
#ifndef HTML_APPFILES_H
#define HTML_APPFILES_H

#include "common.h"
#include "io.h"
#include "stepper.h"
#include "debug.h"
    

String getMainjsAppPage() {
	String site = "optionPageMap = {";
	site += "  1: './control.html',";
	site += "  2: './timelapse.html',";
	site += "  3: './milkyway.html',";
	site += "  4: './tracker.html',";
	site += "  5: './plan.html',";
	site += "  6: './info.html'";
	site += "};";
	site += "";
	site += "function select(optionNr) {";
	site += "";
	site += "  iframe = document.getElementById(\"iframe\");";
	site += "  iframe.src = optionPageMap[optionNr];";
	site += "";
	site += "  wheel = document.getElementById(\"select\");";
	site += "";
	site += "  [1, 2, 3, 4, 5, 6, 7, 8].forEach(element => {";
	site += "    wheel.classList.remove('option' + element);";
	site += "  });";
	site += "";
	site += "  wheel.classList.add('option' + optionNr);";
	site += "};";
	site += "";
	site += "function changeSpeed(sender) {";
	site += "  requestStrings = [";
	site += "    \"\",";
	site += "    \"slide_speed=0.05&pan_speed=0.05\",";
	site += "    \"slide_speed=0.25&pan_speed=0.5\",";
	site += "    \"slide_speed=0.5&pan_speed=1\",";
	site += "    \"slide_speed=1&pan_speed=2\"";
	site += "  ];";
	site += "";
	site += "  makeRequest(requestStrings[sender.value], false);";
	site += "  document.getElementById(\"speed-selection\").innerHTML = ([\"Zero\", \"Extremely Slow\", \"Slow\", \"Middle\", \"Fast\"])[sender.value];";
	site += "};";
	site += "";
	site += "function makeRequest(command, reload = false) {";
	site += "  var url = \"/device/command/?\" + command;";
	site += "  ";
	site += "  var request = new XMLHttpRequest();";
	site += "";
	site += "  request.onreadystatechange = function() {";
	site += "    if (this.readyState == 4 && this.status == 200) {";
	site += "      if(reload) location.reload();";
	site += "    }";
	site += "  };";
	site += "";
	site += "  request.open(\"GET\",url);";
	site += "  request.send();";
	site += "};";
	site += "";
	site += "function getDaytimeInSeconds() {";
	site += "  let now = new Date();";
	site += "  return now.getSeconds() + 60 * now.getMinutes() + 60*60* now.getHours(); ";
	site += "};";
	site += "";
	site += "var streamData = null;";
	site += "function startStreamListener() {";
	site += "  var $event_source_name = new EventSource('../device/stream/');";
	site += "";
	site += "  $event_source_name.addEventListener('event', function(e) { ";
	site += "  var result = JSON.parse( e.data );";
	site += "  ";
	site += "  if(e.lastEventId == 'CLOSE') { console.log(\"Closed stream\"); }";
	site += "  else { ";
	site += "    streamData = result;";
	site += "    updateGUIFromStramData();";
	site += "  }";
	site += "";
	site += "  });";
	site += "";
	site += "  $event_source_name.addEventListener('error', function(e) { $event_source_name.close(); });";
	site += "}";
	site += "";
	site += "classPathMap = {";
	site += "  \"insertSTATE\": (data) => data[\"state\"][\"state\"],";
	site += "  \"insertSTATEDETAIL\": (data) => data[\"state\"][\"detail\"],";
	site += "  \"insertSLIDEPOS\": (data) => data[\"slide\"][\"Position\"],";
	site += "  \"insertSLIDEDIR\": (data) => data[\"slide\"][\"Direction\"],";
	site += "  \"insertSLIDESLEEP\": (data) => data[\"slide\"][\"Sleeping\"],";
	site += "  \"insertPANPOS\": (data) => data[\"pan\"][\"Position\"],";
	site += "  \"insertPANDIR\": (data) => data[\"pan\"][\"Direction\"],";
	site += "  \"insertPANSLEEP\": (data) => data[\"pan\"][\"Sleeping\"],";
	site += "};";
	site += "";
	site += "function updateGUIFromStramData() {";
	site += "  if(!streamData) return;";
	site += "";
	site += "  heartBeat();";
	site += "  updateBattery(streamData['battery']);";
	site += "";
	site += "  for (var classOI in classPathMap) {";
	site += "    if (classPathMap.hasOwnProperty(classOI)) {   ";
	site += "";
	site += "      var elements = document.getElementsByClassName(classOI);";
	site += "      var iFrameElements = document.getElementById(\"iframe\").contentWindow.document.getElementsByClassName(classOI);";
	site += "";
	site += "      [elements, iFrameElements].forEach(list => {";
	site += "";
	site += "        for (var index = 0; index < list.length; index++) {";
	site += "          try {";
	site += "            list[index].innerHTML = classPathMap[classOI](streamData);";
	site += "          } catch (error) {";
	site += "            ";
	site += "          }";
	site += "        }";
	site += "      });";
	site += "      ";
	site += "    }";
	site += "  }";
	site += "}";
	site += "  ";
	site += "function updateBattery(batteryData) {";
	site += "  let batEl = document.querySelector('#battery-fill');";
	site += "";
	site += "  try {";
	site += "    let level = batteryData['level'];";
	site += "    let full = batteryData['full'];";
	site += "    let middle = batteryData['middle'];";
	site += "    let empty = batteryData['empty'];";
	site += "    let critical = batteryData['critical'];";
	site += "";
	site += "    batEl.style.width = Math.max(10, Math.min(100, (level-critical)/(full-critical)*100)) + '%';";
	site += "  ";
	site += "    batEl.style.backgroundColor = 'forestgreen';";
	site += "    if(level <= middle) batEl.style.backgroundColor = '#F4AF00';";
	site += "    if(level <= empty) batEl.style.backgroundColor = '#cc0000';";
	site += "    if(level <= critical) batEl.style.backgroundColor = 'red';";
	site += "";
	site += "  } catch (error) {";
	site += "    batEl.style.width = '50%';";
	site += "    batEl.style.backgroundColor = 'blue';";
	site += "  }";
	site += "}";
	site += "";
	site += "var heartBeatCount = 0;";
	site += "function heartBeat() {";
	site += "  heartBeatCount = 6;";
	site += "  setConnection(true);";
	site += "  setInnerConnection(true);";
	site += "}";
	site += "";
	site += "function setConnection(visible) {";
	site += "  try {";
	site += "    document.querySelector('#connection').style.display = visible ? \"unset\" : \"none\";";
	site += "  } catch (error) { }";
	site += "}";
	site += "";
	site += "function setInnerConnection(antenne) {";
	site += "  try {";
	site += "    document.querySelector('#connection').innerHTML = antenne ? \"&#128225;\" : \"&#10060;\";";
	site += "  } catch (error) { }";
	site += "}";
	site += "";
	site += "setInterval(function() {";
	site += "  heartBeatCount--;";
	site += "  if(heartBeatCount<=0) {";
	site += "    if(heartBeatCount >= -10) {";
	site += "      setConnection(heartBeatCount % 2);";
	site += "    }";
	site += "    else {";
	site += "      setInnerConnection(false);";
	site += "      setConnection(true);";
	site += "    }";
	site += "  }";
	site += "}, 500);";
	site += "";
	site += "";
	site += "var updateTimeRequest = new XMLHttpRequest();";
	site += "updateTimeRequest.open(\"GET\", \"../device/command/?set_time=\" + getDaytimeInSeconds());";
	site += "updateTimeRequest.send();";

	return site;
}

String getMilkywayAppPage() {
	String site = "<!DOCTYPE html>";
	site += "<html lang='en'>";
	site += "<head>";
	site += "  <meta charset='UTF-8'>";
	site += "  <meta name='viewport' content='width=device-width, initial-scale=1.0'>";
	site += "  <title>Milkyway</title>";
	site += "";
	site += "  <link rel='stylesheet' href='definesCss.css'>";
	site += "  <link rel='stylesheet' href='mainCss.css'>";
	site += "";
	site += "  <script src='mainJs.js'></script>";
	site += "</head>";
	site += "<body>";
	site += "  <div class='content'>";
	site += "    <div class='vspace'></div>";
	site += "    <h1>&#127775; Milkyway</h1>";
	site += "    <div class='option-container'>";
	site += "      ";
	site += "      <p>Photos:</p>";
	site += "      <input>";
	site += "      <p class='small'>#</p>";
	site += "";
	site += "      <p>Slide:</p>";
	site += "      <input>";
	site += "      <p class='small'>mm / Step</p>";
	site += "";
	site += "      <p>Photo interval:</p>";
	site += "      <input>";
	site += "      <p class='small'>s / Photo</p>";
	site += "";
	site += "      <p>Step time:</p>";
	site += "      <input>";
	site += "      <p class='small'>s / Step</p>";
	site += "    </div>";
	site += "";
	site += "    <div class='side-container'>";
	site += "      <div class='button main'>&#128640; Shoot Milkyway</div>";
	site += "      <div class='button main'>&#10060;</div>";
	site += "    </div>";
	site += "";
	site += "    <br><br>";
	site += "    <h1>&#127916; Info</h1>";
	site += "";
	site += "    <div class='option-container'>";
	site += "      ";
	site += "      <p>Total time:</p>";
	site += "      <p>213413241234 1234 1234 1234 2</p>";
	site += "      <p class='small'></p>";
	site += "";
	site += "      <p>End time:</p>";
	site += "      <p></p>";
	site += "      <p class='small'></p>";
	site += "";
	site += "      <p></p><p></p><p></p>";
	site += "";
	site += "      <p>Total Slide:</p>";
	site += "      <p></p>";
	site += "      <p class='small'></p>";
	site += "";
	site += "      <p>Total Pan:</p>";
	site += "      <p></p>";
	site += "      <p class='small'></p>      ";
	site += "      ";
	site += "      <p></p><p></p><p></p>";
	site += "";
	site += "      <p>Video (24fps):</p>";
	site += "      <p></p>";
	site += "      <p class='small'></p>";
	site += "      <p>Video (25fps):</p>";
	site += "      <p></p>";
	site += "      <p class='small'></p>";
	site += "      <p>Video (30fps):</p>";
	site += "      <p></p>";
	site += "      <p class='small'></p>";
	site += "      <p>Video (60fps):</p>";
	site += "      <p></p>";
	site += "      <p class='small'></p>";
	site += "    </div>";
	site += "";
	site += "    <div class='closer'></div>";
	site += "  </div>";
	site += "</body>";
	site += "</html>";

	return site;
}

String getIndexAppPage() {
	String site = "<!DOCTYPE html>";
	site += "<html lang='en'>";
	site += "<head>";
	site += "  <meta charset='UTF-8'>";
	site += "  <meta name='viewport' content='width=device-width, initial-scale=1.0'>";
	site += "  <title>Slide and Pan</title>";
	site += "";
	site += "  <link rel='stylesheet' href='definesCss.css'>";
	site += "  <link rel='stylesheet' href='mainCss.css'>";
	site += "";
	site += "  <script src='mainJs.js'></script>";
	site += "</head>";
	site += "<body>";
	site += "  <div id='status-bar'>";
	site += "    <div id='battery'>";
	site += "      <div id='battery-plus-pole'></div>";
	site += "      <div id='battery-fill'></div>";
	site += "      <div id='battery-glas'></div>";
	site += "    </div>";
	site += "";
	site += "    <div class='status left'>";
	site += "      &#128678; <span class='insertSTATE' id='status' onclick='document.getElementById(\"status-bar-detail\").classList.toggle(\"open\");'></span>";
	site += "    </div>";
	site += "";
	site += "    <div id='e-stop' onclick='makeRequest(\"slide_stop&pan_stop\");'>";
	site += "      <p>E-STOP</p>";
	site += "    </div>";
	site += "";
	site += "    <div class='status right'>";
	site += "      <p><span id='connection'>&#128225;</span> &#128247; <span id='camera'>READY</span></p>";
	site += "    </div>";
	site += "  </div>";
	site += "";
	site += "  <div id='status-bar-detail' onclick='document.getElementById(\"status-bar-detail\").classList.remove(\"open\");'>";
	site += "    <h1 class='insertSTATE'></h1>";
	site += "    <p class='insertSTATEDETAIL'>we don\"t know so far</p>";
	site += "  </div>";
	site += "";
	site += "  <div id='select' class='select wheel'>";
	site += "    <div class='select option option1' onclick='select(1);'><p>&#127918;</p></div>";
	site += "    <div class='select option option2' onclick='select(2);'><p>&#9202;</p></div>";
	site += "    <div class='select option option3' onclick='select(3);'><p>&#127775;</p></div>";
	site += "    <div class='select option option4' onclick='select(4);'><p>&#128301;</p></div>";
	site += "    <div class='select option option5' onclick='select(5);'><p>&#128203;</p></div>";
	site += "    <div class='select option option6' onclick='select(6);'><p>&#128209;</p></div>";
	site += "  </div>";
	site += "";
	site += "";
	site += "  <iframe id='iframe' src='' frameBorder='0'></iframe>";
	site += "  <script>select(2); startStreamListener();</script>";
	site += "</body>";
	site += "</html>";

	return site;
}

String getTimelapseAppPage() {
	String site = "<!DOCTYPE html>";
	site += "<html lang='en'>";
	site += "<head>";
	site += "  <meta charset='UTF-8'>";
	site += "  <meta name='viewport' content='width=device-width, initial-scale=1.0'>";
	site += "  <title>Timelapse</title>";
	site += "";
	site += "  <link rel='stylesheet' href='definesCss.css'>";
	site += "  <link rel='stylesheet' href='mainCss.css'>";
	site += "";
	site += "  <script src='mainJs.js'></script>";
	site += "</head>";
	site += "<body>";
	site += "  <div class='content'>";
	site += "    <div class='vspace'></div>";
	site += "    <h1>&#9202; Timelapse</h1>";
	site += "    <div class='option-container'>";
	site += "      ";
	site += "      <p>Photos:</p>";
	site += "      <input>";
	site += "      <p class='small'>#</p>";
	site += "";
	site += "      <p>Slide:</p>";
	site += "      <input>";
	site += "      <p class='small'>mm / Step</p>";
	site += "";
	site += "      <p>Pan:</p>";
	site += "      <input>";
	site += "      <p class='small'>° / Step</p>";
	site += "";
	site += "      <p>Photo interval:</p>";
	site += "      <input>";
	site += "      <p class='small'>s / Photo</p>";
	site += "";
	site += "      <p>Step time:</p>";
	site += "      <input>";
	site += "      <p class='small'>s / Step</p>";
	site += "    </div>";
	site += "";
	site += "    <div class='side-container'>";
	site += "      <div class='button main'>&#128640; Start Timelapse</div>";
	site += "      <div class='button main'>&#10060;</div>";
	site += "      <div class='button main'>&#129488; Preview</div>";
	site += "      <div class='button main'>&#10060;</div>";
	site += "    </div>";
	site += "";
	site += "    <br><br>";
	site += "    <h1>&#127916; Info</h1>";
	site += "";
	site += "    <div class='option-container'>";
	site += "      ";
	site += "      <p>Total time:</p>";
	site += "      <p>213413241234 1234 1234 1234 2</p>";
	site += "      <p class='small'></p>";
	site += "";
	site += "      <p>End time:</p>";
	site += "      <p></p>";
	site += "      <p class='small'></p>";
	site += "";
	site += "      <p></p><p></p><p></p>";
	site += "";
	site += "      <p>Total Slide:</p>";
	site += "      <p></p>";
	site += "      <p class='small'></p>";
	site += "";
	site += "      <p>Total Pan:</p>";
	site += "      <p></p>";
	site += "      <p class='small'></p>      ";
	site += "      ";
	site += "      <p></p><p></p><p></p>";
	site += "";
	site += "      <p>Video (24fps):</p>";
	site += "      <p></p>";
	site += "      <p class='small'></p>";
	site += "      <p>Video (25fps):</p>";
	site += "      <p></p>";
	site += "      <p class='small'></p>";
	site += "      <p>Video (30fps):</p>";
	site += "      <p></p>";
	site += "      <p class='small'></p>";
	site += "      <p>Video (60fps):</p>";
	site += "      <p></p>";
	site += "      <p class='small'></p>";
	site += "    </div>";
	site += "";
	site += "    <div class='closer'></div>";
	site += "  </div>";
	site += "</body>";
	site += "</html>";

	return site;
}

String getInfoAppPage() {
	String site = "<!DOCTYPE html>";
	site += "<html lang='en'>";
	site += "<head>";
	site += "  <meta charset='UTF-8'>";
	site += "  <meta name='viewport' content='width=device-width, initial-scale=1.0'>";
	site += "  <title>Plan</title>";
	site += "";
	site += "  <link rel='stylesheet' href='definesCss.css'>";
	site += "  <link rel='stylesheet' href='mainCss.css'>";
	site += "";
	site += "  <script src='mainJs.js'></script>";
	site += "</head>";
	site += "<body>";
	site += "  <div class='content'>";
	site += "    <div class='vspace'></div>";
	site += "    <h1>&#128209; Info</h1>";
	site += "    ";
	site += "    <br><br>";
	site += "";
	site += "    <div class='main-container'>";
	site += "       ";
	site += "      <h2>&#128640; Slider</h2>";
	site += "      <p>";
	site += "        TODO";
	site += "      </p>";
	site += "";
	site += "      <br><br>";
	site += "";
	site += "      <h2>&#128199; Author</h2>";
	site += "      <p>";
	site += "        TODO";
	site += "      </p>";
	site += "";
	site += "      <br><br>";
	site += "";
	site += "      ";
	site += "      <h2>&#127759; More</h2>";
	site += "      <p>";
	site += "        TODO";
	site += "      </p>";
	site += "";
	site += "      <br><br>";
	site += "";
	site += "      <h2>&#9874; Hardware</h2>";
	site += "      <p>";
	site += "        TODO";
	site += "      </p>";
	site += "";
	site += "      <br><br>";
	site += " ";
	site += "      <h2>&#128655; Constants</h2>";
	site += "      <p>";
	site += "        TODO";
	site += "      </p>";
	site += "";
	site += "      <h2>&#128213; Logs</h2>";
	site += "      <div style='overflow-x: scroll; padding-bottom: 10px;'>";
	site += "        <p style='display: inline; white-space: nowrap; overflow-x: scroll;'>";
	site += "          " + getRingBufferForWeb() + "";
	site += "        </p>";
	site += "      </div>";
	site += "    </div>";
	site += "    ";
	site += "    <div class='closer'></div>";
	site += "  </div>";
	site += "</body>";
	site += "</html>";

	return site;
}

String getDefinescssAppPage() {
	String site = ":root {";
	site += "  --color-red: #cc0000;";
	site += "  --color-red2: #7a0000;";
	site += "  --color-yellow: #F4AF00;";
	site += "  --color-green: forestgreen;";
	site += "  ";
	site += "  --color-light-gray: #C7C7C7;";
	site += "  --color-gray: #7E7E7E;";
	site += "  --color-dark-gray: #4A4A4A;";
	site += "  ";
	site += "  --color-light-white: #F9F9F9;";
	site += "  --color-white: #FAF9F6;";
	site += "  --color-dark-white: #F2F2F2; ";
	site += "  ";
	site += "  --color-first: #0B0C10;";
	site += "  --color-second: #1F2833;";
	site += "  --color-third: #C5C6C7;";
	site += "  --color-fourth: #66FCF1;";
	site += "  --color-fifth: #286090;";
	site += "";
	site += "  --color-background1: #111111;";
	site += "  --color-background2: #353535;";
	site += "  --color-background3: #505050;";
	site += "  --color-front1: #F2F2F2;";
	site += "  --color-front2: tomato;";
	site += "  ";
	site += "  --web-std-width: 960px;";
	site += "}";

	return site;
}

String getControlAppPage() {
	String site = "<!DOCTYPE html>";
	site += "<html lang='en'>";
	site += "<head>";
	site += "  <meta charset='UTF-8'>";
	site += "  <meta name='viewport' content='width=device-width, initial-scale=1.0'>";
	site += "  <title>Control</title>";
	site += "";
	site += "  <link rel='stylesheet' href='definesCss.css'>";
	site += "  <link rel='stylesheet' href='mainCss.css'>";
	site += "";
	site += "  <script src='mainJs.js'></script>";
	site += "</head>";
	site += "<body style='overflow: hidden;'>";
	site += "  <div class='content'>";
	site += "    <div class='vspace'></div>";
	site += "    <h1>&#127918; Control</h1>";
	site += "    <p style='text-align: center; font-size: .7em;'>";
	site += "      <span class='insertSLIDEPOS'>?</span>cm / ";
	site += "      <span class='insertPANPOS'>?</span>°</p>";
	site += "    <div class='control-container'>";
	site += "      <div></div>";
	site += "      <div><div class='button' onclick='makeRequest(\"slide_to=1000000\");'>&#11014;</div></div>";
	site += "      <div></div>";
	site += "";
	site += "      <div><div class='button' onclick='makeRequest(\"pan_to=1000000\");'>&#8618;</div></div>";
	site += "      <div><div class='button stop' onclick='makeRequest(\"slide_stop&pan_stop\");'><p>STOP</p></div></div>";
	site += "      <div><div class='button' onclick='makeRequest(\"pan_to=-1000000\");'>&#8617;</div></div>";
	site += "";
	site += "      <div></div>";
	site += "      <div><div class='button' onclick='makeRequest(\"slide_to=-1000000\");'>&#11015;</div></div>";
	site += "      <div></div>";
	site += "    </div>";
	site += "";
	site += "    <div class='main-container'>";
	site += "      <h3>&#128640; Speed</h3>";
	site += "      <p style='text-align: center;' id='speed-selection'>Fast</p>";
	site += "      <input type='range' min='1' max='4' value='2' class='slider' id='myRange' ";
	site += "          onchange='changeSpeed(this);'>";
	site += "    </div>";
	site += "  </div>";
	site += "</body>";
	site += "</html>";

	return site;
}

String getPlanAppPage() {
	String site = "<!DOCTYPE html>";
	site += "<html lang='en'>";
	site += "<head>";
	site += "  <meta charset='UTF-8'>";
	site += "  <meta name='viewport' content='width=device-width, initial-scale=1.0'>";
	site += "  <title>Plan</title>";
	site += "";
	site += "  <link rel='stylesheet' href='definesCss.css'>";
	site += "  <link rel='stylesheet' href='mainCss.css'>";
	site += "";
	site += "  <script src='mainJs.js'></script>";
	site += "</head>";
	site += "<body>";
	site += "  <div class='content'>";
	site += "    <div class='vspace'></div>";
	site += "    <h1>&#128203; Plan</h1>";
	site += "    ";
	site += "    <p>";
	site += "      TODO";
	site += "    </p>";
	site += "";
	site += "    <br><br>";
	site += "";
	site += "  </div>";
	site += "</body>";
	site += "</html>";

	return site;
}

String getTrackerAppPage() {
	String site = "<!DOCTYPE html>";
	site += "<html lang='en'>";
	site += "<head>";
	site += "  <meta charset='UTF-8'>";
	site += "  <meta name='viewport' content='width=device-width, initial-scale=1.0'>";
	site += "  <title>Tracker</title>";
	site += "";
	site += "  <link rel='stylesheet' href='definesCss.css'>";
	site += "  <link rel='stylesheet' href='mainCss.css'>";
	site += "";
	site += "  <script src='mainJs.js'></script>";
	site += "</head>";
	site += "<body>";
	site += "  <div class='content'>";
	site += "    <div class='vspace'></div>";
	site += "    <h1>&#128301; Star Tracker</h1>";
	site += "    ";
	site += "    <p>";
	site += "";
	site += "    </p>";
	site += "";
	site += "    <br><br>";
	site += "    <div class='side-container'>";
	site += "      <div class='button main'>&#128640; Track Stars</div>";
	site += "      <div class='button main'>&#10060;</div>";
	site += "    </div>";
	site += "";
	site += "  </div>";
	site += "</body>";
	site += "</html>";

	return site;
}

String getMaincssAppPage() {
	String site = "";
	site += "* {";
	site += "  margin: 0;";
	site += "  padding: 0;";
	site += "  font-family: sans-serif;";
	site += "}";
	site += "";
	site += "html, body {";
	site += "  width: 100%;";
	site += "  height: 100%;";
	site += "}";
	site += "";
	site += "h1 { ";
	site += "  text-align: center;";
	site += "}";
	site += "";
	site += ".vspace {";
	site += "  height: 40px;";
	site += "}";
	site += "";
	site += ".content {";
	site += "  max-width: 600px !important;";
	site += "  margin: auto;";
	site += "}";
	site += "";
	site += "#status-bar {";
	site += "  position: fixed;";
	site += "  top: 0;";
	site += "";
	site += "  width: 100%;";
	site += "  height: 30px;";
	site += "";
	site += "  background-color: var(--color-background1);";
	site += "  z-index: 20;";
	site += "}";
	site += "";
	site += "#status-bar #battery {";
	site += "  z-index: 21;";
	site += "";
	site += "  position: relative;";
	site += "  top: 25%;";
	site += "  left: 10px;";
	site += "  height: 33%;";
	site += "  width: 20px;";
	site += "";
	site += "  border: solid var(--color-front1) 2px;";
	site += "  border-radius: 8%;";
	site += "}";
	site += "";
	site += "#status-bar #battery #battery-plus-pole {";
	site += "  position: absolute;";
	site += "  top: 27%;";
	site += "  left: 20px;";
	site += "  height: 20%;";
	site += "  width: 0px;";
	site += "";
	site += "  background-color: var(--color-front1);";
	site += "  border: solid var(--color-front1) 2px;";
	site += "  border-radius: 20%;";
	site += "}";
	site += "";
	site += "#status-bar #battery #battery-fill {";
	site += "  position: absolute;";
	site += "  top: 0;";
	site += "  left: 0;";
	site += "  height: 100%;";
	site += "  width: 80%;";
	site += "";
	site += "  background-color: var(--color-green);";
	site += "}";
	site += "";
	site += "#status-bar #battery #battery-glas {";
	site += "  z-index: 22;";
	site += "";
	site += "  position: absolute;";
	site += "  top: 0;";
	site += "  left: 0;";
	site += "  height: 100%;";
	site += "  width: 100%;";
	site += "";
	site += "  background: rgb(255,255,255);";
	site += "  background: -moz-linear-gradient(180deg, rgba(255,255,255,0) 0%, rgba(249,249,249,0.25) 50%, rgba(249,249,249,.5) 100%);";
	site += "  background: -webkit-linear-gradient(180deg, rgba(255,255,255,0) 0%, rgba(249,249,249,0.25) 50%, rgba(249,249,249,.5) 100%);";
	site += "  background: linear-gradient(180deg, rgba(255,255,255,0) 0%, rgba(249,249,249,0.25) 50%, rgba(249,249,249,.5) 100%);";
	site += "  filter: progid:DXImageTransform.Microsoft.gradient(startColorstr='#ffffff',endColorstr='#f9f9f9',GradientType=1);";
	site += "";
	site += "  display: none;";
	site += "}";
	site += "";
	site += "#status-bar #e-stop {";
	site += "  border: solid var(--color-front2) 1px;";
	site += "  border-radius: 5px;";
	site += "  padding: 5px 20px;";
	site += "";
	site += "  cursor: pointer;";
	site += "  text-align: center;";
	site += "";
	site += "  position: relative;";
	site += "  top: 0;";
	site += "  left: 50%;";
	site += "  width: 50px;";
	site += "";
	site += "  transform: translate(-50%, -50%);";
	site += "}";
	site += "";
	site += "#status-bar #e-stop:hover {";
	site += "  background-color: var(--color-front2);";
	site += "}";
	site += "";
	site += "#status-bar #e-stop p {";
	site += "  color: var(--color-front1);";
	site += "  font-size: .5em;";
	site += "}";
	site += "";
	site += "#status-bar .status {";
	site += "  position: absolute;";
	site += "  top: 8px;";
	site += "  color: var(--color-front1);";
	site += "  font-size: .7em;";
	site += "}";
	site += "";
	site += "#status-bar .status.left {";
	site += "  left: 50px;";
	site += "  cursor: pointer;";
	site += "}";
	site += "";
	site += "#status-bar-detail {";
	site += "  background-color: var(--color-background2);";
	site += "  position: absolute;";
	site += "  top: 30px;";
	site += "  left: 0;";
	site += "  width: 100%;";
	site += "  height: 0;";
	site += "  z-index: 20;";
	site += "";
	site += "  transition: ease .3s all;";
	site += "  overflow: hidden;";
	site += "";
	site += "  color: var(--color-front1);";
	site += "}";
	site += "";
	site += "#status-bar-detail h1 {";
	site += "  margin-top: 10px;";
	site += "  margin-left: 20px;";
	site += "}";
	site += "";
	site += "#status-bar-detail p {";
	site += "  margin-top: 5px;";
	site += "  margin-left: 30px;";
	site += "}";
	site += "";
	site += "#status-bar-detail.open {";
	site += "  height: 100px;";
	site += "}";
	site += "";
	site += "#status-bar .status.right {";
	site += "  right: 10px;";
	site += "}";
	site += "";
	site += "#status-bar #connection {";
	site += "  margin-right: 10px;";
	site += "}";
	site += "";
	site += ".select {";
	site += "  position: fixed;";
	site += "  width: 200vw;";
	site += "  height: 200vw;";
	site += "  min-width: 500px;";
	site += "  min-height: 500px;";
	site += "  max-width: 960px;";
	site += "  max-height: 960px;";
	site += "";
	site += "  border-radius: 50%;";
	site += "  margin: auto;";
	site += "";
	site += "  background-color: var(--color-background1);";
	site += "}";
	site += "";
	site += ".select.wheel {";
	site += "  position: fixed;";
	site += "  left: 50%;";
	site += "  top: 0;";
	site += "  transform: translate(-50%, 85vh);";
	site += "";
	site += "  transition: all .3s ease;";
	site += "";
	site += "  box-shadow: 1px -1px 33px 6px rgba(0,0,0,0.75);";
	site += "  -webkit-box-shadow: 1px -1px 33px 6px rgba(0,0,0,0.75);";
	site += "  -moz-box-shadow: 1px -1px 33px 6px rgba(0,0,0,0.75);";
	site += "";
	site += "  z-index: 20;";
	site += "}";
	site += "";
	site += ".select.wheel.option1 {";
	site += "  transform: translate(-50%, 85vh) rotate(20deg);";
	site += "}";
	site += "";
	site += ".select.wheel.option2 {";
	site += "  transform: translate(-50%, 85vh) rotate(0deg);";
	site += "}";
	site += "";
	site += ".select.wheel.option3 {";
	site += "  transform: translate(-50%, 85vh) rotate(-20deg);";
	site += "}";
	site += "";
	site += ".select.wheel.option4 {";
	site += "  transform: translate(-50%, 85vh) rotate(-40deg);";
	site += "}";
	site += "";
	site += ".select.wheel.option5 {";
	site += "  transform: translate(-50%, 85vh) rotate(-60deg);";
	site += "}";
	site += "";
	site += "";
	site += ".select.wheel.option6 {";
	site += "  transform: translate(-50%, 85vh) rotate(-80deg);";
	site += "}";
	site += "";
	site += ".select.option {";
	site += "  width: 200vw;";
	site += "  height: 200vw;";
	site += "  min-width: 500px;";
	site += "  min-height: 500px;";
	site += "  max-width: 960px;";
	site += "  max-height: 960px;";
	site += "  ";
	site += "  color: var(--color-front1);";
	site += "  font-size: 2em;";
	site += "";
	site += "  background-color: transparent;";
	site += "  border: none;";
	site += "  position: absolute;";
	site += "";
	site += "  text-align: center;";
	site += "  padding-top: 10px;";
	site += "";
	site += "  pointer-events: none;";
	site += "}";
	site += "";
	site += ".select.option p {";
	site += "  pointer-events: all;";
	site += "  cursor: pointer;";
	site += "  display: inline-block;";
	site += "  padding: 5px;";
	site += "}";
	site += "";
	site += ".select.option p:hover {";
	site += "  color: var(--color-front2);";
	site += "}";
	site += "";
	site += ".select.option.option1 {";
	site += "  transform: rotate(-20deg);";
	site += "  z-index: 20;";
	site += "}";
	site += "";
	site += ".select.option.option2 {";
	site += "  transform: rotate(0deg);";
	site += "  z-index: 21;";
	site += "}";
	site += "";
	site += ".select.option.option3 {";
	site += "  transform: rotate(20deg);";
	site += "  z-index: 22;";
	site += "}";
	site += "";
	site += ".select.option.option4 {";
	site += "  transform: rotate(40deg);";
	site += "  z-index: 22;";
	site += "}";
	site += "";
	site += ".select.option.option5 {";
	site += "  transform: rotate(60deg);";
	site += "  z-index: 22;";
	site += "}";
	site += "";
	site += ".select.option.option6 {";
	site += "  transform: rotate(80deg);";
	site += "  z-index: 22;";
	site += "}";
	site += "";
	site += "iframe {";
	site += "  position: absolute;";
	site += "  top: 0;";
	site += "  left: 0;";
	site += "  width: 100%;";
	site += "  height: 100%;";
	site += "  z-index: 1;";
	site += "  margin-top: 30px;";
	site += "}";
	site += "";
	site += ".control-container {";
	site += "  display: grid;";
	site += "  grid-template-columns: 1fr 1fr 1fr;";
	site += "  grid-template-rows: 1fr 1fr 1fr;";
	site += "  gap: 10px 10px;";
	site += "";
	site += "  width: 80%;";
	site += "  margin: 50px auto;";
	site += "}";
	site += "";
	site += ".option-container {";
	site += "  display: grid;";
	site += "  grid-template-columns: 2fr 1fr 1fr;";
	site += "  gap: 5px 10px;";
	site += "";
	site += "  width: 80%;";
	site += "  margin: 50px auto;";
	site += "}";
	site += "";
	site += ".button {";
	site += "  display: inline-block;";
	site += "  text-align: center;";
	site += "  vertical-align: middle;";
	site += "  width: 100%;";
	site += "  height: 100%;";
	site += "  font-size: 3em;";
	site += "";
	site += "  cursor: pointer;";
	site += "";
	site += "  border-radius: 10px;";
	site += "  border: solid var(--color-background1) 2px;";
	site += "";
	site += "  transition: all .3s ease;";
	site += "}";
	site += "";
	site += ".button:hover, .button:active {";
	site += "  border: solid var(--color-front2) 2px;";
	site += "  background-color: var(--color-background3);";
	site += "  color: var(--color-front2);";
	site += "}";
	site += "";
	site += ".button.stop {";
	site += "  font-size: 1em;";
	site += "}";
	site += "";
	site += ".button p {";
	site += "  position: relative;";
	site += "  top: 70%;";
	site += "}";
	site += "";
	site += ".button.main {";
	site += "  width: 80%;";
	site += "  margin: 20px auto;";
	site += "  display: block;";
	site += "  font-size: 1.2em;";
	site += "  padding: 5px 0;";
	site += "}";
	site += "";
	site += "input {";
	site += "  display: inline-block;";
	site += "  text-align: center;";
	site += "  margin: auto;";
	site += "  width: 100%;";
	site += "  color: red;";
	site += "}";
	site += "";
	site += ".main-container {";
	site += "  width: 80%;";
	site += "  margin: 50px auto;";
	site += "}";
	site += "";
	site += ".main-container h2 {";
	site += "  text-align: center;";
	site += "  margin-bottom: 10px;";
	site += "}";
	site += "";
	site += ".side-container {";
	site += "  display: grid;";
	site += "  grid-template-columns: 4fr 1fr;";
	site += "  gap: 20px 10px;";
	site += "  width: 80%;";
	site += "  height: auto;";
	site += "  margin: auto;";
	site += "}";
	site += "";
	site += ".side-container .button {";
	site += "  margin: 0;";
	site += "  width: 100%;";
	site += "  display: inline-table";
	site += "}";
	site += "";
	site += ".small {";
	site += "  font-size: .75em;";
	site += "}";
	site += "";
	site += ".closer {";
	site += "  height: 100px;";
	site += "}";

	return site;
}

#endif