
#ifndef HTML_FILES_H
#define HTML_FILES_H

#include "common.h"
#include "io.h"
#include "stepper.h"
#include "debug.h"
    

void IndexPageHandler(ESP8266WebServer& server) {
	server.sendContent("<!doctype html>");
	server.sendContent("\n");
	server.sendContent("<html lang='en'>");
	server.sendContent("\n");
	server.sendContent("\n");
	server.sendContent("            <head>");
	server.sendContent("            <meta charset='utf-8'>");
	server.sendContent("\n");
	server.sendContent("            <meta charset='utf-8'>");
	server.sendContent("            <meta name='viewport' content='width=device-width, initial-scale=1.0'>");
	server.sendContent("\n");
	server.sendContent("            <title>Slide and Pan</title>");
	server.sendContent("            <meta name='description' content='Slide and Pan'>");
	server.sendContent("            <meta name='author' content='Sebastian Knoll'>");
	server.sendContent("\n");
	server.sendContent("            </head>");
	server.sendContent("          ");
	server.sendContent("\n");
	server.sendContent("<body>");
	server.sendContent("  ");
	server.sendContent("  ");
	server.sendContent("          <style>");
	server.sendContent("            * {");
	server.sendContent("              font-family:courier,arial,helvetica;");
	server.sendContent("            }");
	server.sendContent("\n");
	server.sendContent("            body {");
	server.sendContent("              background-color: rgb(180, 180, 180);");
	server.sendContent("            }");
	server.sendContent("\n");
	server.sendContent("            li {");
	server.sendContent("              display:inline-block;");
	server.sendContent("              margin: 5px;");
	server.sendContent("            }");
	server.sendContent("\n");
	server.sendContent("            ul {");
	server.sendContent("              margin: 0 auto;");
	server.sendContent("              display: inherit;");
	server.sendContent("            }");
	server.sendContent("\n");
	server.sendContent("            h1, h2, h3 {");
	server.sendContent("              text-align: center;");
	server.sendContent("            }");
	server.sendContent("\n");
	server.sendContent("            #container {");
	server.sendContent("              width: 100%;");
	server.sendContent("              max-width: 960px;");
	server.sendContent("              margin: 0 auto;");
	server.sendContent("            }");
	server.sendContent("\n");
	server.sendContent("            .section {");
	server.sendContent("\n");
	server.sendContent("              background: whitesmoke;");
	server.sendContent("              border-radius: 20px;");
	server.sendContent("\n");
	server.sendContent("              padding: 20px;");
	server.sendContent("            }");
	server.sendContent("\n");
	server.sendContent("            input {");
	server.sendContent("              width: 50px;");
	server.sendContent("            }");
	server.sendContent("\n");
	server.sendContent("            .set_button {");
	server.sendContent("              width: 200px;");
	server.sendContent("            }");
	server.sendContent("\n");
	server.sendContent("            .block {");
	server.sendContent("              display: block;");
	server.sendContent("              width: 100%;");
	server.sendContent("              height: 50px;;");
	server.sendContent("            }");
	server.sendContent("\n");
	server.sendContent("          </style>");
	server.sendContent("          ");
	server.sendContent("\n");
	server.sendContent("  ");
	server.sendContent("          <script>");
	server.sendContent("\n");
	server.sendContent("            function makeRequest(command) {");
	server.sendContent("              var url = '/device/command/?' + command;");
	server.sendContent("              ");
	server.sendContent("              var request = new XMLHttpRequest();");
	server.sendContent("\n");
	server.sendContent("              request.onreadystatechange = function() {");
	server.sendContent("                if (this.readyState == 4 && this.status == 200) {");
	server.sendContent("                  location.reload();");
	server.sendContent("                }");
	server.sendContent("              };");
	server.sendContent("\n");
	server.sendContent("              request.open('GET',url);");
	server.sendContent("              request.send();");
	server.sendContent("            }");
	server.sendContent("\n");
	server.sendContent("            function getDaytimeInSeconds() {");
	server.sendContent("              let now = new Date();");
	server.sendContent("              return now.getSeconds() + 60 * now.getMinutes() + 60*60* now.getHours(); ");
	server.sendContent("            }");
	server.sendContent("\n");
	server.sendContent("            var updateTimeRequest = new XMLHttpRequest();");
	server.sendContent("            updateTimeRequest.open('GET', '/device/command/?set_time=' + getDaytimeInSeconds());");
	server.sendContent("            updateTimeRequest.send();");
	server.sendContent("\n");
	server.sendContent("          </script>");
	server.sendContent("          ");
	server.sendContent("\n");
	server.sendContent("  <div id='container'>");
	server.sendContent("    <h1>Manual control</h1>");
	server.sendContent("\n");
	server.sendContent("    <ul>");
	server.sendContent("      <li><a href='index'>Control</a></li>");
	server.sendContent("      <li><a href='timelapse'>Timelapse</a></li>");
	server.sendContent("      <li><a href='settings'>Settings</a></li>");
	server.sendContent("    </ul>");
	server.sendContent("\n");
	server.sendContent("    <br>");
	server.sendContent("\n");
	server.sendContent("    <div class='section'>");
	server.sendContent("      <h2>Control</h2>");
	server.sendContent("      <br>");
	server.sendContent("      <button class='block' onclick='makeRequest(\"slide_to=1000000\");'>Slide Left</button>");
	server.sendContent("      <br>");
	server.sendContent("      <button class='block' onclick='makeRequest(\"slide_to=-1000000\");'>Slide Right</button>");
	server.sendContent("      <br>");
	server.sendContent("      <button class='block' onclick='makeRequest(\"pan_to=1000000\");'>Pan Left</button>");
	server.sendContent("      <br>");
	server.sendContent("      <button class='block' onclick='makeRequest(\"pan_to=-1000000\");'>Pan Right</button>");
	server.sendContent("      <br><br>");
	server.sendContent("      <button class='block' onclick='makeRequest(\"slide_stop&pan_stop\");'>Stop</button>");
	server.sendContent("      <br>");
	server.sendContent("    </div>");
	server.sendContent("\n");
	server.sendContent("    <br><br>");
	server.sendContent("\n");
	server.sendContent("    <div class='section'>");
	server.sendContent("      <h2>Speed</h2>");
	server.sendContent("      <br>");
	server.sendContent("      <button class='block' onclick='makeRequest(\"slide_speed=1&pan_speed=2\");'>Fast</button>");
	server.sendContent("      <br>");
	server.sendContent("      <button class='block' onclick='makeRequest(\"slide_speed=0.5&pan_speed=1\");'>Middle</button>");
	server.sendContent("      <br>");
	server.sendContent("      <button class='block' onclick='makeRequest(\"slide_speed=0.25&pan_speed=0.5\");'>Slow</button>");
	server.sendContent("      <br>");
	server.sendContent("      <button class='block' onclick='makeRequest(\"slide_speed=0.05&pan_speed=0.05\");'>Extrem slow</button>");
	server.sendContent("      <br>");
	server.sendContent("    </div>");
	server.sendContent("\n");
	server.sendContent("    <br><br>");
	server.sendContent("\n");
	server.sendContent("    <div class='section'>");
	server.sendContent("      <h2>Power</h2>");
	server.sendContent("      <br>");
	server.sendContent("      <button class='block' onclick='makeRequest(\"slide_sleep=0&pan_sleep=0\");'>Sleep</button>");
	server.sendContent("      <br>");
	server.sendContent("      <button class='block' onclick='makeRequest(\"slide_sleep=1&pan_sleep=1\");'>Power ON</button>");
	server.sendContent("      <br>");
	server.sendContent("    </div>");
	server.sendContent("\n");
	server.sendContent("    <br>");
	server.sendContent("    <br>");
	server.sendContent("\n");
	server.sendContent("    <a style='text-align: center; display: block;' href='about'>About</a>");
	server.sendContent("\n");
	server.sendContent("    <br>");
	server.sendContent("    <br>");
	server.sendContent("  </div>");
	server.sendContent("</body>");
	server.sendContent("</html>");
}

void TimelapsePageHandler(ESP8266WebServer& server) {
	server.sendContent("<!doctype html>");
	server.sendContent("\n");
	server.sendContent("<html lang='en'>");
	server.sendContent("\n");
	server.sendContent("\n");
	server.sendContent("            <head>");
	server.sendContent("            <meta charset='utf-8'>");
	server.sendContent("\n");
	server.sendContent("            <meta charset='utf-8'>");
	server.sendContent("            <meta name='viewport' content='width=device-width, initial-scale=1.0'>");
	server.sendContent("\n");
	server.sendContent("            <title>Slide and Pan</title>");
	server.sendContent("            <meta name='description' content='Slide and Pan'>");
	server.sendContent("            <meta name='author' content='Sebastian Knoll'>");
	server.sendContent("\n");
	server.sendContent("            </head>");
	server.sendContent("          ");
	server.sendContent("\n");
	server.sendContent("<body>");
	server.sendContent("  ");
	server.sendContent("  ");
	server.sendContent("          <style>");
	server.sendContent("            * {");
	server.sendContent("              font-family:courier,arial,helvetica;");
	server.sendContent("            }");
	server.sendContent("\n");
	server.sendContent("            body {");
	server.sendContent("              background-color: rgb(180, 180, 180);");
	server.sendContent("            }");
	server.sendContent("\n");
	server.sendContent("            li {");
	server.sendContent("              display:inline-block;");
	server.sendContent("              margin: 5px;");
	server.sendContent("            }");
	server.sendContent("\n");
	server.sendContent("            ul {");
	server.sendContent("              margin: 0 auto;");
	server.sendContent("              display: inherit;");
	server.sendContent("            }");
	server.sendContent("\n");
	server.sendContent("            h1, h2, h3 {");
	server.sendContent("              text-align: center;");
	server.sendContent("            }");
	server.sendContent("\n");
	server.sendContent("            #container {");
	server.sendContent("              width: 100%;");
	server.sendContent("              max-width: 960px;");
	server.sendContent("              margin: 0 auto;");
	server.sendContent("            }");
	server.sendContent("\n");
	server.sendContent("            .section {");
	server.sendContent("\n");
	server.sendContent("              background: whitesmoke;");
	server.sendContent("              border-radius: 20px;");
	server.sendContent("\n");
	server.sendContent("              padding: 20px;");
	server.sendContent("            }");
	server.sendContent("\n");
	server.sendContent("            input {");
	server.sendContent("              width: 50px;");
	server.sendContent("            }");
	server.sendContent("\n");
	server.sendContent("            .set_button {");
	server.sendContent("              width: 200px;");
	server.sendContent("            }");
	server.sendContent("\n");
	server.sendContent("            .block {");
	server.sendContent("              display: block;");
	server.sendContent("              width: 100%;");
	server.sendContent("              height: 50px;;");
	server.sendContent("            }");
	server.sendContent("\n");
	server.sendContent("          </style>");
	server.sendContent("          ");
	server.sendContent("\n");
	server.sendContent("  ");
	server.sendContent("          <script>");
	server.sendContent("\n");
	server.sendContent("            function makeRequest(command) {");
	server.sendContent("              var url = '/device/command/?' + command;");
	server.sendContent("              ");
	server.sendContent("              var request = new XMLHttpRequest();");
	server.sendContent("\n");
	server.sendContent("              request.onreadystatechange = function() {");
	server.sendContent("                if (this.readyState == 4 && this.status == 200) {");
	server.sendContent("                  location.reload();");
	server.sendContent("                }");
	server.sendContent("              };");
	server.sendContent("\n");
	server.sendContent("              request.open('GET',url);");
	server.sendContent("              request.send();");
	server.sendContent("            }");
	server.sendContent("\n");
	server.sendContent("            function getDaytimeInSeconds() {");
	server.sendContent("              let now = new Date();");
	server.sendContent("              return now.getSeconds() + 60 * now.getMinutes() + 60*60* now.getHours(); ");
	server.sendContent("            }");
	server.sendContent("\n");
	server.sendContent("            var updateTimeRequest = new XMLHttpRequest();");
	server.sendContent("            updateTimeRequest.open('GET', '/device/command/?set_time=' + getDaytimeInSeconds());");
	server.sendContent("            updateTimeRequest.send();");
	server.sendContent("\n");
	server.sendContent("          </script>");
	server.sendContent("          ");
	server.sendContent("\n");
	server.sendContent("  <div id='container'>");
	server.sendContent("    <h1>Timelapse</h1>");
	server.sendContent("\n");
	server.sendContent("    <ul>");
	server.sendContent("      <li><a href='index'>Control</a></li>");
	server.sendContent("      <li><a href='timelapse'>Timelapse</a></li>");
	server.sendContent("      <li><a href='settings'>Settings</a></li>");
	server.sendContent("    </ul>");
	server.sendContent("\n");
	server.sendContent("    <br>");
	server.sendContent("\n");
	server.sendContent("    <div class='section'>");
	server.sendContent("      <h2>Milkyway</h2>");
	server.sendContent("      <br>");
	server.sendContent("      <p style='display: inline-block;'>Slide:</p> ");
	server.sendContent("      <input value='" + String(getTimelapseSlideSteps()) + "' step='0.001' min='-5000' max='5000' id='mw_slide'> " + (getSlideStepper()->getPhysicalValueUnit()) + "\n");
	server.sendContent("      <br>");
	server.sendContent("      <p style='display: inline-block;'>Photo count:</p>");
	server.sendContent("      <input value='" + String(getTimelapsePictureCount()) + "' min='0' max='5000' id='mw_count'> #");
	server.sendContent("      <br>");
	server.sendContent("      <p style='display: inline-block;'>Exposure Time:</p>");
	server.sendContent("      <input value='" + String(getIOBoard()->getCameraExposureTime()) + "' step='0.1' min='0' max='500' id='mw_photo'> s");
	server.sendContent("      <br>");
	server.sendContent("      <p style='display: inline-block;'>Interval Time:</p> ");
	server.sendContent("      <input value='" + String(getTimelapseInterval()) + "' min='0' max='500' id='mw_interval'> s");
	server.sendContent("      <br>");
	server.sendContent("      <p style='display: inline-block;'>Hemisphere: <a href='#' onclick='makeRequest(\"timelapse_set_hemisphere=" + String(!isTimelapseInNortherHemisphere() ? 1 : 0) + "\");'><i>" + (isTimelapseInNortherHemisphere() ? "Northern" : "South") + "</i></a></p> ");
	server.sendContent("      <br>");
	server.sendContent("      <button class='block' onclick='makeRequest(\"timelapse_slide=\" + document.getElementById(\"mw_slide\").value + \"&timelapse_count=\" + document.getElementById(\"mw_count\").value + \"&timelapse_photo=\" + document.getElementById(\"mw_photo\").value + \"&timelapse_interval=\" + document.getElementById(\"mw_interval\").value + \"&timelapse_milkyway_settings=1\");'>Shoot Milkyway</button>");
	server.sendContent("      <br>");
	server.sendContent("      <br>");
	server.sendContent("      <p style='display: inline-block;'>Pan set to: " + String(getTimelapsePanSteps()) + "\n" + (getPanStepper()->getPhysicalValueUnit()) + "</p>");
	server.sendContent("      <br>");
	server.sendContent("    </div>");
	server.sendContent("\n");
	server.sendContent("    <br><br>");
	server.sendContent("\n");
	server.sendContent("    <div class='section'>");
	server.sendContent("      <h2>Start / Stop</h2>");
	server.sendContent("      <br>");
	server.sendContent("      <button class='block' onclick='makeRequest(\"timelapse_start\");'>Start Timelapse</button>");
	server.sendContent("      <br>");
	server.sendContent("      <button class='block' onclick='makeRequest(\"timelapse_stop\");'>Stop Timelapse</button>");
	server.sendContent("      <br>");
	server.sendContent("      <br>");
	server.sendContent("      <button class='block' onclick='makeRequest(\"timelapse_preview_start\");'>Start Preview</button>");
	server.sendContent("      <br>");
	server.sendContent("      <button class='block' onclick='makeRequest(\"timelapse_preview_stop\");'>Stop Preview</button>");
	server.sendContent("      <br>");
	server.sendContent("    </div>");
	server.sendContent("\n");
	server.sendContent("    <br><br>");
	server.sendContent("\n");
	server.sendContent("    <div class='section'>");
	server.sendContent("      <h2>Manual</h2>");
	server.sendContent("      <br>");
	server.sendContent("      <input value='" + String(getTimelapsePanSteps()) + "' type='number' step='0.001' min='-5000' max='5000' id='pan'> " + (getPanStepper()->getPhysicalValueUnit()) + "\n");
	server.sendContent("      <button class='set_button' onclick='makeRequest(\"timelapse_pan=\" + document.getElementById(\"pan\").value);'>Set Pan</button>");
	server.sendContent("      <br>");
	server.sendContent("      <input value='" + String(getTimelapseSlideSteps()) + "' type='number' step='0.001' min='-5000' max='5000' id='slide'> " + (getSlideStepper()->getPhysicalValueUnit()) + "\n");
	server.sendContent("      <button class='set_button' onclick='makeRequest(\"timelapse_slide=\" + document.getElementById(\"slide\").value);'>Set Slide</button>");
	server.sendContent("      <br>");
	server.sendContent("      <input value='" + String(getTimelapsePictureCount()) + "' min='0' max='5000' id='count'> #");
	server.sendContent("      <button class='set_button' onclick='makeRequest(\"timelapse_count=\" + document.getElementById(\"count\").value);'>Set Picture count</button>");
	server.sendContent("      <br>");
	server.sendContent("      <input value='" + String(getIOBoard()->getCameraExposureTime()) + "' step='0.1' min='0' max='500' id='photo'> s");
	server.sendContent("      <button class='set_button' onclick='makeRequest(\"timelapse_photo=\" + document.getElementById(\"photo\").value);'>Set Photo Interval</button>");
	server.sendContent("      <br>");
	server.sendContent("      <input value='" + String(getTimelapseInterval()) + "' min='0' max='500' id='interval'> s");
	server.sendContent("      <button class='set_button' onclick='makeRequest(\"timelapse_interval=\" + document.getElementById(\"interval\").value);'>Set Timelapse interval</button>");
	server.sendContent("      <br>");
	server.sendContent("      <br>");
	server.sendContent("      <button class='block' onclick='makeRequest(\"timelapse_slide=\" + document.getElementById(\"slide\").value + \"&timelapse_count=\" + document.getElementById(\"count\").value + \"&timelapse_photo=\" + document.getElementById(\"photo\").value + \"&timelapse_interval=\" + document.getElementById(\"interval\").value + \"&timelapse_pan=\" + document.getElementById(\"pan\").value);'>Set all</button>");
	server.sendContent("      <br>");
	server.sendContent("    </div>");
	server.sendContent("\n");
	server.sendContent("    <br><br>");
	server.sendContent("\n");
	server.sendContent("    <div class='section'>");
	server.sendContent("      <h2>Timelapse-Info</h2>");
	server.sendContent("\n");
	server.sendContent("      <br>");
	server.sendContent("      <p>Total time: <i>" + secondsToString(getTimelapseTotalTime()) + "</i></p>");
	server.sendContent("      <p>End time: <i>" + secondsToTimeString(getTimelapseEndTime()) + "</i></p>");
	server.sendContent("      <br>");
	server.sendContent("      <p>Total slide: <i>" + String(getTimelapseTotalSlideDistance()) + "</i> " + (getSlideStepper()->getPhysicalValueUnit()) + "</p>");
	server.sendContent("      <p>Total pan: <i>" + String(getTimelapseTotalPanDistance()) + "</i> " + (getPanStepper()->getPhysicalValueUnit()) + "</p>");
	server.sendContent("      <br>");
	server.sendContent("      <p>Video length (24fps): <i>" + secondsToString(getTimelapseVideoTimePrediction(24)) + "</i></p>");
	server.sendContent("      <p>Video length (25fps): <i>" + secondsToString(getTimelapseVideoTimePrediction(25)) + "</i></p>");
	server.sendContent("      <p>Video length (30fps): <i>" + secondsToString(getTimelapseVideoTimePrediction(30)) + "</i></p>");
	server.sendContent("      <p>Video length (60fps): <i>" + secondsToString(getTimelapseVideoTimePrediction(60)) + "</i></p>");
	server.sendContent("      <br>");
	server.sendContent("    </div>");
	server.sendContent("  </div>");
	server.sendContent("\n");
	server.sendContent("  <br>");
	server.sendContent("  <br>");
	server.sendContent("\n");
	server.sendContent("  <a style='text-align: center; display: block;' href='about'>About</a>");
	server.sendContent("\n");
	server.sendContent("  <br>");
	server.sendContent("  <br>");
	server.sendContent("</body>");
	server.sendContent("</html>");
}

void SettingsPageHandler(ESP8266WebServer& server) {
	server.sendContent("<!doctype html>");
	server.sendContent("\n");
	server.sendContent("<html lang='en'>");
	server.sendContent("\n");
	server.sendContent("\n");
	server.sendContent("            <head>");
	server.sendContent("            <meta charset='utf-8'>");
	server.sendContent("\n");
	server.sendContent("            <meta charset='utf-8'>");
	server.sendContent("            <meta name='viewport' content='width=device-width, initial-scale=1.0'>");
	server.sendContent("\n");
	server.sendContent("            <title>Slide and Pan</title>");
	server.sendContent("            <meta name='description' content='Slide and Pan'>");
	server.sendContent("            <meta name='author' content='Sebastian Knoll'>");
	server.sendContent("\n");
	server.sendContent("            </head>");
	server.sendContent("          ");
	server.sendContent("\n");
	server.sendContent("<body>");
	server.sendContent("\n");
	server.sendContent("  ");
	server.sendContent("          <style>");
	server.sendContent("            * {");
	server.sendContent("              font-family:courier,arial,helvetica;");
	server.sendContent("            }");
	server.sendContent("\n");
	server.sendContent("            body {");
	server.sendContent("              background-color: rgb(180, 180, 180);");
	server.sendContent("            }");
	server.sendContent("\n");
	server.sendContent("            li {");
	server.sendContent("              display:inline-block;");
	server.sendContent("              margin: 5px;");
	server.sendContent("            }");
	server.sendContent("\n");
	server.sendContent("            ul {");
	server.sendContent("              margin: 0 auto;");
	server.sendContent("              display: inherit;");
	server.sendContent("            }");
	server.sendContent("\n");
	server.sendContent("            h1, h2, h3 {");
	server.sendContent("              text-align: center;");
	server.sendContent("            }");
	server.sendContent("\n");
	server.sendContent("            #container {");
	server.sendContent("              width: 100%;");
	server.sendContent("              max-width: 960px;");
	server.sendContent("              margin: 0 auto;");
	server.sendContent("            }");
	server.sendContent("\n");
	server.sendContent("            .section {");
	server.sendContent("\n");
	server.sendContent("              background: whitesmoke;");
	server.sendContent("              border-radius: 20px;");
	server.sendContent("\n");
	server.sendContent("              padding: 20px;");
	server.sendContent("            }");
	server.sendContent("\n");
	server.sendContent("            input {");
	server.sendContent("              width: 50px;");
	server.sendContent("            }");
	server.sendContent("\n");
	server.sendContent("            .set_button {");
	server.sendContent("              width: 200px;");
	server.sendContent("            }");
	server.sendContent("\n");
	server.sendContent("            .block {");
	server.sendContent("              display: block;");
	server.sendContent("              width: 100%;");
	server.sendContent("              height: 50px;;");
	server.sendContent("            }");
	server.sendContent("\n");
	server.sendContent("          </style>");
	server.sendContent("          ");
	server.sendContent("\n");
	server.sendContent("  ");
	server.sendContent("          <script>");
	server.sendContent("\n");
	server.sendContent("            function makeRequest(command) {");
	server.sendContent("              var url = '/device/command/?' + command;");
	server.sendContent("              ");
	server.sendContent("              var request = new XMLHttpRequest();");
	server.sendContent("\n");
	server.sendContent("              request.onreadystatechange = function() {");
	server.sendContent("                if (this.readyState == 4 && this.status == 200) {");
	server.sendContent("                  location.reload();");
	server.sendContent("                }");
	server.sendContent("              };");
	server.sendContent("\n");
	server.sendContent("              request.open('GET',url);");
	server.sendContent("              request.send();");
	server.sendContent("            }");
	server.sendContent("\n");
	server.sendContent("            function getDaytimeInSeconds() {");
	server.sendContent("              let now = new Date();");
	server.sendContent("              return now.getSeconds() + 60 * now.getMinutes() + 60*60* now.getHours(); ");
	server.sendContent("            }");
	server.sendContent("\n");
	server.sendContent("            var updateTimeRequest = new XMLHttpRequest();");
	server.sendContent("            updateTimeRequest.open('GET', '/device/command/?set_time=' + getDaytimeInSeconds());");
	server.sendContent("            updateTimeRequest.send();");
	server.sendContent("\n");
	server.sendContent("          </script>");
	server.sendContent("          ");
	server.sendContent("\n");
	server.sendContent("  <div id='container'>");
	server.sendContent("    <h1>Settings</h1>");
	server.sendContent("\n");
	server.sendContent("    <ul>");
	server.sendContent("      <li><a href='index'>Control</a></li>");
	server.sendContent("      <li><a href='timelapse'>Timelapse</a></li>");
	server.sendContent("      <li><a href='settings'>Settings</a></li>");
	server.sendContent("    </ul>");
	server.sendContent("\n");
	server.sendContent("    <br>");
	server.sendContent("\n");
	server.sendContent("    <div class='section'>");
	server.sendContent("      <h2>Slide</h2>");
	server.sendContent("      <br>");
	server.sendContent("      <p>" + (getSlideStepper()->getPhysicalValueDescription()) + ": <i>" + (getSlideStepper()->getPhysicalValueInfo()) + "</i> <button onclick='makeRequest(\"slide_reset\");'>Center</button></p>");
	server.sendContent("      <input type='number' value='" + (getSlideStepper()->getPhysicalValueInfo()) + "' step='0.001' min='-50000' max='50000' id='slide_pv'>");
	server.sendContent("      <button class='set_button' onclick='makeRequest(\"slide_physical_value=\" + document.getElementById(\"slide_pv\").value);'>Go to " + (getSlideStepper()->getPhysicalValueDescription()) + "</button>");
	server.sendContent("      <br>");
	server.sendContent("      <br>");
	server.sendContent("      <p>Sleep: <i>" + String(getSlideStepper()->isSleeping() ? "Sleeping" : "Awake") + "</i> <button onclick='makeRequest(\"slide_sleep=" + String(getSlideStepper()->isSleeping() ? 1 : 0) + "\");'>" + String(getSlideStepper()->isSleeping() ? "Awake" : "Sleep") + "</button></p>");
	server.sendContent("      <p>Steps: <i>" + String(getSlideStepper()->getSteps()) + "</i>/<i>" + String(getSlideStepper()->getTargetSteps()) + "</i></p>");
	server.sendContent("      <p>Speed: <i>" + String(getSlideStepper()->getSpeed()) + "</i>/<i>" + String(getSlideStepper()->getTargetSpeed()) + "</i></p>");
	server.sendContent("      <p>LazyMode: <i>" + String(getSlideStepper()->isInLazyMode() ? "Yes" : "No") + "</i> <button onclick='makeRequest(\"slide_lazy=" + String(getSlideStepper()->isInLazyMode() ? 0 : 1) + "\");'>" + String(getSlideStepper()->isInLazyMode() ? "Go Strong" : "Go Lazy") + "</button></p>");
	server.sendContent("      <br>");
	server.sendContent("      <p>Resolution: <i>" + String(getSlideStepper()->getResolution()) + "</i></p>");
	server.sendContent("      ");
	server.sendContent("      <div>");
	server.sendContent("        <button onclick='makeRequest(\"slide_res=1\");'>1</button>");
	server.sendContent("        <button onclick='makeRequest(\"slide_res=2\");'>2</button>");
	server.sendContent("        <button onclick='makeRequest(\"slide_res=4\");'>4</button>");
	server.sendContent("        <button onclick='makeRequest(\"slide_res=8\");'>8</button>");
	server.sendContent("        <button onclick='makeRequest(\"slide_res=16\");'>16</button>");
	server.sendContent("      </div>");
	server.sendContent("      <br>");
	server.sendContent("    </div>");
	server.sendContent("\n");
	server.sendContent("    <br><br>");
	server.sendContent("\n");
	server.sendContent("    <div class='section'>");
	server.sendContent("      <h2>Pan</h2>");
	server.sendContent("      <br>");
	server.sendContent("      <p>" + (getPanStepper()->getPhysicalValueDescription()) + ": <i>" + (getPanStepper()->getPhysicalValueInfo()) + "</i> <button onclick='makeRequest(\"pan_reset\");'>Center</button></p>");
	server.sendContent("      <input type='number' value='" + (getPanStepper()->getPhysicalValueInfo()) + "' step='0.001' min='-50000' max='50000' id='pan_pv'>");
	server.sendContent("      <button class='set_button' onclick='makeRequest(\"pan_physical_value=\" + document.getElementById(\"pan_pv\").value);'>Go to " + (getPanStepper()->getPhysicalValueDescription()) + "</button>");
	server.sendContent("      <br>");
	server.sendContent("      <br>");
	server.sendContent("      <p>Sleep: <i>" + String(getPanStepper()->isSleeping() ? "Sleeping" : "Awake") + "</i> <button onclick='makeRequest(\"pan_sleep=" + String(getPanStepper()->isSleeping() ? 1 : 0) + "\");'>" + String(getPanStepper()->isSleeping() ? "Awake" : "Sleep") + "</button></p>");
	server.sendContent("      <p>Steps: <i>" + String(getPanStepper()->getSteps()) + "</i>/<i>" + String(getPanStepper()->getTargetSteps()) + "</i></p>");
	server.sendContent("      <p>Speed: <i>" + String(getPanStepper()->getSpeed()) + "</i>/<i>" + String(getPanStepper()->getTargetSpeed()) + "</i></p>");
	server.sendContent("      <p>LazyMode: <i>" + String(getPanStepper()->isInLazyMode() ? "Yes" : "No") + "</i> <button onclick='makeRequest(\"pan_lazy=" + String(getPanStepper()->isInLazyMode() ? 0 : 1) + "\");'>" + String(getPanStepper()->isInLazyMode() ? "Go Strong" : "Go Lazy") + "</button></p>");
	server.sendContent("      <br>");
	server.sendContent("      <p>Resolution: <i>" + String(getPanStepper()->getResolution()) + "</i></p>");
	server.sendContent("      ");
	server.sendContent("      <div>");
	server.sendContent("        <button onclick='makeRequest(\"pan_res=1\");'>1</button>");
	server.sendContent("        <button onclick='makeRequest(\"pan_res=2\");'>2</button>");
	server.sendContent("        <button onclick='makeRequest(\"pan_res=4\");'>4</button>");
	server.sendContent("        <button onclick='makeRequest(\"pan_res=8\");'>8</button>");
	server.sendContent("        <button onclick='makeRequest(\"pan_res=16\");'>16</button>");
	server.sendContent("      </div>");
	server.sendContent("      <br>");
	server.sendContent("    </div>");
	server.sendContent("\n");
	server.sendContent("    <br><br>");
	server.sendContent("\n");
	server.sendContent("    <div class='section'>");
	server.sendContent("      <h2>Additional</h2>");
	server.sendContent("      <br>");
	server.sendContent("      <p>Battery-Level: <i>" + String(getIOBoard()->getBatteryLevel()) + "</i></p>");
	server.sendContent("      <br>");
	server.sendContent("      <p>S/P LazyMode: <i>" + String(getPanStepper()->isInLazyMode() ? "Yes" : "No") + "</i>/<i>" + String(getPanStepper()->isInLazyMode() ? "Yes" : "No") + "</i></p>");
	server.sendContent("      <button onclick='makeRequest(\"pan_lazy=1&slide_lazy=1\");'>Set both Lazy</button>");
	server.sendContent("      <button onclick='makeRequest(\"pan_lazy=0&slide_lazy=0\");'>Set both Strong</button>");
	server.sendContent("      <br>");
	server.sendContent("      <br>");
	server.sendContent("      <br>");
	server.sendContent("      <p id='darkMode' name='darkMode'>DarkMode: <a href='#darkMode' onclick='makeRequest(\"set_darkmode=" + String(isSliderInDarkMode() ? 0 : 1) + "\");'><i>" + (isSliderInDarkMode() ? "is On" : "is Off") + "</i></a></p>");
	server.sendContent("      <br>");
	server.sendContent("    </div>");
	server.sendContent("\n");
	server.sendContent("    <br>");
	server.sendContent("    <br>");
	server.sendContent("\n");
	server.sendContent("    <div class='section'>");
	server.sendContent("      <h2>Logs</h2>");
	server.sendContent("      <br>");
	server.sendContent("      <div style='overflow-x: scroll; padding-bottom: 10px;'>");
	server.sendContent("        <p style='display: inline; white-space: nowrap; overflow-x: scroll;'>" + getRingBufferForWeb() + "</p>");
	server.sendContent("      </div>");
	server.sendContent("      <br>");
	server.sendContent("    </div>");
	server.sendContent("  </div>");
	server.sendContent("\n");
	server.sendContent("  <br>");
	server.sendContent("  <br>");
	server.sendContent("\n");
	server.sendContent("  <a style='text-align: center; display: block;' href='about'>About</a>");
	server.sendContent("\n");
	server.sendContent("  <br>");
	server.sendContent("  <br>");
	server.sendContent("</body>");
	server.sendContent("</html>");
}

void Slider_detailPageHandler(ESP8266WebServer& server) {
	server.sendContent("<!doctype html>");
	server.sendContent("\n");
	server.sendContent("<html lang='en'>");
	server.sendContent("\n");
	server.sendContent("\n");
	server.sendContent("            <head>");
	server.sendContent("            <meta charset='utf-8'>");
	server.sendContent("\n");
	server.sendContent("            <meta charset='utf-8'>");
	server.sendContent("            <meta name='viewport' content='width=device-width, initial-scale=1.0'>");
	server.sendContent("\n");
	server.sendContent("            <title>Slide and Pan</title>");
	server.sendContent("            <meta name='description' content='Slide and Pan'>");
	server.sendContent("            <meta name='author' content='Sebastian Knoll'>");
	server.sendContent("\n");
	server.sendContent("            </head>");
	server.sendContent("          ");
	server.sendContent("\n");
	server.sendContent("<body>");
	server.sendContent("  ");
	server.sendContent("          <style>");
	server.sendContent("            * {");
	server.sendContent("              font-family:courier,arial,helvetica;");
	server.sendContent("            }");
	server.sendContent("\n");
	server.sendContent("            body {");
	server.sendContent("              background-color: rgb(180, 180, 180);");
	server.sendContent("            }");
	server.sendContent("\n");
	server.sendContent("            li {");
	server.sendContent("              display:inline-block;");
	server.sendContent("              margin: 5px;");
	server.sendContent("            }");
	server.sendContent("\n");
	server.sendContent("            ul {");
	server.sendContent("              margin: 0 auto;");
	server.sendContent("              display: inherit;");
	server.sendContent("            }");
	server.sendContent("\n");
	server.sendContent("            h1, h2, h3 {");
	server.sendContent("              text-align: center;");
	server.sendContent("            }");
	server.sendContent("\n");
	server.sendContent("            #container {");
	server.sendContent("              width: 100%;");
	server.sendContent("              max-width: 960px;");
	server.sendContent("              margin: 0 auto;");
	server.sendContent("            }");
	server.sendContent("\n");
	server.sendContent("            .section {");
	server.sendContent("\n");
	server.sendContent("              background: whitesmoke;");
	server.sendContent("              border-radius: 20px;");
	server.sendContent("\n");
	server.sendContent("              padding: 20px;");
	server.sendContent("            }");
	server.sendContent("\n");
	server.sendContent("            input {");
	server.sendContent("              width: 50px;");
	server.sendContent("            }");
	server.sendContent("\n");
	server.sendContent("            .set_button {");
	server.sendContent("              width: 200px;");
	server.sendContent("            }");
	server.sendContent("\n");
	server.sendContent("            .block {");
	server.sendContent("              display: block;");
	server.sendContent("              width: 100%;");
	server.sendContent("              height: 50px;;");
	server.sendContent("            }");
	server.sendContent("\n");
	server.sendContent("          </style>");
	server.sendContent("          ");
	server.sendContent("\n");
	server.sendContent("  ");
	server.sendContent("          <script>");
	server.sendContent("\n");
	server.sendContent("            function makeRequest(command) {");
	server.sendContent("              var url = '/device/command/?' + command;");
	server.sendContent("              ");
	server.sendContent("              var request = new XMLHttpRequest();");
	server.sendContent("\n");
	server.sendContent("              request.onreadystatechange = function() {");
	server.sendContent("                if (this.readyState == 4 && this.status == 200) {");
	server.sendContent("                  location.reload();");
	server.sendContent("                }");
	server.sendContent("              };");
	server.sendContent("\n");
	server.sendContent("              request.open('GET',url);");
	server.sendContent("              request.send();");
	server.sendContent("            }");
	server.sendContent("\n");
	server.sendContent("            function getDaytimeInSeconds() {");
	server.sendContent("              let now = new Date();");
	server.sendContent("              return now.getSeconds() + 60 * now.getMinutes() + 60*60* now.getHours(); ");
	server.sendContent("            }");
	server.sendContent("\n");
	server.sendContent("            var updateTimeRequest = new XMLHttpRequest();");
	server.sendContent("            updateTimeRequest.open('GET', '/device/command/?set_time=' + getDaytimeInSeconds());");
	server.sendContent("            updateTimeRequest.send();");
	server.sendContent("\n");
	server.sendContent("          </script>");
	server.sendContent("          ");
	server.sendContent("\n");
	server.sendContent("  <div id='container'>");
	server.sendContent("    <h1>Slider in detail</h1>");
	server.sendContent("\n");
	server.sendContent("    <ul>");
	server.sendContent("      <li><a href='index'>Control</a></li>");
	server.sendContent("      <li><a href='timelapse'>Timelapse</a></li>");
	server.sendContent("      <li><a href='settings'>Settings</a></li>");
	server.sendContent("    </ul>");
	server.sendContent("\n");
	server.sendContent("    <br>");
	server.sendContent("\n");
	server.sendContent("    <div class='section'>");
	server.sendContent("      <h2>Slider Inforamtion</h2>");
	server.sendContent("      <br>");
	server.sendContent("      <p>Name: <i>" + String(SLIDEANDPAN_NAME) + "</i></p>");
	server.sendContent("      <p>Version: <i>" + String(SLIDEANDPAN_VERSION) + "</i></p>");
	server.sendContent("      <p>Copyright: <i>" + String(SLIDEANDPAN_COPYRIGHT) + "</i></p>");
	server.sendContent("      <p>ID: <i>" + String(SLIDEANDPAN_ID) + "</i></p>");
	server.sendContent("      <br>");
	server.sendContent("      <p>Note: <i>" + String(SLIDEANDPAN_ID_INFO) + "</i></p>");
	server.sendContent("      <p>Ver.-Info: <i>" + String(SLIDEANDPAN_VERSION_INFO) + "</i></p>");
	server.sendContent("      <br>");
	server.sendContent("    </div>");
	server.sendContent("\n");
	server.sendContent("    <br><br>");
	server.sendContent("\n");
	server.sendContent("    <div class='section'>");
	server.sendContent("      <h2>Hardware - Slide</h2>");
	server.sendContent("      <br>");
	server.sendContent("      <p>Direction Pin: <i>" + String(SLIDE_STEPPER_PIN_DIRECTION) + "</i></p>");
	server.sendContent("      <p>Step Pin <i>" + String(SLIDE_STEPPER_PIN_STEP) + "</i></p>");
	server.sendContent("      <p>Sleep Pin <i>" + String(SLIDE_STEPPER_PIN_SLEEP) + "</i></p>");
	server.sendContent("      <p>Steps / Turn: <i>" + String(STEPPER_STEPS_PER_TURN) + "</i></p>");
	server.sendContent("      <p>Can change res.: <i>" + String(getSlideStepper()->hasChangeResolutionMethod() ? "Yes" : "No") + "</i></p>");
	server.sendContent("      <br>");
	server.sendContent("      <p>Driver M1 Pin <i>" + String(SLIDE_STEPPER_DRIVER_M1) + "</i></p>");
	server.sendContent("      <p>Driver M2 Pin <i>" + String(SLIDE_STEPPER_DRIVER_M2) + "</i></p>");
	server.sendContent("      <p>Driver M3 Pin <i>" + String(SLIDE_STEPPER_DRIVER_M3) + "</i></p>");
	server.sendContent("      <br>");
	server.sendContent("    </div>");
	server.sendContent("\n");
	server.sendContent("    <br><br>");
	server.sendContent("\n");
	server.sendContent("    <div class='section'>");
	server.sendContent("      <h2>Hardware - Pan</h2>");
	server.sendContent("      <br>");
	server.sendContent("      <p>Direction Pin: <i>" + String(PAN_STEPPER_PIN_DIRECTION) + "</i></p>");
	server.sendContent("      <p>Step Pin <i>" + String(PAN_STEPPER_PIN_STEP) + "</i></p>");
	server.sendContent("      <p>Sleep Pin <i>" + String(PAN_STEPPER_PIN_SLEEP) + "</i></p>");
	server.sendContent("      <p>Steps / Turn: <i>" + String(STEPPER_STEPS_PER_TURN) + "</i></p>");
	server.sendContent("      <p>Can change res.: <i>" + String(getPanStepper()->hasChangeResolutionMethod() ? "Yes" : "No") + "</i></p>");
	server.sendContent("      <br>");
	server.sendContent("      <p>Driver M1 Pin <i>" + String(PAN_STEPPER_DRIVER_M1) + "</i></p>");
	server.sendContent("      <p>Driver M2 Pin <i>" + String(PAN_STEPPER_DRIVER_M2) + "</i></p>");
	server.sendContent("      <p>Driver M3 Pin <i>" + String(PAN_STEPPER_DRIVER_M3) + "</i></p>");
	server.sendContent("      <br>");
	server.sendContent("    </div>");
	server.sendContent("\n");
	server.sendContent("    <br><br>");
	server.sendContent("\n");
	server.sendContent("    <div class='section'>");
	server.sendContent("      <h2>IO Board</h2>");
	server.sendContent("      <br>");
	server.sendContent("      <p>Latch Pin: <i>" + String(PIN_LATCH) + "</i></p>");
	server.sendContent("      <p>Clock Pin: <i>" + String(PIN_CLOCK) + "</i></p>");
	server.sendContent("      <p>DataOut Pin: <i>" + String(PIN_DATAOUT) + "</i></p>");
	server.sendContent("      <p>DataIn Pin: <i>" + String(PIN_DATAIN) + "</i></p>");
	server.sendContent("      <p>LatchIn Pin: <i>" + String(PIN_LATCHIN) + "</i></p>");
	server.sendContent("      <br>");
	server.sendContent("      <p>Enc. CLK Pin: <i>" + String(ENCODER_PIN_CLK) + "</i></p>");
	server.sendContent("      <p>Enc. DIR Pin: <i>" + String(ENCODER_PIN_DIRECTION) + "</i></p>");
	server.sendContent("      <p>Enc. Switch Pin: <i>" + String(ENCODER_PIN_SWITCH) + "</i></p>");
	server.sendContent("      <br>");
	server.sendContent("      <p>Battery AI Pin: <i>" + String(PIN_BATTERY) + "</i></p>");
	server.sendContent("      <br>");
	server.sendContent("    </div>");
	server.sendContent("\n");
	server.sendContent("    <br><br>");
	server.sendContent("\n");
	server.sendContent("    <div class='section'>");
	server.sendContent("      <h2>Constants</h2>");
	server.sendContent("      <br>");
	server.sendContent("      <p>Gear diameter: <i>" + String(SLIDE_GEAR_DIAMETER) + "</i></p>");
	server.sendContent("      <p>Gear cog number: <i>" + String(PAN_GEAR_SMALL_COG_NUMBER) + "</i></p>");
	server.sendContent("      <p>Big gear cog number: <i>" + String(PAN_GEAR_LARGE_COG_NUMBER) + "</i></p>");
	server.sendContent("      <p>Earth rotation: <i>" + secondsToString(EARTH_SECONDS_PER_DAY) + "</i></p>");
	server.sendContent("      <p>Moon rotation: <i>" + secondsToString(MOON_SECONDS_PER_TURN) + "</i></p>");
	server.sendContent("      ");
	server.sendContent("      <br>");
	server.sendContent("    </div>");
	server.sendContent("\n");
	server.sendContent("    <br><br>");
	server.sendContent("\n");
	server.sendContent("    <div class='section'>");
	server.sendContent("      <h2>Time</h2>");
	server.sendContent("      <br>");
	server.sendContent("      <p>Slider Time: <i>" + secondsToTimeString(getTime()) + "</i></p>");
	server.sendContent("      <br>");
	server.sendContent("      <button class='block' onclick='makeRequest(\"\");'>Set time</button>");
	server.sendContent("      <br>");
	server.sendContent("    </div>");
	server.sendContent("  </div>");
	server.sendContent("\n");
	server.sendContent("  <br>");
	server.sendContent("  <br>");
	server.sendContent("\n");
	server.sendContent("  ");
	server.sendContent("</body>");
	server.sendContent("</html>");
}

void AboutPageHandler(ESP8266WebServer& server) {
	server.sendContent("<!doctype html>");
	server.sendContent("\n");
	server.sendContent("<html lang='en'>");
	server.sendContent("\n");
	server.sendContent("\n");
	server.sendContent("            <head>");
	server.sendContent("            <meta charset='utf-8'>");
	server.sendContent("\n");
	server.sendContent("            <meta charset='utf-8'>");
	server.sendContent("            <meta name='viewport' content='width=device-width, initial-scale=1.0'>");
	server.sendContent("\n");
	server.sendContent("            <title>Slide and Pan</title>");
	server.sendContent("            <meta name='description' content='Slide and Pan'>");
	server.sendContent("            <meta name='author' content='Sebastian Knoll'>");
	server.sendContent("\n");
	server.sendContent("            </head>");
	server.sendContent("          ");
	server.sendContent("\n");
	server.sendContent("<body>");
	server.sendContent("  ");
	server.sendContent("          <style>");
	server.sendContent("            * {");
	server.sendContent("              font-family:courier,arial,helvetica;");
	server.sendContent("            }");
	server.sendContent("\n");
	server.sendContent("            body {");
	server.sendContent("              background-color: rgb(180, 180, 180);");
	server.sendContent("            }");
	server.sendContent("\n");
	server.sendContent("            li {");
	server.sendContent("              display:inline-block;");
	server.sendContent("              margin: 5px;");
	server.sendContent("            }");
	server.sendContent("\n");
	server.sendContent("            ul {");
	server.sendContent("              margin: 0 auto;");
	server.sendContent("              display: inherit;");
	server.sendContent("            }");
	server.sendContent("\n");
	server.sendContent("            h1, h2, h3 {");
	server.sendContent("              text-align: center;");
	server.sendContent("            }");
	server.sendContent("\n");
	server.sendContent("            #container {");
	server.sendContent("              width: 100%;");
	server.sendContent("              max-width: 960px;");
	server.sendContent("              margin: 0 auto;");
	server.sendContent("            }");
	server.sendContent("\n");
	server.sendContent("            .section {");
	server.sendContent("\n");
	server.sendContent("              background: whitesmoke;");
	server.sendContent("              border-radius: 20px;");
	server.sendContent("\n");
	server.sendContent("              padding: 20px;");
	server.sendContent("            }");
	server.sendContent("\n");
	server.sendContent("            input {");
	server.sendContent("              width: 50px;");
	server.sendContent("            }");
	server.sendContent("\n");
	server.sendContent("            .set_button {");
	server.sendContent("              width: 200px;");
	server.sendContent("            }");
	server.sendContent("\n");
	server.sendContent("            .block {");
	server.sendContent("              display: block;");
	server.sendContent("              width: 100%;");
	server.sendContent("              height: 50px;;");
	server.sendContent("            }");
	server.sendContent("\n");
	server.sendContent("          </style>");
	server.sendContent("          ");
	server.sendContent("\n");
	server.sendContent("  ");
	server.sendContent("          <script>");
	server.sendContent("\n");
	server.sendContent("            function makeRequest(command) {");
	server.sendContent("              var url = '/device/command/?' + command;");
	server.sendContent("              ");
	server.sendContent("              var request = new XMLHttpRequest();");
	server.sendContent("\n");
	server.sendContent("              request.onreadystatechange = function() {");
	server.sendContent("                if (this.readyState == 4 && this.status == 200) {");
	server.sendContent("                  location.reload();");
	server.sendContent("                }");
	server.sendContent("              };");
	server.sendContent("\n");
	server.sendContent("              request.open('GET',url);");
	server.sendContent("              request.send();");
	server.sendContent("            }");
	server.sendContent("\n");
	server.sendContent("            function getDaytimeInSeconds() {");
	server.sendContent("              let now = new Date();");
	server.sendContent("              return now.getSeconds() + 60 * now.getMinutes() + 60*60* now.getHours(); ");
	server.sendContent("            }");
	server.sendContent("\n");
	server.sendContent("            var updateTimeRequest = new XMLHttpRequest();");
	server.sendContent("            updateTimeRequest.open('GET', '/device/command/?set_time=' + getDaytimeInSeconds());");
	server.sendContent("            updateTimeRequest.send();");
	server.sendContent("\n");
	server.sendContent("          </script>");
	server.sendContent("          ");
	server.sendContent("\n");
	server.sendContent("  <div id='container'>");
	server.sendContent("    <h1>About</h1>");
	server.sendContent("\n");
	server.sendContent("    <ul>");
	server.sendContent("      <li><a href='index'>Control</a></li>");
	server.sendContent("      <li><a href='timelapse'>Timelapse</a></li>");
	server.sendContent("      <li><a href='settings'>Settings</a></li>");
	server.sendContent("    </ul>");
	server.sendContent("\n");
	server.sendContent("    <br>");
	server.sendContent("\n");
	server.sendContent("    <div class='section'>");
	server.sendContent("      <h2>Slider Inforamtion</h2>");
	server.sendContent("      <br>");
	server.sendContent("      <p>Name: <i>" + String(SLIDEANDPAN_NAME) + "</i></p>");
	server.sendContent("      <p>Version: <i>" + String(SLIDEANDPAN_VERSION) + "</i></p>");
	server.sendContent("      <p>Copyright: <i>" + String(SLIDEANDPAN_COPYRIGHT) + "</i></p>");
	server.sendContent("      <p>ID: <i>" + String(SLIDEANDPAN_ID) + "</i></p>");
	server.sendContent("      <br>");
	server.sendContent("      <a style='text-align: center; display: block;' href='detail'>More details</a>");
	server.sendContent("\n");
	server.sendContent("      <br>");
	server.sendContent("    </div>");
	server.sendContent("\n");
	server.sendContent("    <br><br>");
	server.sendContent("\n");
	server.sendContent("    <div class='section'>");
	server.sendContent("      <h2>Author</h2>");
	server.sendContent("      <br>");
	server.sendContent("      <p>");
	server.sendContent("        My name is <i>Sebastian Knoll</i> and I am the inventor and author of this project. ");
	server.sendContent("        If you have any question regarding me or the app do not hesitate to ");
	server.sendContent("        <a href='https://sebastianknoll.net/me/contact.php'>contact me</a> or visit my ");
	server.sendContent("        <a href='https://sebastianknoll.net/'>homepage</a>. ");
	server.sendContent("        <br>");
	server.sendContent("        <br>");
	server.sendContent("        If you have any legal concerns, note that this is an private application ");
	server.sendContent("        which you can use at your own risk. Furthermore you can checkout ");
	server.sendContent("        <a href='https://sebastianknoll.net/gtc/'>legal stuff</a> and ");
	server.sendContent("        <a href='https://sebastianknoll.net/gtc/TODO'>legal stuff for Slide and Pan</a>.");
	server.sendContent("      </p>");
	server.sendContent("      <br>");
	server.sendContent("    </div>");
	server.sendContent("\n");
	server.sendContent("    <br><br>");
	server.sendContent("\n");
	server.sendContent("    <div class='section'>");
	server.sendContent("      <h2>More</h2>");
	server.sendContent("      <br>");
	server.sendContent("      <p>");
	server.sendContent("      Use the Hashtag <a href='https://www.instagram.com/explore/tags/slideandpan/'>#slideandpan</a> so that we can see your amazing work.");
	server.sendContent("      </p>");
	server.sendContent("      <br>");
	server.sendContent("      <p>Use the <a href='" + String(SLIDEANDPAN_LINK_HANDBOOK) + "'>Handbook</a> for more information and tutorials.</p>");
	server.sendContent("      <br>");
	server.sendContent("    </div>");
	server.sendContent("  </div>");
	server.sendContent("\n");
	server.sendContent("  <br>");
	server.sendContent("  <br>");
	server.sendContent("\n");
	server.sendContent("  ");
	server.sendContent("</body>");
	server.sendContent("</html>");
}

void Normal_timelapsePageHandler(ESP8266WebServer& server) {
	server.sendContent("<!doctype html>");
	server.sendContent("\n");
	server.sendContent("<html lang='en'>");
	server.sendContent("\n");
	server.sendContent("<head>");
	server.sendContent("  <meta charset=\"utf-8\">");
	server.sendContent("\n");
	server.sendContent("  <meta charset=\"utf-8\">");
	server.sendContent("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">");
	server.sendContent("\n");
	server.sendContent("  <title>Slide and Pan</title>");
	server.sendContent("  <meta name=\"description\" content=\"Slide and Pan\">");
	server.sendContent("  <meta name=\"author\" content=\"Sebastian Knoll\">");
	server.sendContent("\n");
	server.sendContent("</head>");
	server.sendContent("\n");
	server.sendContent("<body>");
	server.sendContent("  ");
	server.sendContent("  <style>");
	server.sendContent("    * {");
	server.sendContent("      font-family:courier,arial,helvetica;");
	server.sendContent("    }");
	server.sendContent("\n");
	server.sendContent("    body {");
	server.sendContent("      background-color: rgb(180, 180, 180);");
	server.sendContent("    }");
	server.sendContent("\n");
	server.sendContent("    li {");
	server.sendContent("      display:inline-block;");
	server.sendContent("      margin: 5px;");
	server.sendContent("    }");
	server.sendContent("\n");
	server.sendContent("    ul {");
	server.sendContent("      margin: 0 auto;");
	server.sendContent("      display: inherit;");
	server.sendContent("    }");
	server.sendContent("\n");
	server.sendContent("    h1, h2, h3 {");
	server.sendContent("      text-align: center;");
	server.sendContent("    }");
	server.sendContent("\n");
	server.sendContent("    #container {");
	server.sendContent("      width: 100%;");
	server.sendContent("      max-width: 960px;");
	server.sendContent("      margin: 0 auto;");
	server.sendContent("    }");
	server.sendContent("\n");
	server.sendContent("    .section {");
	server.sendContent("\n");
	server.sendContent("      background: whitesmoke;");
	server.sendContent("      border-radius: 20px;");
	server.sendContent("\n");
	server.sendContent("      padding: 20px;");
	server.sendContent("    }");
	server.sendContent("\n");
	server.sendContent("    input {");
	server.sendContent("      width: 50px;");
	server.sendContent("    }");
	server.sendContent("\n");
	server.sendContent("    .set_button {");
	server.sendContent("      width: 200px;");
	server.sendContent("    }");
	server.sendContent("\n");
	server.sendContent("    .block {");
	server.sendContent("      display: block;");
	server.sendContent("      width: 100%;");
	server.sendContent("      height: 50px;;");
	server.sendContent("    }");
	server.sendContent("\n");
	server.sendContent("  </style>");
	server.sendContent("\n");
	server.sendContent("  <script>");
	server.sendContent("\n");
	server.sendContent("    function makeRequest(command) {");
	server.sendContent("      var url = '/device/command/?' + command;");
	server.sendContent("      ");
	server.sendContent("      var request = new XMLHttpRequest();");
	server.sendContent("\n");
	server.sendContent("      request.onreadystatechange = function() {");
	server.sendContent("        if (this.readyState == 4 && this.status == 200) {");
	server.sendContent("          location.reload();");
	server.sendContent("        }");
	server.sendContent("      };");
	server.sendContent("\n");
	server.sendContent("      request.open('GET',url);");
	server.sendContent("      request.send();");
	server.sendContent("    }");
	server.sendContent("\n");
	server.sendContent("  </script>");
	server.sendContent("\n");
	server.sendContent("  <div id='container'>");
	server.sendContent("    <h1>Timelapse</h1>");
	server.sendContent("\n");
	server.sendContent("    <ul>");
	server.sendContent("      <li><a href='index'>Control</a></li>");
	server.sendContent("      <li><a href='timelapse'>Timelapse</a></li>");
	server.sendContent("      <li><a href='settings'>Settings</a></li>");
	server.sendContent("    </ul>");
	server.sendContent("\n");
	server.sendContent("    <br>");
	server.sendContent("\n");
	server.sendContent("    <div class='section'>");
	server.sendContent("      <h2>Milkyway</h2>");
	server.sendContent("      <br>");
	server.sendContent("      <p style='display: inline-block;'>Slide:</p> ");
	server.sendContent("      <input value='" + String(getTimelapseSlideSteps()) + "' step='0.001' min='-5000' max='5000' id='mw_slide'> " + (getSlideStepper()->getPhysicalValueUnit()) + "\n");
	server.sendContent("      <br>");
	server.sendContent("      <p style='display: inline-block;'>Photo count:</p>");
	server.sendContent("      <input value='" + String(getTimelapsePictureCount()) + "' min='0' max='5000' id='mw_count'> #");
	server.sendContent("      <br>");
	server.sendContent("      <p style='display: inline-block;'>Exposure Time:</p>");
	server.sendContent("      <input value='" + String(getIOBoard()->getCameraExposureTime()) + "' min='0' max='500' id='mw_photo'> s");
	server.sendContent("      <br>");
	server.sendContent("      <p style='display: inline-block;'>Interval Time:</p> ");
	server.sendContent("      <input value='" + String(getTimelapseInterval()) + "' min='0' max='500' id='mw_interval'> s");
	server.sendContent("      <br>");
	server.sendContent("      <button class='block' onclick='makeRequest(\"timelapse_slide=\" + document.getElementById(\"mw_slide\").value + \"&timelapse_count=\" + document.getElementById(\"mw_count\").value + \"&timelapse_photo=\" + document.getElementById(\"mw_photo\").value + \"&timelapse_interval=\" + document.getElementById(\"mw_interval\").value + \"&timelapse_milkyway_settings=1\");'>Shoot Milkyway</button>");
	server.sendContent("      <br>");
	server.sendContent("      <br>");
	server.sendContent("      <p style='display: inline-block;'>Pan set to: " + String(getTimelapsePanSteps()) + "\n" + (getPanStepper()->getPhysicalValueUnit()) + "</p>");
	server.sendContent("      <br>");
	server.sendContent("    </div>");
	server.sendContent("\n");
	server.sendContent("    <br><br>");
	server.sendContent("\n");
	server.sendContent("    <div class='section'>");
	server.sendContent("      <h2>Start / Stop</h2>");
	server.sendContent("      <br>");
	server.sendContent("      <button class='block' onclick='makeRequest(\"timelapse_start\");'>Start Timelapse</button>");
	server.sendContent("      <br>");
	server.sendContent("      <button class='block' onclick='makeRequest(\"timelapse_stop\");'>Stop Timelapse</button>");
	server.sendContent("      <br>");
	server.sendContent("      <br>");
	server.sendContent("      <button class='block' onclick='makeRequest(\"timelapse_preview_start\");'>Start Preview</button>");
	server.sendContent("      <br>");
	server.sendContent("      <button class='block' onclick='makeRequest(\"timelapse_preview_stop\");'>Stop Preview</button>");
	server.sendContent("      <br>");
	server.sendContent("    </div>");
	server.sendContent("\n");
	server.sendContent("    <br><br>");
	server.sendContent("\n");
	server.sendContent("    <div class='section'>");
	server.sendContent("      <h2>Manual</h2>");
	server.sendContent("      <br>");
	server.sendContent("      <input value='" + String(getTimelapsePanSteps()) + "' type='number' step='0.001' min='-5000' max='5000' id='pan'> " + (getPanStepper()->getPhysicalValueUnit()) + "\n");
	server.sendContent("      <button class='set_button' onclick='makeRequest(\"timelapse_pan=\" + document.getElementById(\"pan\").value);'>Set Pan</button>");
	server.sendContent("      <br>");
	server.sendContent("      <input value='" + String(getTimelapseSlideSteps()) + "' type='number' step='0.001' min='-5000' max='5000' id='slide'> " + (getSlideStepper()->getPhysicalValueUnit()) + "\n");
	server.sendContent("      <button class='set_button' onclick='makeRequest(\"timelapse_slide=\" + document.getElementById(\"slide\").value);'>Set Slide</button>");
	server.sendContent("      <br>");
	server.sendContent("      <input value='" + String(getTimelapsePictureCount()) + "' min='0' max='5000' id='count'> #");
	server.sendContent("      <button class='set_button' onclick='makeRequest(\"timelapse_count=\" + document.getElementById(\"count\").value);'>Set Picture count</button>");
	server.sendContent("      <br>");
	server.sendContent("      <input value='" + String(getIOBoard()->getCameraExposureTime()) + "' min='0' max='500' id='photo'> s");
	server.sendContent("      <button class='set_button' onclick='makeRequest(\"timelapse_photo=\" + document.getElementById(\"photo\").value);'>Set Photo Interval</button>");
	server.sendContent("      <br>");
	server.sendContent("      <input value='" + String(getTimelapseInterval()) + "' min='0' max='500' id='interval'> s");
	server.sendContent("      <button class='set_button' onclick='makeRequest(\"timelapse_interval=\" + document.getElementById(\"interval\").value);'>Set Timelapse interval</button>");
	server.sendContent("      <br>");
	server.sendContent("      <br>");
	server.sendContent("      <button class='block' onclick='makeRequest(\"timelapse_slide=\" + document.getElementById(\"slide\").value + \"&timelapse_count=\" + document.getElementById(\"count\").value + \"&timelapse_photo=\" + document.getElementById(\"photo\").value + \"&timelapse_interval=\" + document.getElementById(\"interval\").value + \"&timelapse_pan=\" + document.getElementById(\"pan\").value);'>Set all</button>");
	server.sendContent("      <br>");
	server.sendContent("    </div>");
	server.sendContent("\n");
	server.sendContent("    <br><br>");
	server.sendContent("\n");
	server.sendContent("    <div class='section'>");
	server.sendContent("      <h2>Timelapse-Info</h2>");
	server.sendContent("\n");
	server.sendContent("      <br>");
	server.sendContent("      <p>Total time: <i>" + secondsToString(getTimelapseTotalTime()) + "</i></p>");
	server.sendContent("      <p>Total slide: <i>" + String(getTimelapseTotalSlideDistance()) + "</i> " + (getSlideStepper()->getPhysicalValueUnit()) + "</p>");
	server.sendContent("      <p>Total pan: <i>" + String(getTimelapseTotalPanDistance()) + "</i> " + (getPanStepper()->getPhysicalValueUnit()) + "</p>");
	server.sendContent("      <br>");
	server.sendContent("      <p>Video length (24fps): <i>" + secondsToString(getTimelapseVideoTimePrediction(24)) + "</i></p>");
	server.sendContent("      <p>Video length (25fps): <i>" + secondsToString(getTimelapseVideoTimePrediction(25)) + "</i></p>");
	server.sendContent("      <p>Video length (30fps): <i>" + secondsToString(getTimelapseVideoTimePrediction(30)) + "</i></p>");
	server.sendContent("      <p>Video length (60fps): <i>" + secondsToString(getTimelapseVideoTimePrediction(60)) + "</i></p>");
	server.sendContent("      <br>");
	server.sendContent("    </div>");
	server.sendContent("  </div>");
	server.sendContent("\n");
	server.sendContent("  <br>");
	server.sendContent("  <br>");
	server.sendContent("\n");
	server.sendContent("  <a style='text-align: center; display: block;' href='about'>About</a>");
	server.sendContent("\n");
	server.sendContent("  <br>");
	server.sendContent("  <br>");
	server.sendContent("</body>");
	server.sendContent("</html>");
}

#endif