
#ifndef HTML_APPFILES_H
#define HTML_APPFILES_H

#include "common.h"
#include "io.h"
#include "stepper.h"
#include "debug.h"
    

void MainjsAppPageHandler(ESP8266WebServer& server) {
	server.sendContent(F("optionPageMap = {"));
	server.sendContent(F("  1: './control.html',"));
	server.sendContent(F("  2: './timelapse.html',"));
	server.sendContent(F("  3: './milkyway.html',"));
	server.sendContent(F("  4: './tracker.html',"));
	server.sendContent(F("  5: './plan.html',"));
	server.sendContent(F("  6: './info.html'"));
	server.sendContent(F("};"));
	server.sendContent(F("\n"));
	server.sendContent(F("function select(optionNr) {"));
	server.sendContent(F("\n"));
	server.sendContent(F("  iframe = document.getElementById(\"iframe\");"));
	server.sendContent(F("  iframe.src = optionPageMap[optionNr];"));
	server.sendContent(F("\n"));
	server.sendContent(F("  wheel = document.getElementById(\"select\");"));
	server.sendContent(F("\n"));
	server.sendContent(F("  [1, 2, 3, 4, 5, 6, 7, 8].forEach(element => {"));
	server.sendContent(F("    wheel.classList.remove('option' + element);"));
	server.sendContent(F("  });"));
	server.sendContent(F("\n"));
	server.sendContent(F("  wheel.classList.add('option' + optionNr);"));
	server.sendContent(F("};"));
	server.sendContent(F("\n"));
	server.sendContent(F("function changeSpeed(sender) {"));
	server.sendContent(F("  requestStrings = ["));
	server.sendContent(F("    \"\","));
	server.sendContent(F("    \"slide_speed=0.05&pan_speed=0.05\","));
	server.sendContent(F("    \"slide_speed=0.25&pan_speed=0.5\","));
	server.sendContent(F("    \"slide_speed=0.5&pan_speed=1\","));
	server.sendContent(F("    \"slide_speed=1&pan_speed=2\"\n"));
	server.sendContent(F("  ];"));
	server.sendContent(F("\n"));
	server.sendContent(F("  makeRequest(requestStrings[sender.value], false);"));
	server.sendContent(F("  document.getElementById(\"speed-selection\").innerHTML = ([\"Zero\", \"Extremely Slow\", \"Slow\", \"Middle\", \"Fast\"])[sender.value];"));
	server.sendContent(F("};"));
	server.sendContent(F("\n"));
	server.sendContent(F("function makeRequest(command, reload = false) {"));
	server.sendContent(F("  var url = \"/device/command/?\" + command;"));
	server.sendContent(F("  "));
	server.sendContent(F("  var request = new XMLHttpRequest();"));
	server.sendContent(F("\n"));
	server.sendContent(F("  request.onreadystatechange = function() {"));
	server.sendContent(F("    if (this.readyState == 4 && this.status == 200) {"));
	server.sendContent(F("      if(reload) location.reload();"));
	server.sendContent(F("    }"));
	server.sendContent(F("  };"));
	server.sendContent(F("\n"));
	server.sendContent(F("  request.open(\"GET\",url);"));
	server.sendContent(F("  request.send();"));
	server.sendContent(F("};"));
	server.sendContent(F("\n"));
	server.sendContent(F("function getDaytimeInSeconds() {"));
	server.sendContent(F("  let now = new Date();"));
	server.sendContent(F("  return now.getSeconds() + 60 * now.getMinutes() + 60*60* now.getHours(); "));
	server.sendContent(F("};"));
	server.sendContent(F("\n"));
	server.sendContent(F("var streamData = null;"));
	server.sendContent(F("function startStreamListener() {"));
	server.sendContent(F("  var $event_source_name = new EventSource('../device/stream/');"));
	server.sendContent(F("\n"));
	server.sendContent(F("  $event_source_name.addEventListener('event', function(e) { "));
	server.sendContent(F("  var result = JSON.parse( e.data );"));
	server.sendContent(F("  "));
	server.sendContent(F("  if(e.lastEventId == 'CLOSE') { console.log(\"Closed stream\"); }"));
	server.sendContent(F("  else { "));
	server.sendContent(F("    streamData = result;"));
	server.sendContent(F("    updateGUIFromStramData();"));
	server.sendContent(F("  }"));
	server.sendContent(F("\n"));
	server.sendContent(F("  });"));
	server.sendContent(F("\n"));
	server.sendContent(F("  $event_source_name.addEventListener('error', function(e) { $event_source_name.close(); });"));
	server.sendContent(F("}"));
	server.sendContent(F("\n"));
	server.sendContent(F("classPathMap = {"));
	server.sendContent(F("  \"insertSTATE\": (data) => data[\"state\"][\"state\"],"));
	server.sendContent(F("  \"insertSTATEDETAIL\": (data) => data[\"state\"][\"detail\"],"));
	server.sendContent(F("  \"insertSLIDEPOS\": (data) => data[\"slide\"][\"Position\"],"));
	server.sendContent(F("  \"insertSLIDEDIR\": (data) => data[\"slide\"][\"Direction\"],"));
	server.sendContent(F("  \"insertSLIDESLEEP\": (data) => data[\"slide\"][\"Sleeping\"],"));
	server.sendContent(F("  \"insertPANPOS\": (data) => data[\"pan\"][\"Position\"],"));
	server.sendContent(F("  \"insertPANDIR\": (data) => data[\"pan\"][\"Direction\"],"));
	server.sendContent(F("  \"insertPANSLEEP\": (data) => data[\"pan\"][\"Sleeping\"],"));
	server.sendContent(F("};"));
	server.sendContent(F("\n"));
	server.sendContent(F("function updateGUIFromStramData() {"));
	server.sendContent(F("  if(!streamData) return;"));
	server.sendContent(F("\n"));
	server.sendContent(F("  heartBeat();"));
	server.sendContent(F("  updateBattery(streamData['battery']);"));
	server.sendContent(F("  updatePowerState(streamData['slide']['Sleeping'], streamData['pan']['Sleeping'])"));
	server.sendContent(F("\n"));
	server.sendContent(F("  for (var classOI in classPathMap) {"));
	server.sendContent(F("    if (classPathMap.hasOwnProperty(classOI)) {   "));
	server.sendContent(F("      updateGUIValue(classOI, classPathMap[classOI](streamData));"));
	server.sendContent(F("    }"));
	server.sendContent(F("  }"));
	server.sendContent(F("}"));
	server.sendContent(F("\n"));
	server.sendContent(F("function updateGUIValue(classOI, value) {"));
	server.sendContent(F("\n"));
	server.sendContent(F("  var elements = document.getElementsByClassName(classOI);"));
	server.sendContent(F("\n"));
	server.sendContent(F("  ifr = document.getElementById(\"iframe\");"));
	server.sendContent(F("  var iFrameElements = ifr "));
	server.sendContent(F("    ? document.getElementById(\"iframe\").contentWindow.document.getElementsByClassName(classOI)"));
	server.sendContent(F("    : [];"));
	server.sendContent(F("\n"));
	server.sendContent(F("  [elements, iFrameElements].forEach(list => {"));
	server.sendContent(F("\n"));
	server.sendContent(F("    for (var index = 0; index < list.length; index++) {"));
	server.sendContent(F("      try {"));
	server.sendContent(F("        list[index].innerHTML = value;"));
	server.sendContent(F("      } catch (error) {"));
	server.sendContent(F("        "));
	server.sendContent(F("      }"));
	server.sendContent(F("    }"));
	server.sendContent(F("  });"));
	server.sendContent(F("}"));
	server.sendContent(F("  "));
	server.sendContent(F("function updateBattery(batteryData) {"));
	server.sendContent(F("  let batEl = document.querySelector('#battery-fill');"));
	server.sendContent(F("\n"));
	server.sendContent(F("  try {"));
	server.sendContent(F("    let level = batteryData['level'];"));
	server.sendContent(F("    let full = batteryData['full'];"));
	server.sendContent(F("    let middle = batteryData['middle'];"));
	server.sendContent(F("    let empty = batteryData['empty'];"));
	server.sendContent(F("    let critical = batteryData['critical'];"));
	server.sendContent(F("\n"));
	server.sendContent(F("    batEl.style.width = Math.max(10, Math.min(100, (level-critical)/(full-critical)*100)) + '%';"));
	server.sendContent(F("  "));
	server.sendContent(F("    batEl.style.backgroundColor = 'forestgreen';"));
	server.sendContent(F("    if(level <= middle) batEl.style.backgroundColor = '#F4AF00';"));
	server.sendContent(F("    if(level <= empty) batEl.style.backgroundColor = '#cc0000';"));
	server.sendContent(F("    if(level <= critical) batEl.style.backgroundColor = 'red';"));
	server.sendContent(F("\n"));
	server.sendContent(F("  } catch (error) {"));
	server.sendContent(F("    batEl.style.width = '50%';"));
	server.sendContent(F("    batEl.style.backgroundColor = 'blue';"));
	server.sendContent(F("  }"));
	server.sendContent(F("}"));
	server.sendContent(F("\n"));
	server.sendContent(F("function updateCameraState() {"));
	server.sendContent(F("  var inner = \"&#128247; ?\";"));
	server.sendContent(F("  "));
	server.sendContent(F("  var state = streamData ? streamData['state']['camera'].toLowerCase() : '';"));
	server.sendContent(F("  "));
	server.sendContent(F("  switch(state) {"));
	server.sendContent(F("    case \"photo\": "));
	server.sendContent(F("      inner = \"&#128248; Shoot\";"));
	server.sendContent(F("      break;"));
	server.sendContent(F("\n"));
	server.sendContent(F("    case \"idle\": "));
	server.sendContent(F("      inner = \"&#128247;\";"));
	server.sendContent(F("      break;"));
	server.sendContent(F("      "));
	server.sendContent(F("    case \"prepare\": "));
	server.sendContent(F("      inner = \"&#128247; Prepare\";"));
	server.sendContent(F("      break;"));
	server.sendContent(F("      "));
	server.sendContent(F("    case \"rest\": "));
	server.sendContent(F("      inner = \"&#128247; Rest\";"));
	server.sendContent(F("      break;"));
	server.sendContent(F("      "));
	server.sendContent(F("    case \"?\": "));
	server.sendContent(F("      inner = \"&#128247; ?! :0\";"));
	server.sendContent(F("      break;"));
	server.sendContent(F("  }"));
	server.sendContent(F("\n"));
	server.sendContent(F("  let el = document.getElementById(\"camera-state\");"));
	server.sendContent(F("  if(el) el.innerHTML = inner;"));
	server.sendContent(F("}"));
	server.sendContent(F("\n"));
	server.sendContent(F("var heartBeatCount = 0;"));
	server.sendContent(F("function heartBeat() {"));
	server.sendContent(F("  heartBeatCount = 6;"));
	server.sendContent(F("  setConnection(true);"));
	server.sendContent(F("  setInnerConnection(true);"));
	server.sendContent(F("}"));
	server.sendContent(F("\n"));
	server.sendContent(F("function setConnection(visible) {"));
	server.sendContent(F("  try {"));
	server.sendContent(F("    document.querySelector('#connection').style.display = visible ? \"unset\" : \"none\";"));
	server.sendContent(F("  } catch (error) { }"));
	server.sendContent(F("}"));
	server.sendContent(F("\n"));
	server.sendContent(F("function setInnerConnection(antenne) {"));
	server.sendContent(F("  try {"));
	server.sendContent(F("    document.querySelector('#connection').innerHTML = antenne ? \"&#128225;\" : \"&#10060;\";"));
	server.sendContent(F("  } catch (error) { }"));
	server.sendContent(F("}"));
	server.sendContent(F("\n"));
	server.sendContent(F("function updatePowerState(slideState, panState) {"));
	server.sendContent(F("  mapState = (state) => (state.toLowerCase() == \"yes\") ? \"&#128164;\" : \"&#128170;\";"));
	server.sendContent(F("  slideState = mapState(slideState);"));
	server.sendContent(F("  panState = mapState(panState);"));
	server.sendContent(F("\n"));
	server.sendContent(F("  document.getElementById(\"power-state\").innerHTML = slideState + ' / ' + panState;"));
	server.sendContent(F("}"));
	server.sendContent(F("\n"));
	server.sendContent(F("setInterval(function() {"));
	server.sendContent(F("  updateCameraState()"));
	server.sendContent(F("\n"));
	server.sendContent(F("  heartBeatCount--;"));
	server.sendContent(F("  if(heartBeatCount<=0) {"));
	server.sendContent(F("    streamData = null;"));
	server.sendContent(F("\n"));
	server.sendContent(F("    if(heartBeatCount >= -10) {"));
	server.sendContent(F("      setConnection(heartBeatCount % 2);"));
	server.sendContent(F("    "));
	server.sendContent(F("      dotString = '...'.substr(0, Math.abs(heartBeatCount % 4));"));
	server.sendContent(F("      updateGUIValue('insertSTATE', 'Wait for Slider' + dotString);"));
	server.sendContent(F("      updateGUIValue('insertSTATEDETAIL', 'Maybe we lost the connection :0');"));
	server.sendContent(F("    }"));
	server.sendContent(F("    else {"));
	server.sendContent(F("      setInnerConnection(false);"));
	server.sendContent(F("      setConnection(true);"));
	server.sendContent(F("      updateGUIValue('insertSTATE', 'No Connection!');"));
	server.sendContent(F("      updateGUIValue('insertSTATEDETAIL', 'Please try to reconnect.');"));
	server.sendContent(F("    }"));
	server.sendContent(F("  }"));
	server.sendContent(F("}, 500);"));
	server.sendContent(F("\n"));
	server.sendContent(F("\n"));
	server.sendContent(F("var updateTimeRequest = new XMLHttpRequest();"));
	server.sendContent(F("updateTimeRequest.open(\"GET\", \"../device/command/?set_time=\" + getDaytimeInSeconds());"));
	server.sendContent(F("updateTimeRequest.send();"));
}

void MilkywayAppPageHandler(ESP8266WebServer& server) {
	server.sendContent(F("<!DOCTYPE html>"));
	server.sendContent(F("<html lang='en'>"));
	server.sendContent(F("<head>"));
	server.sendContent(F("  <meta charset='UTF-8'>"));
	server.sendContent(F("  <meta name='viewport' content='width=device-width, initial-scale=1.0'>"));
	server.sendContent(F("  <title>Milkyway</title>"));
	server.sendContent(F("\n"));
	server.sendContent(F("  <link rel='stylesheet' href='definesCss.css'>"));
	server.sendContent(F("  <link rel='stylesheet' href='mainCss.css'>"));
	server.sendContent(F("  <link rel='stylesheet' href='mainCss2.css'>"));
	server.sendContent(F("\n"));
	server.sendContent(F("  <script src='mainJs.js'></script>"));
	server.sendContent(F("</head>"));
	server.sendContent(F("<body>"));
	server.sendContent(F("  <div class='content'>"));
	server.sendContent(F("    <div class='vspace'></div>"));
	server.sendContent(F("    <h1>&#127775; Milkyway</h1>"));
	server.sendContent(F("    <div class='option-container'>"));
	server.sendContent(F("      "));
	server.sendContent(F("      <p>Photos:</p>"));
	server.sendContent(F("      <input value='"));
	server.sendContent( String(getTimelapsePictureCount()) );
	server.sendContent(F("' type='number' min='0' max='5000' id='count'>"));
	server.sendContent(F("      <p class='small'>#</p>"));
	server.sendContent(F("\n"));
	server.sendContent(F("      <p>Slide:</p>"));
	server.sendContent(F("      <input value='"));
	server.sendContent( String(getTimelapseSlideSteps()) );
	server.sendContent(F("' type='number' step='0.001' min='-5000' max='5000' id='slide'>"));
	server.sendContent(F("      <p class='small'>mm / Step</p>"));
	server.sendContent(F("\n"));
	server.sendContent(F("      <p>Photo interval:</p>"));
	server.sendContent(F("      <input value='"));
	server.sendContent( String(getIOBoard()->getCameraExposureTime()) );
	server.sendContent(F("' type='number' step='0.1' min='0' max='500' id='photo'>"));
	server.sendContent(F("      <p class='small'>s / Photo</p>"));
	server.sendContent(F("\n"));
	server.sendContent(F("      <p>Step time:</p>"));
	server.sendContent(F("      <input value='"));
	server.sendContent( String(getTimelapseInterval()) );
	server.sendContent(F("' type='number' min='0' max='500' id='interval'>"));
	server.sendContent(F("      <p class='small'>s / Step</p>"));
	server.sendContent(F("    </div>"));
	server.sendContent(F("\n"));
	server.sendContent(F("    <div class='button main'"));
	server.sendContent(F("      onclick='makeRequest(\"timelapse_slide=\" + document.getElementById(\"slide\").value + \"&timelapse_count=\" + document.getElementById(\"count\").value + \"&timelapse_photo=\" + document.getElementById(\"photo\").value + \"&timelapse_interval=\" + document.getElementById(\"interval\").value + \"&timelapse_milkyway_settings=1\", true);'>"));
	server.sendContent(F("      &#129517; Update settings"));
	server.sendContent(F("    </div>"));
	server.sendContent(F("    <div class='side-container'>"));
	server.sendContent(F("      <div class='button main'"));
	server.sendContent(F("        onclick='makeRequest(\"timelapse_slide=\" + document.getElementById(\"slide\").value + \"&timelapse_count=\" + document.getElementById(\"count\").value + \"&timelapse_photo=\" + document.getElementById(\"photo\").value + \"&timelapse_interval=\" + document.getElementById(\"interval\").value + \"&timelapse_milkyway_settings=1&timelapse_start\");'>"));
	server.sendContent(F("        &#128640; Start Timelapse"));
	server.sendContent(F("      </div>"));
	server.sendContent(F("      <div class='button main' onclick='makeRequest(\"timelapse_stop\");'>&#10060;</div>"));
	server.sendContent(F("      <div class='button main'"));
	server.sendContent(F("        onclick='makeRequest(\"timelapse_slide=\" + document.getElementById(\"slide\").value + \"&timelapse_count=\" + document.getElementById(\"count\").value + \"&timelapse_photo=\" + document.getElementById(\"photo\").value + \"&timelapse_interval=\" + document.getElementById(\"interval\").value + \"&timelapse_milkyway_settings=1&timelapse_preview_start\");'>"));
	server.sendContent(F("        &#129488; Preview"));
	server.sendContent(F("      </div>"));
	server.sendContent(F("      <div class='button main' onclick='makeRequest(\"timelapse_preview_stop\");'>&#10060;</div>"));
	server.sendContent(F("    </div>"));
	server.sendContent(F("\n"));
	server.sendContent(F("    <br><br>"));
	server.sendContent(F("    <h1>&#127916; Info</h1>"));
	server.sendContent(F("\n"));
	server.sendContent(F("    <br>"));
	server.sendContent(F("    "));
	server.sendContent(F("    <div class='side-container-half'>"));
	server.sendContent(F("\n"));
	server.sendContent(F("      <p>Resulting Pan:</p>"));
	server.sendContent(F("      <p><i>"));
	server.sendContent( String(getTimelapsePanSteps()) );
	server.sendContent(F("</i> "));
	server.sendContent( (getPanStepper()->getPhysicalValueUnit()) );
	server.sendContent(F(" / Step</p>"));
	server.sendContent(F("\n"));
	server.sendContent(F("      <p>Hemisphere:</p>"));
	server.sendContent(F("      <p><a href='#' onclick='makeRequest(\"timelapse_set_hemisphere="));
	server.sendContent( String(!isTimelapseInNortherHemisphere() ? 1 : 0) );
	server.sendContent(F("\", true);'>"));
	server.sendContent( String(isTimelapseInNortherHemisphere() ? "Northern" : "South") );
	server.sendContent(F("</a></p>"));
	server.sendContent(F("\n"));
	server.sendContent(F("      <p></p><p></p>"));
	server.sendContent(F("\n"));
	server.sendContent(F("      <p>Total time:</p>"));
	server.sendContent(F("      <p><i>"));
	server.sendContent( secondsToString(getTimelapseTotalTime()) );
	server.sendContent(F("</i></p>"));
	server.sendContent(F("\n"));
	server.sendContent(F("      <p>End time:</p>"));
	server.sendContent(F("      <p><i>"));
	server.sendContent( secondsToTimeString(getTimelapseEndTime()) );
	server.sendContent(F("</i></p>"));
	server.sendContent(F("\n"));
	server.sendContent(F("      <p></p><p></p>"));
	server.sendContent(F("\n"));
	server.sendContent(F("      <p>Total Slide:</p>"));
	server.sendContent(F("      <p><i>"));
	server.sendContent( String(getTimelapseTotalSlideDistance()) );
	server.sendContent(F("</i> "));
	server.sendContent( (getSlideStepper()->getPhysicalValueUnit()) );
	server.sendContent(F("</p>"));
	server.sendContent(F("\n"));
	server.sendContent(F("      <p>Total Pan:</p>"));
	server.sendContent(F("      <p><i>"));
	server.sendContent( String(getTimelapseTotalPanDistance()) );
	server.sendContent(F("</i> "));
	server.sendContent( (getPanStepper()->getPhysicalValueUnit()) );
	server.sendContent(F("</p>     "));
	server.sendContent(F("      "));
	server.sendContent(F("      <p></p><p></p>"));
	server.sendContent(F("\n"));
	server.sendContent(F("      <p>Video (24fps):</p>"));
	server.sendContent(F("      <p><i>"));
	server.sendContent( secondsToString(getTimelapseVideoTimePrediction(24)) );
	server.sendContent(F("</i></p>"));
	server.sendContent(F("\n"));
	server.sendContent(F("      <p>Video (25fps):</p>"));
	server.sendContent(F("      <p><i>"));
	server.sendContent( secondsToString(getTimelapseVideoTimePrediction(25)) );
	server.sendContent(F("</i></p>"));
	server.sendContent(F("\n"));
	server.sendContent(F("      <p>Video (30fps):</p>"));
	server.sendContent(F("      <p><i>"));
	server.sendContent( secondsToString(getTimelapseVideoTimePrediction(30)) );
	server.sendContent(F("</i></p>"));
	server.sendContent(F("      "));
	server.sendContent(F("      <p>Video (60fps):</p>"));
	server.sendContent(F("      <p><i>"));
	server.sendContent( secondsToString(getTimelapseVideoTimePrediction(60)) );
	server.sendContent(F("</i></p>"));
	server.sendContent(F("    </div>"));
	server.sendContent(F("\n"));
	server.sendContent(F("    <div class='closer'></div>"));
	server.sendContent(F("  </div>"));
	server.sendContent(F("</body>"));
	server.sendContent(F("</html>"));
}

void IndexAppPageHandler(ESP8266WebServer& server) {
	server.sendContent(F("<!DOCTYPE html>"));
	server.sendContent(F("<html lang='en'>"));
	server.sendContent(F("<head style='overflow: hidden;'>"));
	server.sendContent(F("  <meta charset='UTF-8'>"));
	server.sendContent(F("  <meta name='viewport' content='width=device-width, initial-scale=1.0'>"));
	server.sendContent(F("  <title>Slide and Pan</title>"));
	server.sendContent(F("\n"));
	server.sendContent(F("  <link rel='stylesheet' href='definesCss.css'>"));
	server.sendContent(F("  <link rel='stylesheet' href='mainCss.css'>"));
	server.sendContent(F("  <link rel='stylesheet' href='mainCss2.css'>"));
	server.sendContent(F("\n"));
	server.sendContent(F("  <script src='mainJs.js'></script>"));
	server.sendContent(F("</head>"));
	server.sendContent(F("<body style='overflow: hidden;'>"));
	server.sendContent(F("  <div id='status-bar'>"));
	server.sendContent(F("    <div id='battery'>"));
	server.sendContent(F("      <div id='battery-plus-pole'></div>"));
	server.sendContent(F("      <div id='battery-fill'></div>"));
	server.sendContent(F("      <div id='battery-glas'></div>"));
	server.sendContent(F("    </div>"));
	server.sendContent(F("\n"));
	server.sendContent(F("    <div class='status left'>"));
	server.sendContent(F("      &#128678; <span class='insertSTATE' id='status' onclick='document.getElementById(\"status-bar-detail\").classList.toggle(\"open\");'></span>"));
	server.sendContent(F("    </div>"));
	server.sendContent(F("\n"));
	server.sendContent(F("    <div id='e-stop' onclick='makeRequest(\"slide_stop&pan_stop&timelapse_stop\");'>"));
	server.sendContent(F("      <p>E-STOP</p>"));
	server.sendContent(F("    </div>"));
	server.sendContent(F("\n"));
	server.sendContent(F("    <div class='status right'>"));
	server.sendContent(F("      <p>"));
	server.sendContent(F("        <span id='connection'>&#128225;</span>"));
	server.sendContent(F("        <span id='power-state'>. / ..</span> "));
	server.sendContent(F("        <span id='camera-state'>&#128247;</span>"));
	server.sendContent(F("      </p>"));
	server.sendContent(F("    </div>"));
	server.sendContent(F("  </div>"));
	server.sendContent(F("\n"));
	server.sendContent(F("  <div id='status-bar-detail'>"));
	server.sendContent(F("    <h1 class='insertSTATE'></h1>"));
	server.sendContent(F("    <p class='insertSTATEDETAIL'></p>"));
	server.sendContent(F("    <br><br>"));
	server.sendContent(F("    <hr>"));
	server.sendContent(F("    <br>"));
	server.sendContent(F("    <p style='text-align: center; font-size: 2em;'>"));
	server.sendContent(F("      <span class='insertSLIDEPOS'>?</span>"));
	server.sendContent( (getSlideStepper()->getPhysicalValueUnit()) );
	server.sendContent(F(" / "));
	server.sendContent(F("      <span class='insertPANPOS'>?</span>"));
	server.sendContent( (getPanStepper()->getPhysicalValueUnit()) );
	server.sendContent(F("\n"));
	server.sendContent(F("    </p>"));
	server.sendContent(F("    <br>"));
	server.sendContent(F("    <div class='side-container'>"));
	server.sendContent(F("      <div class='button main' onclick='makeRequest(\"slide_reset&pan_reset\");'>&#127919; Set as Home</div>"));
	server.sendContent(F("      <div class='button main' onclick='makeRequest(\"pan_physical_value=0&slide_physical_value=0\");'>&#127969;</div>"));
	server.sendContent(F("      <div class='button main' onclick='makeRequest(\"slide_sleep=1&pan_sleep=1\");'>&#9889; Stepper power On</div>"));
	server.sendContent(F("      <div class='button main' onclick='makeRequest(\"slide_sleep=0&pan_sleep=0\");'>OFF</div>"));
	server.sendContent(F("      <div></div><div></div>"));
	server.sendContent(F("      <div class='button main' onclick='makeRequest(\"slide_lazy=0\");'>&#128170; Set Slide strong</div>"));
	server.sendContent(F("      <div class='button main' onclick='makeRequest(\"slide_lazy=1\");'>Lazy</div>"));
	server.sendContent(F("      <div class='button main' onclick='makeRequest(\"pan_lazy=0\");'>&#128170; Set Pan strong</div>"));
	server.sendContent(F("      <div class='button main' onclick='makeRequest(\"pan_lazy=1\");'>Lazy</div>"));
	server.sendContent(F("    </div>"));
	server.sendContent(F("    <br><br>"));
	server.sendContent(F("    <hr>"));
	server.sendContent(F("    <br><br>"));
	server.sendContent(F("    <div class='section'>"));
	server.sendContent(F("      <h3>Slide to:</h3>"));
	server.sendContent(F("      <div class='side-container'>"));
	server.sendContent(F("        <input type='number' value='"));
	server.sendContent( (getSlideStepper()->getPhysicalValueInfo()) );
	server.sendContent(F("' step='0.001' min='-50000' max='50000' id='slide_pv'>"));
	server.sendContent(F("        <div class='button main' onclick='makeRequest(\"slide_physical_value=\" + document.getElementById(\"slide_pv\").value);'>&#128681;</div>"));
	server.sendContent(F("      </div>"));
	server.sendContent(F("      <br>"));
	server.sendContent(F("      <h3>Pan to:</h3>"));
	server.sendContent(F("      <div class='side-container'>"));
	server.sendContent(F("        <input type='number' value='"));
	server.sendContent( (getPanStepper()->getPhysicalValueInfo()) );
	server.sendContent(F("' step='0.001' min='-50000' max='50000' id='pan_pv'>"));
	server.sendContent(F("        <div class='button main' onclick='makeRequest(\"pan_physical_value=\" + document.getElementById(\"pan_pv\").value);'>&#128681;</div>"));
	server.sendContent(F("      </div>"));
	server.sendContent(F("      <br>"));
	server.sendContent(F("      <h3>Trigger photo:</h3>"));
	server.sendContent(F("      <div class='side-container'>"));
	server.sendContent(F("        <input type='number' value='"));
	server.sendContent( String(getIOBoard()->getCameraExposureTime()) );
	server.sendContent(F("' step='0.01' min='0.01' max='50000' id='g_exp'>"));
	server.sendContent(F("        <div class='button main' onclick='makeRequest(\"photo_set_exp=\" + document.getElementById(\"g_exp\").value + \"&photo_trigger=1\");'>&#128248;</div>"));
	server.sendContent(F("      </div>"));
	server.sendContent(F("    </div>"));
	server.sendContent(F("    "));
	server.sendContent(F("    <div class='closer'></div>"));
	server.sendContent(F("  </div>"));
	server.sendContent(F("\n"));
	server.sendContent(F("  <div id='select' class='select wheel'>"));
	server.sendContent(F("    <div class='select option option1' onclick='select(1);'><p>&#127918;</p></div>"));
	server.sendContent(F("    <div class='select option option2' onclick='select(2);'><p>&#9202;</p></div>"));
	server.sendContent(F("    <div class='select option option3' onclick='select(3);'><p>&#127775;</p></div>"));
	server.sendContent(F("    <div class='select option option4' onclick='select(4);'><p>&#128301;</p></div>"));
	server.sendContent(F("    <div class='select option option5' onclick='select(5);'><p>&#128203;</p></div>"));
	server.sendContent(F("    <div class='select option option6' onclick='select(6);'><p>&#128209;</p></div>"));
	server.sendContent(F("  </div>"));
	server.sendContent(F("\n"));
	server.sendContent(F("\n"));
	server.sendContent(F("  <iframe id='iframe' src='' frameBorder='0'></iframe>"));
	server.sendContent(F("  <script>select(2); startStreamListener();</script>"));
	server.sendContent(F("</body>"));
	server.sendContent(F("</html>"));
}

void TimelapseAppPageHandler(ESP8266WebServer& server) {
	server.sendContent(F("<!DOCTYPE html>"));
	server.sendContent(F("<html lang='en'>"));
	server.sendContent(F("<head>"));
	server.sendContent(F("  <meta charset='UTF-8'>"));
	server.sendContent(F("  <meta name='viewport' content='width=device-width, initial-scale=1.0'>"));
	server.sendContent(F("  <title>Timelapse</title>"));
	server.sendContent(F("\n"));
	server.sendContent(F("  <link rel='stylesheet' href='definesCss.css'>"));
	server.sendContent(F("  <link rel='stylesheet' href='mainCss.css'>"));
	server.sendContent(F("  <link rel='stylesheet' href='mainCss2.css'>"));
	server.sendContent(F("\n"));
	server.sendContent(F("  <script src='mainJs.js'></script>"));
	server.sendContent(F("</head>"));
	server.sendContent(F("<body>"));
	server.sendContent(F("  <div class='content'>"));
	server.sendContent(F("    <div class='vspace'></div>"));
	server.sendContent(F("    <h1>&#9202; Timelapse</h1>"));
	server.sendContent(F("    <div class='option-container'>"));
	server.sendContent(F("      "));
	server.sendContent(F("      <p>Photos:</p>"));
	server.sendContent(F("      <input value='"));
	server.sendContent( String(getTimelapsePictureCount()) );
	server.sendContent(F("' type='number' min='0' max='5000' id='count'>"));
	server.sendContent(F("      <p class='small'>#</p>"));
	server.sendContent(F("\n"));
	server.sendContent(F("      <p>Slide:</p>"));
	server.sendContent(F("      <input value='"));
	server.sendContent( String(getTimelapseSlideSteps()) );
	server.sendContent(F("' type='number' step='0.001' min='-5000' max='5000' id='slide'>"));
	server.sendContent(F("      <p class='small'>mm / Step</p>"));
	server.sendContent(F("\n"));
	server.sendContent(F("      <p>Pan:</p>"));
	server.sendContent(F("      <input value='"));
	server.sendContent( String(getTimelapsePanSteps()) );
	server.sendContent(F("' type='number' step='0.001' min='-5000' max='5000' id='pan'>"));
	server.sendContent(F("      <p class='small'>° / Step</p>"));
	server.sendContent(F("\n"));
	server.sendContent(F("      <p>Photo interval:</p>"));
	server.sendContent(F("      <input value='"));
	server.sendContent( String(getIOBoard()->getCameraExposureTime()) );
	server.sendContent(F("' type='number' step='0.1' min='0' max='500' id='photo'>"));
	server.sendContent(F("      <p class='small'>s / Photo</p>"));
	server.sendContent(F("\n"));
	server.sendContent(F("      <p>Step time:</p>"));
	server.sendContent(F("      <input value='"));
	server.sendContent( String(getTimelapseInterval()) );
	server.sendContent(F("' type='number' min='0' max='500' id='interval'>"));
	server.sendContent(F("      <p class='small'>s / Step</p>"));
	server.sendContent(F("    </div>"));
	server.sendContent(F("\n"));
	server.sendContent(F("    <div class='button main'"));
	server.sendContent(F("      onclick='makeRequest(\"timelapse_slide=\" + document.getElementById(\"slide\").value + \"&timelapse_count=\" + document.getElementById(\"count\").value + \"&timelapse_photo=\" + document.getElementById(\"photo\").value + \"&timelapse_interval=\" + document.getElementById(\"interval\").value + \"&timelapse_pan=\" + document.getElementById(\"pan\").value, true);'>"));
	server.sendContent(F("      &#129517; Update settings"));
	server.sendContent(F("    </div>"));
	server.sendContent(F("    <div class='side-container'>"));
	server.sendContent(F("      <div class='button main'"));
	server.sendContent(F("        onclick='makeRequest(\"timelapse_slide=\" + document.getElementById(\"slide\").value + \"&timelapse_count=\" + document.getElementById(\"count\").value + \"&timelapse_photo=\" + document.getElementById(\"photo\").value + \"&timelapse_interval=\" + document.getElementById(\"interval\").value + \"&timelapse_pan=\" + document.getElementById(\"pan\").value + \"&timelapse_start\");'>"));
	server.sendContent(F("        &#128640; Start Timelapse"));
	server.sendContent(F("      </div>"));
	server.sendContent(F("      <div class='button main' onclick='makeRequest(\"timelapse_stop\");'>&#10060;</div>"));
	server.sendContent(F("      <div class='button main'"));
	server.sendContent(F("        onclick='makeRequest(\"timelapse_slide=\" + document.getElementById(\"slide\").value + \"&timelapse_count=\" + document.getElementById(\"count\").value + \"&timelapse_photo=\" + document.getElementById(\"photo\").value + \"&timelapse_interval=\" + document.getElementById(\"interval\").value + \"&timelapse_pan=\" + document.getElementById(\"pan\").value + \"&timelapse_preview_start\");'>"));
	server.sendContent(F("        &#129488; Preview"));
	server.sendContent(F("      </div>"));
	server.sendContent(F("      <div class='button main' onclick='makeRequest(\"timelapse_preview_stop\");'>&#10060;</div>"));
	server.sendContent(F("    </div>"));
	server.sendContent(F("\n"));
	server.sendContent(F("    <br><br>"));
	server.sendContent(F("    <h1>&#127916; Info</h1>"));
	server.sendContent(F("\n"));
	server.sendContent(F("    <br>"));
	server.sendContent(F("\n"));
	server.sendContent(F("    <div class='side-container-half'>"));
	server.sendContent(F("\n"));
	server.sendContent(F("      <p>Total time:</p>"));
	server.sendContent(F("      <p><i>"));
	server.sendContent( secondsToString(getTimelapseTotalTime()) );
	server.sendContent(F("</i></p>"));
	server.sendContent(F("\n"));
	server.sendContent(F("      <p>End time:</p>"));
	server.sendContent(F("      <p><i>"));
	server.sendContent( secondsToTimeString(getTimelapseEndTime()) );
	server.sendContent(F("</i></p>"));
	server.sendContent(F("\n"));
	server.sendContent(F("      <p></p><p></p>"));
	server.sendContent(F("\n"));
	server.sendContent(F("      <p>Total Slide:</p>"));
	server.sendContent(F("      <p><i>"));
	server.sendContent( String(getTimelapseTotalSlideDistance()) );
	server.sendContent(F("</i> "));
	server.sendContent( (getSlideStepper()->getPhysicalValueUnit()) );
	server.sendContent(F("</p>"));
	server.sendContent(F("\n"));
	server.sendContent(F("      <p>Total Pan:</p>"));
	server.sendContent(F("      <p><i>"));
	server.sendContent( String(getTimelapseTotalPanDistance()) );
	server.sendContent(F("</i> "));
	server.sendContent( (getPanStepper()->getPhysicalValueUnit()) );
	server.sendContent(F("</p>      "));
	server.sendContent(F("      "));
	server.sendContent(F("      <p></p><p></p>"));
	server.sendContent(F("\n"));
	server.sendContent(F("      <p>Video (24fps):</p>"));
	server.sendContent(F("      <p><i>"));
	server.sendContent( secondsToString(getTimelapseVideoTimePrediction(24)) );
	server.sendContent(F("</i></p>"));
	server.sendContent(F("\n"));
	server.sendContent(F("      <p>Video (25fps):</p>"));
	server.sendContent(F("      <p><i>"));
	server.sendContent( secondsToString(getTimelapseVideoTimePrediction(25)) );
	server.sendContent(F("</i></p>"));
	server.sendContent(F("\n"));
	server.sendContent(F("      <p>Video (30fps):</p>"));
	server.sendContent(F("      <p><i>"));
	server.sendContent( secondsToString(getTimelapseVideoTimePrediction(30)) );
	server.sendContent(F("</i></p>"));
	server.sendContent(F("\n"));
	server.sendContent(F("      <p>Video (60fps):</p>"));
	server.sendContent(F("      <p><i>"));
	server.sendContent( secondsToString(getTimelapseVideoTimePrediction(60)) );
	server.sendContent(F("</i></p>"));
	server.sendContent(F("    </div>"));
	server.sendContent(F("\n"));
	server.sendContent(F("    <div class='closer'></div>"));
	server.sendContent(F("  </div>"));
	server.sendContent(F("</body>"));
	server.sendContent(F("</html>"));
}

void Maincss2AppPageHandler(ESP8266WebServer& server) {
	server.sendContent(F(".select.wheel.option1 {"));
	server.sendContent(F("  transform: translate(-50%, var(--select-top-pos)) rotate(20deg);"));
	server.sendContent(F("}"));
	server.sendContent(F("\n"));
	server.sendContent(F(".select.wheel.option2 {"));
	server.sendContent(F("  transform: translate(-50%, var(--select-top-pos)) rotate(0deg);"));
	server.sendContent(F("}"));
	server.sendContent(F("\n"));
	server.sendContent(F(".select.wheel.option3 {"));
	server.sendContent(F("  transform: translate(-50%, var(--select-top-pos)) rotate(-20deg);"));
	server.sendContent(F("}"));
	server.sendContent(F("\n"));
	server.sendContent(F(".select.wheel.option4 {"));
	server.sendContent(F("  transform: translate(-50%, var(--select-top-pos)) rotate(-40deg);"));
	server.sendContent(F("}"));
	server.sendContent(F("\n"));
	server.sendContent(F(".select.wheel.option5 {"));
	server.sendContent(F("  transform: translate(-50%, var(--select-top-pos)) rotate(-60deg);"));
	server.sendContent(F("}"));
	server.sendContent(F("\n"));
	server.sendContent(F("\n"));
	server.sendContent(F(".select.wheel.option6 {"));
	server.sendContent(F("  transform: translate(-50%, var(--select-top-pos)) rotate(-80deg);"));
	server.sendContent(F("}"));
	server.sendContent(F("\n"));
	server.sendContent(F(".select.option {"));
	server.sendContent(F("  width: 200vw;"));
	server.sendContent(F("  height: 200vw;"));
	server.sendContent(F("  min-width: 500px;"));
	server.sendContent(F("  min-height: 500px;"));
	server.sendContent(F("  max-width: 960px;"));
	server.sendContent(F("  max-height: 960px;"));
	server.sendContent(F("  "));
	server.sendContent(F("  color: var(--color-front1);"));
	server.sendContent(F("  font-size: 2em;"));
	server.sendContent(F("\n"));
	server.sendContent(F("  background-color: transparent;"));
	server.sendContent(F("  border: none;"));
	server.sendContent(F("  position: fixed;"));
	server.sendContent(F("\n"));
	server.sendContent(F("  text-align: center;"));
	server.sendContent(F("  padding-top: 10px;"));
	server.sendContent(F("\n"));
	server.sendContent(F("  pointer-events: none;"));
	server.sendContent(F("}"));
	server.sendContent(F("\n"));
	server.sendContent(F(".select.option p {"));
	server.sendContent(F("  pointer-events: all;"));
	server.sendContent(F("  cursor: pointer;"));
	server.sendContent(F("  display: inline-block;"));
	server.sendContent(F("  padding: 5px;"));
	server.sendContent(F("}"));
	server.sendContent(F("\n"));
	server.sendContent(F(".select.option p:hover {"));
	server.sendContent(F("  color: var(--color-front2);"));
	server.sendContent(F("}"));
	server.sendContent(F("\n"));
	server.sendContent(F(".select.option.option1 {"));
	server.sendContent(F("  transform: rotate(-20deg);"));
	server.sendContent(F("  z-index: 20;"));
	server.sendContent(F("}"));
	server.sendContent(F("\n"));
	server.sendContent(F(".select.option.option2 {"));
	server.sendContent(F("  transform: rotate(0deg);"));
	server.sendContent(F("  z-index: 21;"));
	server.sendContent(F("}"));
	server.sendContent(F("\n"));
	server.sendContent(F(".select.option.option3 {"));
	server.sendContent(F("  transform: rotate(20deg);"));
	server.sendContent(F("  z-index: 22;"));
	server.sendContent(F("}"));
	server.sendContent(F("\n"));
	server.sendContent(F(".select.option.option4 {"));
	server.sendContent(F("  transform: rotate(40deg);"));
	server.sendContent(F("  z-index: 22;"));
	server.sendContent(F("}"));
	server.sendContent(F("\n"));
	server.sendContent(F(".select.option.option5 {"));
	server.sendContent(F("  transform: rotate(60deg);"));
	server.sendContent(F("  z-index: 22;"));
	server.sendContent(F("}"));
	server.sendContent(F("\n"));
	server.sendContent(F(".select.option.option6 {"));
	server.sendContent(F("  transform: rotate(80deg);"));
	server.sendContent(F("  z-index: 22;"));
	server.sendContent(F("}"));
	server.sendContent(F("\n"));
	server.sendContent(F("iframe {"));
	server.sendContent(F("  position: absolute;"));
	server.sendContent(F("  top: 0;"));
	server.sendContent(F("  left: 0;"));
	server.sendContent(F("  width: 100%;"));
	server.sendContent(F("  height: 100%;"));
	server.sendContent(F("  z-index: 1;"));
	server.sendContent(F("  margin-top: 30px;"));
	server.sendContent(F("}"));
	server.sendContent(F("\n"));
	server.sendContent(F(".control-container {"));
	server.sendContent(F("  display: grid;"));
	server.sendContent(F("  grid-template-columns: 1fr 1fr 1fr;"));
	server.sendContent(F("  grid-template-rows: 1fr 1fr 1fr;"));
	server.sendContent(F("  gap: 10px 10px;"));
	server.sendContent(F("\n"));
	server.sendContent(F("  width: 80%;"));
	server.sendContent(F("  margin: 50px auto;"));
	server.sendContent(F("}"));
	server.sendContent(F("\n"));
	server.sendContent(F(".option-container {"));
	server.sendContent(F("  display: grid;"));
	server.sendContent(F("  grid-template-columns: 2fr 1fr 1fr;"));
	server.sendContent(F("  gap: 5px 10px;"));
	server.sendContent(F("\n"));
	server.sendContent(F("  width: 80%;"));
	server.sendContent(F("  margin: 50px auto;"));
	server.sendContent(F("}"));
	server.sendContent(F("\n"));
	server.sendContent(F(".button {"));
	server.sendContent(F("  display: inline-block;"));
	server.sendContent(F("  text-align: center;"));
	server.sendContent(F("  vertical-align: middle;"));
	server.sendContent(F("  width: 100%;"));
	server.sendContent(F("  height: 100%;"));
	server.sendContent(F("  font-size: 3em;"));
	server.sendContent(F("\n"));
	server.sendContent(F("  cursor: pointer;"));
	server.sendContent(F("\n"));
	server.sendContent(F("  border-radius: 10px;"));
	server.sendContent(F("  border: solid var(--color-background1) 2px;"));
	server.sendContent(F("\n"));
	server.sendContent(F("  transition: all .3s ease;"));
	server.sendContent(F("}"));
	server.sendContent(F("\n"));
	server.sendContent(F(".button:hover, .button:active {"));
	server.sendContent(F("  border: solid var(--color-front2) 2px;"));
	server.sendContent(F("  background-color: var(--color-background3);"));
	server.sendContent(F("  color: var(--color-front2);"));
	server.sendContent(F("}"));
	server.sendContent(F("\n"));
	server.sendContent(F(".button.stop {"));
	server.sendContent(F("  font-size: 1em;"));
	server.sendContent(F("}"));
	server.sendContent(F("\n"));
	server.sendContent(F(".button p {"));
	server.sendContent(F("  position: relative;"));
	server.sendContent(F("  top: 70%;"));
	server.sendContent(F("}"));
	server.sendContent(F("\n"));
	server.sendContent(F(".button.main {"));
	server.sendContent(F("  width: 80%;"));
	server.sendContent(F("  margin: 20px auto;"));
	server.sendContent(F("  display: block;"));
	server.sendContent(F("  font-size: 1.2em;"));
	server.sendContent(F("  padding: 5px 0;"));
	server.sendContent(F("}"));
	server.sendContent(F("\n"));
	server.sendContent(F("input {"));
	server.sendContent(F("  display: inline-block;"));
	server.sendContent(F("  text-align: center;"));
	server.sendContent(F("  margin: auto;"));
	server.sendContent(F("  width: 100%;"));
	server.sendContent(F("  color: red;"));
	server.sendContent(F("}"));
	server.sendContent(F("\n"));
	server.sendContent(F(".main-container {"));
	server.sendContent(F("  width: 80%;"));
	server.sendContent(F("  margin: 50px auto;"));
	server.sendContent(F("}"));
	server.sendContent(F("\n"));
	server.sendContent(F(".main-container h2 {"));
	server.sendContent(F("  text-align: center;"));
	server.sendContent(F("  margin-bottom: 10px;"));
	server.sendContent(F("}"));
	server.sendContent(F("\n"));
	server.sendContent(F(".side-container {"));
	server.sendContent(F("  display: grid;"));
	server.sendContent(F("  grid-template-columns: 4fr 1fr;"));
	server.sendContent(F("  gap: 20px 10px;"));
	server.sendContent(F("  width: 80%;"));
	server.sendContent(F("  height: auto;"));
	server.sendContent(F("  margin: auto;"));
	server.sendContent(F("}"));
	server.sendContent(F("\n"));
	server.sendContent(F(".side-container .button {"));
	server.sendContent(F("  margin: 0;"));
	server.sendContent(F("  width: 100%;"));
	server.sendContent(F("  display: inline-table"));
	server.sendContent(F("}"));
	server.sendContent(F("\n"));
	server.sendContent(F("\n"));
	server.sendContent(F(".side-container-half {"));
	server.sendContent(F("  display: grid;"));
	server.sendContent(F("  grid-template-columns: 1fr 1fr;"));
	server.sendContent(F("  gap: 20px 10px;"));
	server.sendContent(F("  width: 80%;"));
	server.sendContent(F("  height: auto;"));
	server.sendContent(F("  margin: auto;"));
	server.sendContent(F("}"));
	server.sendContent(F("\n"));
	server.sendContent(F(".small {"));
	server.sendContent(F("  font-size: .75em;"));
	server.sendContent(F("  margin-left: 20px;"));
	server.sendContent(F("}"));
	server.sendContent(F("\n"));
	server.sendContent(F(".closer {"));
	server.sendContent(F("  height: 200px;"));
	server.sendContent(F("}"));
	server.sendContent(F("\n"));
	server.sendContent(F(".section {"));
	server.sendContent(F("  text-align: text;"));
	server.sendContent(F("  width: 80%;"));
	server.sendContent(F("  margin: auto;"));
	server.sendContent(F("}"));
	server.sendContent(F("\n"));
	server.sendContent(F(".section h1, h2, h3 {"));
	server.sendContent(F("  text-align: center;"));
	server.sendContent(F("}"));
	server.sendContent(F("\n"));
	server.sendContent(F("input {"));
	server.sendContent(F("  text-align: left;"));
	server.sendContent(F("  color: var(--color-background1);"));
	server.sendContent(F("  background-color: var(--color-front1);"));
	server.sendContent(F("  padding: 5px 10px;"));
	server.sendContent(F("  "));
	server.sendContent(F("  border-radius: 10px;"));
	server.sendContent(F("  border: solid var(--color-background1) 2px;"));
	server.sendContent(F("  min-height: 25px;"));
	server.sendContent(F("  width: 80%;"));
	server.sendContent(F("}"));
}

void InfoAppPageHandler(ESP8266WebServer& server) {
	server.sendContent(F("<!DOCTYPE html>"));
	server.sendContent(F("<html lang='en'>"));
	server.sendContent(F("<head>"));
	server.sendContent(F("  <meta charset='UTF-8'>"));
	server.sendContent(F("  <meta name='viewport' content='width=device-width, initial-scale=1.0'>"));
	server.sendContent(F("  <title>Plan</title>"));
	server.sendContent(F("\n"));
	server.sendContent(F("  <link rel='stylesheet' href='definesCss.css'>"));
	server.sendContent(F("  <link rel='stylesheet' href='mainCss.css'>"));
	server.sendContent(F("  <link rel='stylesheet' href='mainCss2.css'>"));
	server.sendContent(F("\n"));
	server.sendContent(F("  <script src='mainJs.js'></script>"));
	server.sendContent(F("</head>"));
	server.sendContent(F("<body>"));
	server.sendContent(F("  <div class='content'>"));
	server.sendContent(F("    <div class='vspace'></div>"));
	server.sendContent(F("    <h1>&#128209; Info</h1>"));
	server.sendContent(F("    "));
	server.sendContent(F("    <br><br>"));
	server.sendContent(F("\n"));
	server.sendContent(F("    <div class='main-container'>"));
	server.sendContent(F("       "));
	server.sendContent(F("      <h2>&#128640; Slider</h2>"));
	server.sendContent(F("      <br>"));
	server.sendContent(F("      <div class='side-container-half'>"));
	server.sendContent(F("        <p>Name:</p><i>"));
	server.sendContent( String(SLIDEANDPAN_NAME) );
	server.sendContent(F("</i>"));
	server.sendContent(F("        <p>Version:</p><i>"));
	server.sendContent( String(SLIDEANDPAN_VERSION) );
	server.sendContent(F("</i>"));
	server.sendContent(F("        <p>Copyright:</p><i>"));
	server.sendContent( String(SLIDEANDPAN_COPYRIGHT) );
	server.sendContent(F("</i>"));
	server.sendContent(F("        <p>ID:</p><i>"));
	server.sendContent( String(SLIDEANDPAN_ID) );
	server.sendContent(F("</i>"));
	server.sendContent(F("      </div>"));
	server.sendContent(F("\n"));
	server.sendContent(F("      <br><br>"));
	server.sendContent(F("\n"));
	server.sendContent(F("      <h2>&#128199; Author</h2>"));
	server.sendContent(F("      <br>"));
	server.sendContent(F("      <p>"));
	server.sendContent(F("        My name is <i>Sebastian Knoll</i> and I am the inventor and author of this project. "));
	server.sendContent(F("        If you have any question regarding me or the app do not hesitate to "));
	server.sendContent(F("        <a target='_blank' href='https://sebastianknoll.net/me/contact.php'>contact me</a> or visit my "));
	server.sendContent(F("        <a target='_blank' href='https://sebastianknoll.net/'>homepage</a>. "));
	server.sendContent(F("        <br>"));
	server.sendContent(F("        <br>"));
	server.sendContent(F("        If you have any legal concerns, note that this is an private application "));
	server.sendContent(F("        which you can use at your own risk. Furthermore you can checkout "));
	server.sendContent(F("        <a target='_blank' href='https://sebastianknoll.net/gtc/'>legal stuff</a> and "));
	server.sendContent(F("        <a target='_blank' href='https://sebastianknoll.net/slide/gtc'>legal stuff for Slide and Pan</a>."));
	server.sendContent(F("      </p>"));
	server.sendContent(F("\n"));
	server.sendContent(F("      <br><br>"));
	server.sendContent(F("\n"));
	server.sendContent(F("      "));
	server.sendContent(F("      <h2>&#127759; More</h2>"));
	server.sendContent(F("      <br>"));
	server.sendContent(F("      <p>"));
	server.sendContent(F("        <p>"));
	server.sendContent(F("        Use the Hashtag <a target='_blank' href='https://www.instagram.com/explore/tags/slideandpan/'>#slideandpan</a> so that I can see your amazing work."));
	server.sendContent(F("        </p>"));
	server.sendContent(F("        <br>"));
	server.sendContent(F("        <p>Use the <a target='_blank' href='"));
	server.sendContent( String(SLIDEANDPAN_LINK_HANDBOOK) );
	server.sendContent(F("'>Handbook</a> for more information and tutorials.</p>"));
	server.sendContent(F("        <br>"));
	server.sendContent(F("        <p>Have a look at my work <a target='_blank' href='https://sebastianknoll.net/photo'>here</a>.</p>"));
	server.sendContent(F("        <br>"));
	server.sendContent(F("      </p>"));
	server.sendContent(F("\n"));
	server.sendContent(F("      <br><br>"));
	server.sendContent(F("\n"));
	server.sendContent(F("      <h2>&#9874; Hardware</h2>"));
	server.sendContent(F("      <h3 style='text-align: left;'>Slide</h3>"));
	server.sendContent(F("      <br>"));
	server.sendContent(F("      <div class='side-container-half'>"));
	server.sendContent(F("        <p>Direction Pin:</p><i>"));
	server.sendContent( String(SLIDE_STEPPER_PIN_DIRECTION) );
	server.sendContent(F("</i>"));
	server.sendContent(F("        <p>Step Pin:</p><i>"));
	server.sendContent( String(SLIDE_STEPPER_PIN_STEP) );
	server.sendContent(F("</i>"));
	server.sendContent(F("        <p>Sleep Pin:</p><i>"));
	server.sendContent( String(SLIDE_STEPPER_PIN_SLEEP) );
	server.sendContent(F("</i>"));
	server.sendContent(F("        <p>Steps / Turn:</p><i>"));
	server.sendContent( String(STEPPER_STEPS_PER_TURN) );
	server.sendContent(F("</i>"));
	server.sendContent(F("        <p>Can change res.:</p><i>"));
	server.sendContent( String(getSlideStepper()->hasChangeResolutionMethod() ? "Yes" : "No") );
	server.sendContent(F("</i>"));
	server.sendContent(F("        <p>Driver M1 Pin:</p><i>"));
	server.sendContent( String(SLIDE_STEPPER_DRIVER_M1) );
	server.sendContent(F("</i>"));
	server.sendContent(F("        <p>Driver M2 Pin:</p><i>"));
	server.sendContent( String(SLIDE_STEPPER_DRIVER_M2) );
	server.sendContent(F("</i>"));
	server.sendContent(F("        <p>Driver M3 Pin:</p><i>"));
	server.sendContent( String(SLIDE_STEPPER_DRIVER_M3) );
	server.sendContent(F("</i>"));
	server.sendContent(F("      </div>"));
	server.sendContent(F("\n"));
	server.sendContent(F("      <br>"));
	server.sendContent(F("\n"));
	server.sendContent(F("      <h3 style='text-align: left;'>Pan</h3>"));
	server.sendContent(F("      <br>"));
	server.sendContent(F("      <div class='side-container-half'>"));
	server.sendContent(F("        <p>Direction Pin:</p><i>"));
	server.sendContent( String(PAN_STEPPER_PIN_DIRECTION) );
	server.sendContent(F("</i>"));
	server.sendContent(F("        <p>Step Pin:</p><i>"));
	server.sendContent( String(PAN_STEPPER_PIN_STEP) );
	server.sendContent(F("</i>"));
	server.sendContent(F("        <p>Sleep Pin:</p><i>"));
	server.sendContent( String(PAN_STEPPER_PIN_SLEEP) );
	server.sendContent(F("</i>"));
	server.sendContent(F("        <p>Steps / Turn:</p><i>"));
	server.sendContent( String(STEPPER_STEPS_PER_TURN) );
	server.sendContent(F("</i>"));
	server.sendContent(F("        <p>Can change res.:</p><i>"));
	server.sendContent( String(getPanStepper()->hasChangeResolutionMethod() ? "Yes" : "No") );
	server.sendContent(F("</i>"));
	server.sendContent(F("        <p>Driver M1 Pin:</p><i>"));
	server.sendContent( String(PAN_STEPPER_DRIVER_M1) );
	server.sendContent(F("</i>"));
	server.sendContent(F("        <p>Driver M2 Pin:</p><i>"));
	server.sendContent( String(PAN_STEPPER_DRIVER_M2) );
	server.sendContent(F("</i>"));
	server.sendContent(F("        <p>Driver M3 Pin:</p><i>"));
	server.sendContent( String(PAN_STEPPER_DRIVER_M3) );
	server.sendContent(F("</i>"));
	server.sendContent(F("      </div>"));
	server.sendContent(F("      "));
	server.sendContent(F("      <br><br>"));
	server.sendContent(F("      <h2>&#128655; Constants</h2>"));
	server.sendContent(F("      <br>"));
	server.sendContent(F("      <div class='side-container-half'>"));
	server.sendContent(F("        <p>Gear diameter:</p> <i>"));
	server.sendContent( String(SLIDE_GEAR_DIAMETER) );
	server.sendContent(F("</i>"));
	server.sendContent(F("        <p>Gear cog number: </p><i>"));
	server.sendContent( String(PAN_GEAR_SMALL_COG_NUMBER) );
	server.sendContent(F("</i>"));
	server.sendContent(F("        <p>Big gear cog number: </p><i>"));
	server.sendContent( String(PAN_GEAR_LARGE_COG_NUMBER) );
	server.sendContent(F("</i>"));
	server.sendContent(F("        <p>Earth rotation: </p><i>"));
	server.sendContent( secondsToString(EARTH_SECONDS_PER_DAY) );
	server.sendContent(F("</i>"));
	server.sendContent(F("        <p>Moon rotation: </p><i>"));
	server.sendContent( secondsToString(MOON_SECONDS_PER_TURN) );
	server.sendContent(F("</i>"));
	server.sendContent(F("      </div>"));
	server.sendContent(F("\n"));
	server.sendContent(F("      <br><br>"));
	server.sendContent(F("      <h2>&#128213; Logs</h2>"));
	server.sendContent(F("      <br>"));
	server.sendContent(F("      <div style='overflow-x: scroll; padding-bottom: 10px;'>"));
	server.sendContent(F("        <p style='display: inline; white-space: nowrap; overflow-x: scroll;'>"));
	server.sendContent(F("          "));
	server.sendContent( getRingBufferForWeb() );
	server.sendContent(F("\n"));
	server.sendContent(F("        </p>"));
	server.sendContent(F("      </div>"));
	server.sendContent(F("    </div>"));
	server.sendContent(F("    "));
	server.sendContent(F("    <div class='closer'></div>"));
	server.sendContent(F("  </div>"));
	server.sendContent(F("</body>"));
	server.sendContent(F("</html>"));
}

void DefinescssAppPageHandler(ESP8266WebServer& server) {
	server.sendContent(F(":root {"));
	server.sendContent(F("  --color-red: #cc0000;"));
	server.sendContent(F("  --color-red2: #7a0000;"));
	server.sendContent(F("  --color-yellow: #F4AF00;"));
	server.sendContent(F("  --color-green: forestgreen;"));
	server.sendContent(F("  "));
	server.sendContent(F("  --color-light-gray: #C7C7C7;"));
	server.sendContent(F("  --color-gray: #7E7E7E;"));
	server.sendContent(F("  --color-dark-gray: #4A4A4A;"));
	server.sendContent(F("  "));
	server.sendContent(F("  --color-light-white: #F9F9F9;"));
	server.sendContent(F("  --color-white: #FAF9F6;"));
	server.sendContent(F("  --color-dark-white: #F2F2F2; "));
	server.sendContent(F("  "));
	server.sendContent(F("  --color-first: #0B0C10;"));
	server.sendContent(F("  --color-second: #1F2833;"));
	server.sendContent(F("  --color-third: #C5C6C7;"));
	server.sendContent(F("  --color-fourth: #66FCF1;"));
	server.sendContent(F("  --color-fifth: #286090;"));
	server.sendContent(F("\n"));
	server.sendContent(F("  --color-background1: #111111;"));
	server.sendContent(F("  --color-background2: #353535;"));
	server.sendContent(F("  --color-background3: #505050;"));
	server.sendContent(F("  --color-front1: #F2F2F2;"));
	server.sendContent(F("  --color-front2: tomato;"));
	server.sendContent(F("  "));
	server.sendContent(F("  --web-std-width: 960px;"));
	server.sendContent(F("  --select-top-pos: 75vh;"));
	server.sendContent(F("}"));
}

void ControlAppPageHandler(ESP8266WebServer& server) {
	server.sendContent(F("<!DOCTYPE html>"));
	server.sendContent(F("<html lang='en'>"));
	server.sendContent(F("<head>"));
	server.sendContent(F("  <meta charset='UTF-8'>"));
	server.sendContent(F("  <meta name='viewport' content='width=device-width, initial-scale=1.0'>"));
	server.sendContent(F("  <title>Control</title>"));
	server.sendContent(F("\n"));
	server.sendContent(F("  <link rel='stylesheet' href='definesCss.css'>"));
	server.sendContent(F("  <link rel='stylesheet' href='mainCss.css'>"));
	server.sendContent(F("  <link rel='stylesheet' href='mainCss2.css'>"));
	server.sendContent(F("\n"));
	server.sendContent(F("  <script src='mainJs.js'></script>"));
	server.sendContent(F("</head>"));
	server.sendContent(F("<body>"));
	server.sendContent(F("  <div class='content'>"));
	server.sendContent(F("    <div class='vspace'></div>"));
	server.sendContent(F("    <h1>&#127918; Control</h1>"));
	server.sendContent(F("    <p style='text-align: center; font-size: .7em;'>"));
	server.sendContent(F("      <span class='insertSLIDEPOS'>?</span>"));
	server.sendContent( (getSlideStepper()->getPhysicalValueUnit()) );
	server.sendContent(F(" / "));
	server.sendContent(F("      <span class='insertPANPOS'>?</span>"));
	server.sendContent( (getPanStepper()->getPhysicalValueUnit()) );
	server.sendContent(F("</p>"));
	server.sendContent(F("    <div class='control-container'>"));
	server.sendContent(F("      <div></div>"));
	server.sendContent(F("      <div><div class='button' onclick='makeRequest(\"slide_to=1000000\");'>&#11014;</div></div>"));
	server.sendContent(F("      <div></div>"));
	server.sendContent(F("\n"));
	server.sendContent(F("      <div><div class='button' onclick='makeRequest(\"pan_to=1000000\");'>&#8618;</div></div>"));
	server.sendContent(F("      <div><div class='button stop' onclick='makeRequest(\"slide_stop&pan_stop\");'><p>STOP</p></div></div>"));
	server.sendContent(F("      <div><div class='button' onclick='makeRequest(\"pan_to=-1000000\");'>&#8617;</div></div>"));
	server.sendContent(F("\n"));
	server.sendContent(F("      <div></div>"));
	server.sendContent(F("      <div><div class='button' onclick='makeRequest(\"slide_to=-1000000\");'>&#11015;</div></div>"));
	server.sendContent(F("      <div><div class='button' onclick='makeRequest(\"slide_to=0&pan_to=0\");'>&#127969;</div></div>"));
	server.sendContent(F("    </div>"));
	server.sendContent(F("\n"));
	server.sendContent(F("    <div class='main-container'>"));
	server.sendContent(F("      <h3>&#128640; Speed</h3>"));
	server.sendContent(F("      <p style='text-align: center;' id='speed-selection'>Fast</p>"));
	server.sendContent(F("      <input type='range' min='1' max='4' value='2' class='slider' id='myRange' "));
	server.sendContent(F("          style='padding: 0; display: block;'"));
	server.sendContent(F("          onchange='changeSpeed(this);'>"));
	server.sendContent(F("\n"));
	server.sendContent(F("      <br><br>"));
	server.sendContent(F("      <br><br>"));
	server.sendContent(F("      <h3>&#128268; Stepper Power</h3>"));
	server.sendContent(F("      <br><br>"));
	server.sendContent(F("      <div class='side-container'>"));
	server.sendContent(F("        <div class='button main' onclick='makeRequest(\"slide_sleep=1&pan_sleep=1\");'>&#9889; Power On</div>"));
	server.sendContent(F("        <div class='button main' onclick='makeRequest(\"slide_sleep=0&pan_sleep=0\");'>OFF</div>"));
	server.sendContent(F("      </div>"));
	server.sendContent(F("    </div>"));
	server.sendContent(F("\n"));
	server.sendContent(F("  "));
	server.sendContent(F("    "));
	server.sendContent(F("  </div>"));
	server.sendContent(F("  "));
	server.sendContent(F("  <div class='closer'></div>"));
	server.sendContent(F("</body>"));
	server.sendContent(F("</html>"));
}

void PlanAppPageHandler(ESP8266WebServer& server) {
	server.sendContent(F("<!DOCTYPE html>"));
	server.sendContent(F("<html lang='en'>"));
	server.sendContent(F("<head>"));
	server.sendContent(F("  <meta charset='UTF-8'>"));
	server.sendContent(F("  <meta name='viewport' content='width=device-width, initial-scale=1.0'>"));
	server.sendContent(F("  <title>Plan</title>"));
	server.sendContent(F("\n"));
	server.sendContent(F("  <link rel='stylesheet' href='definesCss.css'>"));
	server.sendContent(F("  <link rel='stylesheet' href='mainCss.css'>"));
	server.sendContent(F("  <link rel='stylesheet' href='mainCss2.css'>"));
	server.sendContent(F("\n"));
	server.sendContent(F("  <script src='mainJs.js'></script>"));
	server.sendContent(F("</head>"));
	server.sendContent(F("<body>"));
	server.sendContent(F("  <div class='content'>"));
	server.sendContent(F("    <div class='vspace'></div>"));
	server.sendContent(F("    <h1>&#128203; Plan</h1>"));
	server.sendContent(F("    "));
	server.sendContent(F("    <p>"));
	server.sendContent(F("      TODO"));
	server.sendContent(F("    </p>"));
	server.sendContent(F("\n"));
	server.sendContent(F("    <br><br>"));
	server.sendContent(F("\n"));
	server.sendContent(F("  </div>"));
	server.sendContent(F("</body>"));
	server.sendContent(F("</html>"));
}

void TrackerAppPageHandler(ESP8266WebServer& server) {
	server.sendContent(F("<!DOCTYPE html>"));
	server.sendContent(F("<html lang='en'>"));
	server.sendContent(F("<head>"));
	server.sendContent(F("  <meta charset='UTF-8'>"));
	server.sendContent(F("  <meta name='viewport' content='width=device-width, initial-scale=1.0'>"));
	server.sendContent(F("  <title>Tracker</title>"));
	server.sendContent(F("\n"));
	server.sendContent(F("  <link rel='stylesheet' href='definesCss.css'>"));
	server.sendContent(F("  <link rel='stylesheet' href='mainCss.css'>"));
	server.sendContent(F("  <link rel='stylesheet' href='mainCss2.css'>"));
	server.sendContent(F("\n"));
	server.sendContent(F("  <script src='mainJs.js'></script>"));
	server.sendContent(F("</head>"));
	server.sendContent(F("<body>"));
	server.sendContent(F("  <div class='content'>"));
	server.sendContent(F("    <div class='vspace'></div>"));
	server.sendContent(F("    <h1>&#128301; Star-Tracker</h1>"));
	server.sendContent(F("    "));
	server.sendContent(F("    <p>"));
	server.sendContent(F("\n"));
	server.sendContent(F("    </p>"));
	server.sendContent(F("\n"));
	server.sendContent(F("    <br><br>"));
	server.sendContent(F("    <div class='side-container'>"));
	server.sendContent(F("      <div class='button main'>&#128640; Track Stars</div>"));
	server.sendContent(F("      <div class='button main'>&#10060;</div>"));
	server.sendContent(F("    </div>"));
	server.sendContent(F("\n"));
	server.sendContent(F("  </div>"));
	server.sendContent(F("</body>"));
	server.sendContent(F("</html>"));
}

void MaincssAppPageHandler(ESP8266WebServer& server) {
	server.sendContent(F("\n"));
	server.sendContent(F("* {"));
	server.sendContent(F("  margin: 0;"));
	server.sendContent(F("  padding: 0;"));
	server.sendContent(F("  font-family: sans-serif;"));
	server.sendContent(F("}"));
	server.sendContent(F("\n"));
	server.sendContent(F("html, body {"));
	server.sendContent(F("  width: 100%;"));
	server.sendContent(F("  height: 100%;"));
	server.sendContent(F("}"));
	server.sendContent(F("\n"));
	server.sendContent(F("h1 { "));
	server.sendContent(F("  text-align: center;"));
	server.sendContent(F("}"));
	server.sendContent(F("\n"));
	server.sendContent(F(".vspace {"));
	server.sendContent(F("  height: 40px;"));
	server.sendContent(F("}"));
	server.sendContent(F("\n"));
	server.sendContent(F(".content {"));
	server.sendContent(F("  max-width: 600px !important;"));
	server.sendContent(F("  margin: auto;"));
	server.sendContent(F("}"));
	server.sendContent(F("\n"));
	server.sendContent(F("#status-bar {"));
	server.sendContent(F("  position: fixed;"));
	server.sendContent(F("  top: 0;"));
	server.sendContent(F("\n"));
	server.sendContent(F("  width: 100%;"));
	server.sendContent(F("  height: 30px;"));
	server.sendContent(F("\n"));
	server.sendContent(F("  background-color: var(--color-background1);"));
	server.sendContent(F("  z-index: 20;"));
	server.sendContent(F("}"));
	server.sendContent(F("\n"));
	server.sendContent(F("#status-bar #battery {"));
	server.sendContent(F("  z-index: 21;"));
	server.sendContent(F("\n"));
	server.sendContent(F("  position: relative;"));
	server.sendContent(F("  top: 25%;"));
	server.sendContent(F("  left: 10px;"));
	server.sendContent(F("  height: 33%;"));
	server.sendContent(F("  width: 20px;"));
	server.sendContent(F("\n"));
	server.sendContent(F("  border: solid var(--color-front1) 2px;"));
	server.sendContent(F("  border-radius: 8%;"));
	server.sendContent(F("}"));
	server.sendContent(F("\n"));
	server.sendContent(F("#status-bar #battery #battery-plus-pole {"));
	server.sendContent(F("  position: absolute;"));
	server.sendContent(F("  top: 27%;"));
	server.sendContent(F("  left: 20px;"));
	server.sendContent(F("  height: 20%;"));
	server.sendContent(F("  width: 0px;"));
	server.sendContent(F("\n"));
	server.sendContent(F("  background-color: var(--color-front1);"));
	server.sendContent(F("  border: solid var(--color-front1) 2px;"));
	server.sendContent(F("  border-radius: 20%;"));
	server.sendContent(F("}"));
	server.sendContent(F("\n"));
	server.sendContent(F("#status-bar #battery #battery-fill {"));
	server.sendContent(F("  position: absolute;"));
	server.sendContent(F("  top: 0;"));
	server.sendContent(F("  left: 0;"));
	server.sendContent(F("  height: 100%;"));
	server.sendContent(F("  width: 80%;"));
	server.sendContent(F("\n"));
	server.sendContent(F("  background-color: var(--color-green);"));
	server.sendContent(F("}"));
	server.sendContent(F("\n"));
	server.sendContent(F("#status-bar #battery #battery-glas {"));
	server.sendContent(F("  z-index: 22;"));
	server.sendContent(F("\n"));
	server.sendContent(F("  position: absolute;"));
	server.sendContent(F("  top: 0;"));
	server.sendContent(F("  left: 0;"));
	server.sendContent(F("  height: 100%;"));
	server.sendContent(F("  width: 100%;"));
	server.sendContent(F("\n"));
	server.sendContent(F("  background: rgb(255,255,255);"));
	server.sendContent(F("  background: -moz-linear-gradient(180deg, rgba(255,255,255,0) 0%, rgba(249,249,249,0.25) 50%, rgba(249,249,249,.5) 100%);"));
	server.sendContent(F("  background: -webkit-linear-gradient(180deg, rgba(255,255,255,0) 0%, rgba(249,249,249,0.25) 50%, rgba(249,249,249,.5) 100%);"));
	server.sendContent(F("  background: linear-gradient(180deg, rgba(255,255,255,0) 0%, rgba(249,249,249,0.25) 50%, rgba(249,249,249,.5) 100%);"));
	server.sendContent(F("  filter: progid:DXImageTransform.Microsoft.gradient(startColorstr='#ffffff',endColorstr='#f9f9f9',GradientType=1);"));
	server.sendContent(F("\n"));
	server.sendContent(F("  display: none;"));
	server.sendContent(F("}"));
	server.sendContent(F("\n"));
	server.sendContent(F("#status-bar #e-stop {"));
	server.sendContent(F("  border: solid var(--color-front2) 1px;"));
	server.sendContent(F("  border-radius: 5px;"));
	server.sendContent(F("  padding: 5px 20px;"));
	server.sendContent(F("\n"));
	server.sendContent(F("  cursor: pointer;"));
	server.sendContent(F("  text-align: center;"));
	server.sendContent(F("\n"));
	server.sendContent(F("  position: relative;"));
	server.sendContent(F("  top: 0;"));
	server.sendContent(F("  left: 50%;"));
	server.sendContent(F("  width: 50px;"));
	server.sendContent(F("\n"));
	server.sendContent(F("  transform: translate(-50%, -50%);"));
	server.sendContent(F("}"));
	server.sendContent(F("\n"));
	server.sendContent(F("#status-bar #e-stop:hover {"));
	server.sendContent(F("  background-color: var(--color-front2);"));
	server.sendContent(F("}"));
	server.sendContent(F("\n"));
	server.sendContent(F("#status-bar #e-stop p {"));
	server.sendContent(F("  color: var(--color-front1);"));
	server.sendContent(F("  font-size: .5em;"));
	server.sendContent(F("}"));
	server.sendContent(F("\n"));
	server.sendContent(F("#status-bar .status {"));
	server.sendContent(F("  position: absolute;"));
	server.sendContent(F("  top: 8px;"));
	server.sendContent(F("  color: var(--color-front1);"));
	server.sendContent(F("  font-size: .7em;"));
	server.sendContent(F("}"));
	server.sendContent(F("\n"));
	server.sendContent(F("#status-bar .status.left {"));
	server.sendContent(F("  left: 50px;"));
	server.sendContent(F("  cursor: pointer;"));
	server.sendContent(F("}"));
	server.sendContent(F("\n"));
	server.sendContent(F("#status-bar-detail {"));
	server.sendContent(F("  background-color: var(--color-background2);"));
	server.sendContent(F("  position: absolute;"));
	server.sendContent(F("  top: 30px;"));
	server.sendContent(F("  left: 0;"));
	server.sendContent(F("  width: 100%;"));
	server.sendContent(F("  height: 0;"));
	server.sendContent(F("  z-index: 20;"));
	server.sendContent(F("\n"));
	server.sendContent(F("  transition: ease .3s all;"));
	server.sendContent(F("  overflow: hidden;"));
	server.sendContent(F("\n"));
	server.sendContent(F("  color: var(--color-front1);"));
	server.sendContent(F("}"));
	server.sendContent(F("\n"));
	server.sendContent(F("#status-bar-detail h1 {"));
	server.sendContent(F("  margin-top: 10px;"));
	server.sendContent(F("  margin-left: 20px;"));
	server.sendContent(F("}"));
	server.sendContent(F("\n"));
	server.sendContent(F("#status-bar-detail p {"));
	server.sendContent(F("  margin-top: 5px;"));
	server.sendContent(F("  margin-left: 30px;"));
	server.sendContent(F("  text-align: center;"));
	server.sendContent(F("}"));
	server.sendContent(F("\n"));
	server.sendContent(F("#status-bar-detail.open {"));
	server.sendContent(F("  height: 100%;"));
	server.sendContent(F("  overflow-y: auto;"));
	server.sendContent(F("}"));
	server.sendContent(F("\n"));
	server.sendContent(F("#status-bar .status.right {"));
	server.sendContent(F("  right: 10px;"));
	server.sendContent(F("}"));
	server.sendContent(F("\n"));
	server.sendContent(F("#status-bar #connection, #status-bar #power-state {"));
	server.sendContent(F("  margin-right: 10px;"));
	server.sendContent(F("}"));
	server.sendContent(F("\n"));
	server.sendContent(F(".select {"));
	server.sendContent(F("  position: fixed;"));
	server.sendContent(F("  width: 200vw;"));
	server.sendContent(F("  height: 200vw;"));
	server.sendContent(F("  min-width: 500px;"));
	server.sendContent(F("  min-height: 500px;"));
	server.sendContent(F("  max-width: 960px;"));
	server.sendContent(F("  max-height: 960px;"));
	server.sendContent(F("\n"));
	server.sendContent(F("  border-radius: 50%;"));
	server.sendContent(F("  margin: auto;"));
	server.sendContent(F("\n"));
	server.sendContent(F("  background-color: var(--color-background1);"));
	server.sendContent(F("}"));
	server.sendContent(F("\n"));
	server.sendContent(F(".select.wheel {"));
	server.sendContent(F("  position: fixed;"));
	server.sendContent(F("  left: 50%;"));
	server.sendContent(F("  top: 0;"));
	server.sendContent(F("  transform: translate(-50%, var(--select-top-pos));"));
	server.sendContent(F("\n"));
	server.sendContent(F("  transition: all .3s ease;"));
	server.sendContent(F("\n"));
	server.sendContent(F("  box-shadow: 1px -1px 33px 6px rgba(0,0,0,0.75);"));
	server.sendContent(F("  -webkit-box-shadow: 1px -1px 33px 6px rgba(0,0,0,0.75);"));
	server.sendContent(F("  -moz-box-shadow: 1px -1px 33px 6px rgba(0,0,0,0.75);"));
	server.sendContent(F("\n"));
	server.sendContent(F("  z-index: 20;"));
	server.sendContent(F("}"));
}

#endif