
#ifndef HTML_FILES_H
#define HTML_FILES_H

#include "common.h"
#include "io.h"
#include "stepper.h"
#include "debug.h"
    

String getIndexPage() {
	String site = "<!doctype html>";
	site += "";
	site += "<html lang='en'>";
	site += "";
	site += "";
	site += "            <head>";
	site += "            <meta charset='utf-8'>";
	site += "";
	site += "            <meta charset='utf-8'>";
	site += "            <meta name='viewport' content='width=device-width, initial-scale=1.0'>";
	site += "";
	site += "            <title>Slide and Pan</title>";
	site += "            <meta name='description' content='Slide and Pan'>";
	site += "            <meta name='author' content='Sebastian Knoll'>";
	site += "";
	site += "            <link rel='stylesheet' href='main.css'>";
	site += "            <script src='main.js'></script>";
	site += "";
	site += "            </head>";
	site += "          ";
	site += "";
	site += "<body>";
	site += "  ";
	site += "  ";
	site += "";
	site += "  ";
	site += "";
	site += "  <div id='container'>";
	site += "    <h1>&#128377; Manual control</h1>";
	site += "";
	site += "    <ul>";
	site += "      <li><a href='index'>Control</a></li>";
	site += "      <li><a href='timelapse'>Timelapse</a></li>";
	site += "      <li><a href='settings'>Settings</a></li>";
	site += "    </ul>";
	site += "";
	site += "    ";
	site += "<div id=\"slider-info\">";
	site += "  <p id=\"info\">&#128677; Current State</p>";
	site += "  <h1 class=\"insertSTATE\">" + getSliderStateString() + "</h1>";
	site += "  <p class=\"insertSTATEDETAIL\">" + getSliderSubStateString() + "</p>";
	site += "  <button class=\"block\" onclick='makeRequest(\"timelapse_stop&slide_stop&pan_stop\");'>Stop</button>";
	site += "</div>";
	site += "<script> startStreamListener(); </script>";
	site += "";
	site += "";
	site += "    <br>";
	site += "";
	site += "    <div class='section'>";
	site += "      <h2>&#127918; Control</h2>";
	site += "      <br>";
	site += "      <button class='block' onclick='makeRequest(\"slide_to=1000000\");'>Slide Left</button>";
	site += "      <br>";
	site += "      <button class='block' onclick='makeRequest(\"slide_to=-1000000\");'>Slide Right</button>";
	site += "      <br>";
	site += "      <button class='block' onclick='makeRequest(\"pan_to=1000000\");'>Pan Left</button>";
	site += "      <br>";
	site += "      <button class='block' onclick='makeRequest(\"pan_to=-1000000\");'>Pan Right</button>";
	site += "      <br><br>";
	site += "      <button class='block' onclick='makeRequest(\"slide_stop&pan_stop\");'>Stop</button>";
	site += "      <br>";
	site += "    </div>";
	site += "";
	site += "    <br><br>";
	site += "";
	site += "    <div class='section'>";
	site += "      <h2>&#128640; Speed</h2>";
	site += "      <br>";
	site += "      <button class='block' onclick='makeRequest(\"slide_speed=1&pan_speed=2\");'>Fast</button>";
	site += "      <br>";
	site += "      <button class='block' onclick='makeRequest(\"slide_speed=0.5&pan_speed=1\");'>Middle</button>";
	site += "      <br>";
	site += "      <button class='block' onclick='makeRequest(\"slide_speed=0.25&pan_speed=0.5\");'>Slow</button>";
	site += "      <br>";
	site += "      <button class='block' onclick='makeRequest(\"slide_speed=0.05&pan_speed=0.05\");'>Extrem slow</button>";
	site += "      <br>";
	site += "    </div>";
	site += "";
	site += "    <br><br>";
	site += "";
	site += "    <div class='section'>";
	site += "      <h2>&#128268; Power</h2>";
	site += "      <br>";
	site += "      <button class='block' onclick='makeRequest(\"slide_sleep=0&pan_sleep=0\");'>Sleep</button>";
	site += "      <br>";
	site += "      <button class='block' onclick='makeRequest(\"slide_sleep=1&pan_sleep=1\");'>Power ON</button>";
	site += "      <br>";
	site += "    </div>";
	site += "";
	site += "    <br>";
	site += "    <br>";
	site += "";
	site += "    <a style='text-align: center; display: block;' href='about'>About</a>";
	site += "";
	site += "    <br><br><br><br>";
	site += "    <br><br><br><br>";
	site += "  </div>";
	site += "</body>";
	site += "</html>";

	return site;
}

String getTimelapsePage() {
	String site = "<!doctype html>";
	site += "";
	site += "<html lang='en'>";
	site += "";
	site += "";
	site += "            <head>";
	site += "            <meta charset='utf-8'>";
	site += "";
	site += "            <meta charset='utf-8'>";
	site += "            <meta name='viewport' content='width=device-width, initial-scale=1.0'>";
	site += "";
	site += "            <title>Slide and Pan</title>";
	site += "            <meta name='description' content='Slide and Pan'>";
	site += "            <meta name='author' content='Sebastian Knoll'>";
	site += "";
	site += "            <link rel='stylesheet' href='main.css'>";
	site += "            <script src='main.js'></script>";
	site += "";
	site += "            </head>";
	site += "          ";
	site += "";
	site += "<body>";
	site += "  ";
	site += "  ";
	site += "";
	site += "  ";
	site += "";
	site += "  <div id='container'>";
	site += "    <h1>&#9202; Timelapse</h1>";
	site += "";
	site += "    <ul>";
	site += "      <li><a href='index'>Control</a></li>";
	site += "      <li><a href='timelapse'>Timelapse</a></li>";
	site += "      <li><a href='settings'>Settings</a></li>";
	site += "    </ul>";
	site += "";
	site += "    <br>";
	site += "";
	site += "    ";
	site += "<div id=\"slider-info\">";
	site += "  <p id=\"info\">&#128677; Current State</p>";
	site += "  <h1 class=\"insertSTATE\">" + getSliderStateString() + "</h1>";
	site += "  <p class=\"insertSTATEDETAIL\">" + getSliderSubStateString() + "</p>";
	site += "  <button class=\"block\" onclick='makeRequest(\"timelapse_stop&slide_stop&pan_stop\");'>Stop</button>";
	site += "</div>";
	site += "<script> startStreamListener(); </script>";
	site += "";
	site += "";
	site += "    <div class='section'>";
	site += "      <h2>&#10024; Milkyway</h2>";
	site += "      <br>";
	site += "      <p style='display: inline-block;'>Slide:</p> ";
	site += "      <input value='" + String(getTimelapseSlideSteps()) + "' step='0.001' min='-5000' max='5000' id='mw_slide'> " + (getSlideStepper()->getPhysicalValueUnit()) + "";
	site += "      <br>";
	site += "      <p style='display: inline-block;'>Photo count:</p>";
	site += "      <input value='" + String(getTimelapsePictureCount()) + "' min='0' max='5000' id='mw_count'> #";
	site += "      <br>";
	site += "      <p style='display: inline-block;'>Exposure Time:</p>";
	site += "      <input value='" + String(getIOBoard()->getCameraExposureTime()) + "' step='0.1' min='0' max='500' id='mw_photo'> s";
	site += "      <br>";
	site += "      <p style='display: inline-block;'>Interval Time:</p> ";
	site += "      <input value='" + String(getTimelapseInterval()) + "' min='0' max='500' id='mw_interval'> s";
	site += "      <br>";
	site += "      <p style='display: inline-block;'>Hemisphere: <a href='#' onclick='makeRequest(\"timelapse_set_hemisphere=" + String(!isTimelapseInNortherHemisphere() ? 1 : 0) + "\");'><i>" + String(isTimelapseInNortherHemisphere() ? "Northern" : "South") + "</i></a></p> ";
	site += "      <br>";
	site += "      <button class='block' onclick='makeRequest(\"timelapse_slide=\" + document.getElementById(\"mw_slide\").value + \"&timelapse_count=\" + document.getElementById(\"mw_count\").value + \"&timelapse_photo=\" + document.getElementById(\"mw_photo\").value + \"&timelapse_interval=\" + document.getElementById(\"mw_interval\").value + \"&timelapse_milkyway_settings=1\");'>Shoot Milkyway</button>";
	site += "      <br>";
	site += "      <br>";
	site += "      <p style='display: inline-block;'>Pan set to: " + String(getTimelapsePanSteps()) + "" + (getPanStepper()->getPhysicalValueUnit()) + "</p>";
	site += "      <br>";
	site += "    </div>";
	site += "";
	site += "    <br><br>";
	site += "";
	site += "    <div class='section'>";
	site += "      <h2>&#9654; Start / Stop</h2>";
	site += "      <br>";
	site += "      <button class='block' onclick='makeRequest(\"timelapse_start\");'>Start Timelapse</button>";
	site += "      <br>";
	site += "      <button class='block' onclick='makeRequest(\"timelapse_stop\");'>Stop Timelapse</button>";
	site += "      <br>";
	site += "      <br>";
	site += "      <button class='block' onclick='makeRequest(\"timelapse_preview_start\");'>Start Preview</button>";
	site += "      <br>";
	site += "      <button class='block' onclick='makeRequest(\"timelapse_preview_stop\");'>Stop Preview</button>";
	site += "      <br>";
	site += "    </div>";
	site += "";
	site += "    <br><br>";
	site += "";
	site += "    <div class='section'>";
	site += "      <h2>&#128377; Manual</h2>";
	site += "      <br>";
	site += "      <input value='" + String(getTimelapsePanSteps()) + "' type='number' step='0.001' min='-5000' max='5000' id='pan'> " + (getPanStepper()->getPhysicalValueUnit()) + "";
	site += "      <button class='set_button' onclick='makeRequest(\"timelapse_pan=\" + document.getElementById(\"pan\").value);'>Set Pan</button>";
	site += "      <br>";
	site += "      <input value='" + String(getTimelapseSlideSteps()) + "' type='number' step='0.001' min='-5000' max='5000' id='slide'> " + (getSlideStepper()->getPhysicalValueUnit()) + "";
	site += "      <button class='set_button' onclick='makeRequest(\"timelapse_slide=\" + document.getElementById(\"slide\").value);'>Set Slide</button>";
	site += "      <br>";
	site += "      <input value='" + String(getTimelapsePictureCount()) + "' min='0' max='5000' id='count'> #";
	site += "      <button class='set_button' onclick='makeRequest(\"timelapse_count=\" + document.getElementById(\"count\").value);'>Set Picture count</button>";
	site += "      <br>";
	site += "      <input value='" + String(getIOBoard()->getCameraExposureTime()) + "' step='0.1' min='0' max='500' id='photo'> s";
	site += "      <button class='set_button' onclick='makeRequest(\"timelapse_photo=\" + document.getElementById(\"photo\").value);'>Set Photo Interval</button>";
	site += "      <br>";
	site += "      <input value='" + String(getTimelapseInterval()) + "' min='0' max='500' id='interval'> s";
	site += "      <button class='set_button' onclick='makeRequest(\"timelapse_interval=\" + document.getElementById(\"interval\").value);'>Set Timelapse interval</button>";
	site += "      <br>";
	site += "      <br>";
	site += "      <button class='block' onclick='makeRequest(\"timelapse_slide=\" + document.getElementById(\"slide\").value + \"&timelapse_count=\" + document.getElementById(\"count\").value + \"&timelapse_photo=\" + document.getElementById(\"photo\").value + \"&timelapse_interval=\" + document.getElementById(\"interval\").value + \"&timelapse_pan=\" + document.getElementById(\"pan\").value);'>Set all</button>";
	site += "      <br>";
	site += "    </div>";
	site += "";
	site += "    <br><br>";
	site += "";
	site += "    <div class='section'>";
	site += "      <h2>&#127916; Timelapse-Info</h2>";
	site += "";
	site += "      <br>";
	site += "      <p>Total time: <i>" + secondsToString(getTimelapseTotalTime()) + "</i></p>";
	site += "      <p>End time: <i>" + secondsToTimeString(getTimelapseEndTime()) + "</i></p>";
	site += "      <br>";
	site += "      <p>Total slide: <i>" + String(getTimelapseTotalSlideDistance()) + "</i> " + (getSlideStepper()->getPhysicalValueUnit()) + "</p>";
	site += "      <p>Total pan: <i>" + String(getTimelapseTotalPanDistance()) + "</i> " + (getPanStepper()->getPhysicalValueUnit()) + "</p>";
	site += "      <br>";
	site += "      <p>Video length (24fps): <i>" + secondsToString(getTimelapseVideoTimePrediction(24)) + "</i></p>";
	site += "      <p>Video length (25fps): <i>" + secondsToString(getTimelapseVideoTimePrediction(25)) + "</i></p>";
	site += "      <p>Video length (30fps): <i>" + secondsToString(getTimelapseVideoTimePrediction(30)) + "</i></p>";
	site += "      <p>Video length (60fps): <i>" + secondsToString(getTimelapseVideoTimePrediction(60)) + "</i></p>";
	site += "      <br>";
	site += "    </div>";
	site += "  </div>";
	site += "";
	site += "  <br>";
	site += "  <br>";
	site += "";
	site += "  <a style='text-align: center; display: block;' href='about'>About</a>";
	site += "";
	site += "  <br><br><br><br>";
	site += "  <br><br><br><br>";
	site += "";
	site += "  ";
	site += "</body>";
	site += "</html>";

	return site;
}

String getSettingsPage() {
	String site = "<!doctype html>";
	site += "";
	site += "<html lang='en'>";
	site += "";
	site += "";
	site += "            <head>";
	site += "            <meta charset='utf-8'>";
	site += "";
	site += "            <meta charset='utf-8'>";
	site += "            <meta name='viewport' content='width=device-width, initial-scale=1.0'>";
	site += "";
	site += "            <title>Slide and Pan</title>";
	site += "            <meta name='description' content='Slide and Pan'>";
	site += "            <meta name='author' content='Sebastian Knoll'>";
	site += "";
	site += "            <link rel='stylesheet' href='main.css'>";
	site += "            <script src='main.js'></script>";
	site += "";
	site += "            </head>";
	site += "          ";
	site += "";
	site += "<body>";
	site += "";
	site += "  ";
	site += "";
	site += "  ";
	site += "";
	site += "  <div id='container'>";
	site += "    <h1>&#9881; Settings</h1>";
	site += "";
	site += "    <ul>";
	site += "      <li><a href='index'>Control</a></li>";
	site += "      <li><a href='timelapse'>Timelapse</a></li>";
	site += "      <li><a href='settings'>Settings</a></li>";
	site += "    </ul>";
	site += "";
	site += "    ";
	site += "<div id=\"slider-info\">";
	site += "  <p id=\"info\">&#128677; Current State</p>";
	site += "  <h1 class=\"insertSTATE\">" + getSliderStateString() + "</h1>";
	site += "  <p class=\"insertSTATEDETAIL\">" + getSliderSubStateString() + "</p>";
	site += "  <button class=\"block\" onclick='makeRequest(\"timelapse_stop&slide_stop&pan_stop\");'>Stop</button>";
	site += "</div>";
	site += "<script> startStreamListener(); </script>";
	site += "";
	site += "";
	site += "    <br>";
	site += "";
	site += "    <div class='section'>";
	site += "      <h2>&#8596; Slide</h2>";
	site += "      <br>";
	site += "      <p>" + (getSlideStepper()->getPhysicalValueDescription()) + ": <i>" + (getSlideStepper()->getPhysicalValueInfo()) + "</i> <button onclick='makeRequest(\"slide_reset\");'>Center</button></p>";
	site += "      <input type='number' value='" + (getSlideStepper()->getPhysicalValueInfo()) + "' step='0.001' min='-50000' max='50000' id='slide_pv'>";
	site += "      <button class='set_button' onclick='makeRequest(\"slide_physical_value=\" + document.getElementById(\"slide_pv\").value);'>Go to " + (getSlideStepper()->getPhysicalValueDescription()) + "</button>";
	site += "      <br>";
	site += "      <br>";
	site += "      <p>Sleep: <i>" + String(getSlideStepper()->isSleeping() ? "Sleeping" : "Awake") + "</i> <button onclick='makeRequest(\"slide_sleep=" + String(getSlideStepper()->isSleeping() ? 1 : 0) + "\");'>" + String(getSlideStepper()->isSleeping() ? "Awake" : "Sleep") + "</button></p>";
	site += "      <p>Steps: <i>" + String(getSlideStepper()->getSteps()) + "</i>/<i>" + String(getSlideStepper()->getTargetSteps()) + "</i></p>";
	site += "      <p>Speed: <i>" + String(getSlideStepper()->getSpeed()) + "</i>/<i>" + String(getSlideStepper()->getTargetSpeed()) + "</i></p>";
	site += "      <p>LazyMode: <i>" + String(getSlideStepper()->isInLazyMode() ? "Yes" : "No") + "</i> <button onclick='makeRequest(\"slide_lazy=" + String(getSlideStepper()->isInLazyMode() ? 0 : 1) + "\");'>" + String(getSlideStepper()->isInLazyMode() ? "Go Strong" : "Go Lazy") + "</button></p>";
	site += "      <br>";
	site += "      <p>Resolution: <i>" + String(getSlideStepper()->getResolution()) + "</i></p>";
	site += "      ";
	site += "      <div>";
	site += "        <button onclick='makeRequest(\"slide_res=1\");'>1</button>";
	site += "        <button onclick='makeRequest(\"slide_res=2\");'>2</button>";
	site += "        <button onclick='makeRequest(\"slide_res=4\");'>4</button>";
	site += "        <button onclick='makeRequest(\"slide_res=8\");'>8</button>";
	site += "        <button onclick='makeRequest(\"slide_res=16\");'>16</button>";
	site += "      </div>";
	site += "      <br>";
	site += "    </div>";
	site += "";
	site += "    <br><br>";
	site += "";
	site += "    <div class='section'>";
	site += "      <h2>&#8618; Pan</h2>";
	site += "      <br>";
	site += "      <p>" + (getPanStepper()->getPhysicalValueDescription()) + ": <i>" + (getPanStepper()->getPhysicalValueInfo()) + "</i> <button onclick='makeRequest(\"pan_reset\");'>Center</button></p>";
	site += "      <input type='number' value='" + (getPanStepper()->getPhysicalValueInfo()) + "' step='0.001' min='-50000' max='50000' id='pan_pv'>";
	site += "      <button class='set_button' onclick='makeRequest(\"pan_physical_value=\" + document.getElementById(\"pan_pv\").value);'>Go to " + (getPanStepper()->getPhysicalValueDescription()) + "</button>";
	site += "      <br>";
	site += "      <br>";
	site += "      <p>Sleep: <i>" + String(getPanStepper()->isSleeping() ? "Sleeping" : "Awake") + "</i> <button onclick='makeRequest(\"pan_sleep=" + String(getPanStepper()->isSleeping() ? 1 : 0) + "\");'>" + String(getPanStepper()->isSleeping() ? "Awake" : "Sleep") + "</button></p>";
	site += "      <p>Steps: <i>" + String(getPanStepper()->getSteps()) + "</i>/<i>" + String(getPanStepper()->getTargetSteps()) + "</i></p>";
	site += "      <p>Speed: <i>" + String(getPanStepper()->getSpeed()) + "</i>/<i>" + String(getPanStepper()->getTargetSpeed()) + "</i></p>";
	site += "      <p>LazyMode: <i>" + String(getPanStepper()->isInLazyMode() ? "Yes" : "No") + "</i> <button onclick='makeRequest(\"pan_lazy=" + String(getPanStepper()->isInLazyMode() ? 0 : 1) + "\");'>" + String(getPanStepper()->isInLazyMode() ? "Go Strong" : "Go Lazy") + "</button></p>";
	site += "      <br>";
	site += "      <p>Resolution: <i>" + String(getPanStepper()->getResolution()) + "</i></p>";
	site += "      ";
	site += "      <div>";
	site += "        <button onclick='makeRequest(\"pan_res=1\");'>1</button>";
	site += "        <button onclick='makeRequest(\"pan_res=2\");'>2</button>";
	site += "        <button onclick='makeRequest(\"pan_res=4\");'>4</button>";
	site += "        <button onclick='makeRequest(\"pan_res=8\");'>8</button>";
	site += "        <button onclick='makeRequest(\"pan_res=16\");'>16</button>";
	site += "      </div>";
	site += "      <br>";
	site += "    </div>";
	site += "";
	site += "    <br><br>";
	site += "";
	site += "    <div class='section'>";
	site += "      <h2>&#128203; Additional</h2>";
	site += "      <br>";
	site += "      <p>Battery-Level: <i>" + String(getIOBoard()->getBatteryLevel()) + "</i></p>";
	site += "      <br>";
	site += "      <p>S/P LazyMode: <i>" + String(getPanStepper()->isInLazyMode() ? "Yes" : "No") + "</i>/<i>" + String(getPanStepper()->isInLazyMode() ? "Yes" : "No") + "</i></p>";
	site += "      <button onclick='makeRequest(\"pan_lazy=1&slide_lazy=1\");'>Set both Lazy</button>";
	site += "      <button onclick='makeRequest(\"pan_lazy=0&slide_lazy=0\");'>Set both Strong</button>";
	site += "      <br>";
	site += "      <br>";
	site += "      <br>";
	site += "      <p id='darkMode' name='darkMode'>DarkMode: <a href='#darkMode' onclick='makeRequest(\"set_darkmode=" + String(isSliderInDarkMode() ? 0 : 1) + "\");'><i>" + String(isSliderInDarkMode() ? "is On" : "is Off") + "</i></a></p>";
	site += "      <br>";
	site += "    </div>";
	site += "";
	site += "    <br>";
	site += "    <br>";
	site += "";
	site += "    <div class='section'>";
	site += "      <h2>&#128451; Logs</h2>";
	site += "      <br>";
	site += "      <div style='overflow-x: scroll; padding-bottom: 10px;'>";
	site += "        <p style='display: inline; white-space: nowrap; overflow-x: scroll;'>" + getRingBufferForWeb() + "</p>";
	site += "      </div>";
	site += "      <br>";
	site += "    </div>";
	site += "  </div>";
	site += "";
	site += "  <br>";
	site += "  <br>";
	site += "";
	site += "  <a style='text-align: center; display: block;' href='about'>About</a>";
	site += "";
	site += "  <br><br><br><br>";
	site += "  <br><br><br><br>";
	site += "</body>";
	site += "</html>";

	return site;
}

String getAboutPage() {
	String site = "<!doctype html>";
	site += "";
	site += "<html lang='en'>";
	site += "";
	site += "";
	site += "            <head>";
	site += "            <meta charset='utf-8'>";
	site += "";
	site += "            <meta charset='utf-8'>";
	site += "            <meta name='viewport' content='width=device-width, initial-scale=1.0'>";
	site += "";
	site += "            <title>Slide and Pan</title>";
	site += "            <meta name='description' content='Slide and Pan'>";
	site += "            <meta name='author' content='Sebastian Knoll'>";
	site += "";
	site += "            <link rel='stylesheet' href='main.css'>";
	site += "            <script src='main.js'></script>";
	site += "";
	site += "            </head>";
	site += "          ";
	site += "";
	site += "<body>";
	site += "  ";
	site += "";
	site += "  ";
	site += "";
	site += "  <div id='container'>";
	site += "    <h1>&#128199; About</h1>";
	site += "";
	site += "    <ul>";
	site += "      <li><a href='index'>Control</a></li>";
	site += "      <li><a href='timelapse'>Timelapse</a></li>";
	site += "      <li><a href='settings'>Settings</a></li>";
	site += "    </ul>";
	site += "";
	site += "    ";
	site += "<div id=\"slider-info\">";
	site += "  <p id=\"info\">&#128677; Current State</p>";
	site += "  <h1 class=\"insertSTATE\">" + getSliderStateString() + "</h1>";
	site += "  <p class=\"insertSTATEDETAIL\">" + getSliderSubStateString() + "</p>";
	site += "  <button class=\"block\" onclick='makeRequest(\"timelapse_stop&slide_stop&pan_stop\");'>Stop</button>";
	site += "</div>";
	site += "<script> startStreamListener(); </script>";
	site += "";
	site += "";
	site += "    <br>";
	site += "";
	site += "    <div class='section'>";
	site += "      <h2>&#128202; Slider Inforamtion</h2>";
	site += "      <br>";
	site += "      <p>Name: <i>" + String(SLIDEANDPAN_NAME) + "</i></p>";
	site += "      <p>Version: <i>" + String(SLIDEANDPAN_VERSION) + "</i></p>";
	site += "      <p>Copyright: <i>" + String(SLIDEANDPAN_COPYRIGHT) + "</i></p>";
	site += "      <p>ID: <i>" + String(SLIDEANDPAN_ID) + "</i></p>";
	site += "      <br>";
	site += "      <a style='text-align: center; display: block;' href='detail'>More details</a>";
	site += "";
	site += "      <br>";
	site += "    </div>";
	site += "";
	site += "    <br><br>";
	site += "";
	site += "    <div class='section'>";
	site += "      <h2>&#128681; Author</h2>";
	site += "      <br>";
	site += "      <p>";
	site += "        My name is <i>Sebastian Knoll</i> and I am the inventor and author of this project. ";
	site += "        If you have any question regarding me or the app do not hesitate to ";
	site += "        <a href='https://sebastianknoll.net/me/contact.php'>contact me</a> or visit my ";
	site += "        <a href='https://sebastianknoll.net/'>homepage</a>. ";
	site += "        <br>";
	site += "        <br>";
	site += "        If you have any legal concerns, note that this is an private application ";
	site += "        which you can use at your own risk. Furthermore you can checkout ";
	site += "        <a href='https://sebastianknoll.net/gtc/'>legal stuff</a> and ";
	site += "        <a href='https://sebastianknoll.net/gtc/TODO'>legal stuff for Slide and Pan</a>.";
	site += "      </p>";
	site += "      <br>";
	site += "    </div>";
	site += "";
	site += "    <br><br>";
	site += "";
	site += "    <div class='section'>";
	site += "      <h2>&#127829; More</h2>";
	site += "      <br>";
	site += "      <p>";
	site += "      Use the Hashtag <a href='https://www.instagram.com/explore/tags/slideandpan/'>#slideandpan</a> so that we can see your amazing work.";
	site += "      </p>";
	site += "      <br>";
	site += "      <p>Use the <a href='" + String(SLIDEANDPAN_LINK_HANDBOOK) + "'>Handbook</a> for more information and tutorials.</p>";
	site += "      <br>";
	site += "    </div>";
	site += "  </div>";
	site += "";
	site += "";
	site += "  <br><br><br><br>";
	site += "  <br><br><br><br>";
	site += "  ";
	site += "</body>";
	site += "</html>";

	return site;
}

String getNormal_timelapsePage() {
	String site = "<!doctype html>";
	site += "";
	site += "<html lang='en'>";
	site += "";
	site += "<head>";
	site += "  <meta charset=\"utf-8\">";
	site += "";
	site += "  <meta charset=\"utf-8\">";
	site += "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">";
	site += "";
	site += "  <title>Slide and Pan</title>";
	site += "  <meta name=\"description\" content=\"Slide and Pan\">";
	site += "  <meta name=\"author\" content=\"Sebastian Knoll\">";
	site += "";
	site += "</head>";
	site += "";
	site += "<body>";
	site += "  ";
	site += "  <style>";
	site += "    * {";
	site += "      font-family:courier,arial,helvetica;";
	site += "    }";
	site += "";
	site += "    body {";
	site += "      background-color: rgb(180, 180, 180);";
	site += "    }";
	site += "";
	site += "    li {";
	site += "      display:inline-block;";
	site += "      margin: 5px;";
	site += "    }";
	site += "";
	site += "    ul {";
	site += "      margin: 0 auto;";
	site += "      display: inherit;";
	site += "    }";
	site += "";
	site += "    h1, h2, h3 {";
	site += "      text-align: center;";
	site += "    }";
	site += "";
	site += "    #container {";
	site += "      width: 100%;";
	site += "      max-width: 960px;";
	site += "      margin: 0 auto;";
	site += "    }";
	site += "";
	site += "    .section {";
	site += "";
	site += "      background: whitesmoke;";
	site += "      border-radius: 20px;";
	site += "";
	site += "      padding: 20px;";
	site += "    }";
	site += "";
	site += "    input {";
	site += "      width: 50px;";
	site += "    }";
	site += "";
	site += "    .set_button {";
	site += "      width: 200px;";
	site += "    }";
	site += "";
	site += "    .block {";
	site += "      display: block;";
	site += "      width: 100%;";
	site += "      height: 50px;;";
	site += "    }";
	site += "";
	site += "  </style>";
	site += "";
	site += "  <script>";
	site += "";
	site += "    function makeRequest(command) {";
	site += "      var url = '/device/command/?' + command;";
	site += "      ";
	site += "      var request = new XMLHttpRequest();";
	site += "";
	site += "      request.onreadystatechange = function() {";
	site += "        if (this.readyState == 4 && this.status == 200) {";
	site += "          location.reload();";
	site += "        }";
	site += "      };";
	site += "";
	site += "      request.open('GET',url);";
	site += "      request.send();";
	site += "    }";
	site += "";
	site += "  </script>";
	site += "";
	site += "  <div id='container'>";
	site += "    <h1>Timelapse</h1>";
	site += "";
	site += "    <ul>";
	site += "      <li><a href='index'>Control</a></li>";
	site += "      <li><a href='timelapse'>Timelapse</a></li>";
	site += "      <li><a href='settings'>Settings</a></li>";
	site += "    </ul>";
	site += "";
	site += "    <br>";
	site += "";
	site += "    <div class='section'>";
	site += "      <h2>Milkyway</h2>";
	site += "      <br>";
	site += "      <p style='display: inline-block;'>Slide:</p> ";
	site += "      <input value='" + String(getTimelapseSlideSteps()) + "' step='0.001' min='-5000' max='5000' id='mw_slide'> " + (getSlideStepper()->getPhysicalValueUnit()) + "";
	site += "      <br>";
	site += "      <p style='display: inline-block;'>Photo count:</p>";
	site += "      <input value='" + String(getTimelapsePictureCount()) + "' min='0' max='5000' id='mw_count'> #";
	site += "      <br>";
	site += "      <p style='display: inline-block;'>Exposure Time:</p>";
	site += "      <input value='" + String(getIOBoard()->getCameraExposureTime()) + "' min='0' max='500' id='mw_photo'> s";
	site += "      <br>";
	site += "      <p style='display: inline-block;'>Interval Time:</p> ";
	site += "      <input value='" + String(getTimelapseInterval()) + "' min='0' max='500' id='mw_interval'> s";
	site += "      <br>";
	site += "      <button class='block' onclick='makeRequest(\"timelapse_slide=\" + document.getElementById(\"mw_slide\").value + \"&timelapse_count=\" + document.getElementById(\"mw_count\").value + \"&timelapse_photo=\" + document.getElementById(\"mw_photo\").value + \"&timelapse_interval=\" + document.getElementById(\"mw_interval\").value + \"&timelapse_milkyway_settings=1\");'>Shoot Milkyway</button>";
	site += "      <br>";
	site += "      <br>";
	site += "      <p style='display: inline-block;'>Pan set to: " + String(getTimelapsePanSteps()) + "" + (getPanStepper()->getPhysicalValueUnit()) + "</p>";
	site += "      <br>";
	site += "    </div>";
	site += "";
	site += "    <br><br>";
	site += "";
	site += "    <div class='section'>";
	site += "      <h2>Start / Stop</h2>";
	site += "      <br>";
	site += "      <button class='block' onclick='makeRequest(\"timelapse_start\");'>Start Timelapse</button>";
	site += "      <br>";
	site += "      <button class='block' onclick='makeRequest(\"timelapse_stop\");'>Stop Timelapse</button>";
	site += "      <br>";
	site += "      <br>";
	site += "      <button class='block' onclick='makeRequest(\"timelapse_preview_start\");'>Start Preview</button>";
	site += "      <br>";
	site += "      <button class='block' onclick='makeRequest(\"timelapse_preview_stop\");'>Stop Preview</button>";
	site += "      <br>";
	site += "    </div>";
	site += "";
	site += "    <br><br>";
	site += "";
	site += "    <div class='section'>";
	site += "      <h2>Manual</h2>";
	site += "      <br>";
	site += "      <input value='" + String(getTimelapsePanSteps()) + "' type='number' step='0.001' min='-5000' max='5000' id='pan'> " + (getPanStepper()->getPhysicalValueUnit()) + "";
	site += "      <button class='set_button' onclick='makeRequest(\"timelapse_pan=\" + document.getElementById(\"pan\").value);'>Set Pan</button>";
	site += "      <br>";
	site += "      <input value='" + String(getTimelapseSlideSteps()) + "' type='number' step='0.001' min='-5000' max='5000' id='slide'> " + (getSlideStepper()->getPhysicalValueUnit()) + "";
	site += "      <button class='set_button' onclick='makeRequest(\"timelapse_slide=\" + document.getElementById(\"slide\").value);'>Set Slide</button>";
	site += "      <br>";
	site += "      <input value='" + String(getTimelapsePictureCount()) + "' min='0' max='5000' id='count'> #";
	site += "      <button class='set_button' onclick='makeRequest(\"timelapse_count=\" + document.getElementById(\"count\").value);'>Set Picture count</button>";
	site += "      <br>";
	site += "      <input value='" + String(getIOBoard()->getCameraExposureTime()) + "' min='0' max='500' id='photo'> s";
	site += "      <button class='set_button' onclick='makeRequest(\"timelapse_photo=\" + document.getElementById(\"photo\").value);'>Set Photo Interval</button>";
	site += "      <br>";
	site += "      <input value='" + String(getTimelapseInterval()) + "' min='0' max='500' id='interval'> s";
	site += "      <button class='set_button' onclick='makeRequest(\"timelapse_interval=\" + document.getElementById(\"interval\").value);'>Set Timelapse interval</button>";
	site += "      <br>";
	site += "      <br>";
	site += "      <button class='block' onclick='makeRequest(\"timelapse_slide=\" + document.getElementById(\"slide\").value + \"&timelapse_count=\" + document.getElementById(\"count\").value + \"&timelapse_photo=\" + document.getElementById(\"photo\").value + \"&timelapse_interval=\" + document.getElementById(\"interval\").value + \"&timelapse_pan=\" + document.getElementById(\"pan\").value);'>Set all</button>";
	site += "      <br>";
	site += "    </div>";
	site += "";
	site += "    <br><br>";
	site += "";
	site += "    <div class='section'>";
	site += "      <h2>Timelapse-Info</h2>";
	site += "";
	site += "      <br>";
	site += "      <p>Total time: <i>" + secondsToString(getTimelapseTotalTime()) + "</i></p>";
	site += "      <p>Total slide: <i>" + String(getTimelapseTotalSlideDistance()) + "</i> " + (getSlideStepper()->getPhysicalValueUnit()) + "</p>";
	site += "      <p>Total pan: <i>" + String(getTimelapseTotalPanDistance()) + "</i> " + (getPanStepper()->getPhysicalValueUnit()) + "</p>";
	site += "      <br>";
	site += "      <p>Video length (24fps): <i>" + secondsToString(getTimelapseVideoTimePrediction(24)) + "</i></p>";
	site += "      <p>Video length (25fps): <i>" + secondsToString(getTimelapseVideoTimePrediction(25)) + "</i></p>";
	site += "      <p>Video length (30fps): <i>" + secondsToString(getTimelapseVideoTimePrediction(30)) + "</i></p>";
	site += "      <p>Video length (60fps): <i>" + secondsToString(getTimelapseVideoTimePrediction(60)) + "</i></p>";
	site += "      <br>";
	site += "    </div>";
	site += "  </div>";
	site += "";
	site += "  <br>";
	site += "  <br>";
	site += "";
	site += "  <a style='text-align: center; display: block;' href='about'>About</a>";
	site += "";
	site += "  <br>";
	site += "  <br>";
	site += "</body>";
	site += "</html>";

	return site;
}

String getSliderdetailPage() {
	String site = "<!doctype html>";
	site += "";
	site += "<html lang='en'>";
	site += "";
	site += "";
	site += "            <head>";
	site += "            <meta charset='utf-8'>";
	site += "";
	site += "            <meta charset='utf-8'>";
	site += "            <meta name='viewport' content='width=device-width, initial-scale=1.0'>";
	site += "";
	site += "            <title>Slide and Pan</title>";
	site += "            <meta name='description' content='Slide and Pan'>";
	site += "            <meta name='author' content='Sebastian Knoll'>";
	site += "";
	site += "            <link rel='stylesheet' href='main.css'>";
	site += "            <script src='main.js'></script>";
	site += "";
	site += "            </head>";
	site += "          ";
	site += "";
	site += "<body>";
	site += "  ";
	site += "";
	site += "  ";
	site += "";
	site += "  <div id='container'>";
	site += "    <h1>Slider in detail</h1>";
	site += "";
	site += "    <ul>";
	site += "      <li><a href='index'>Control</a></li>";
	site += "      <li><a href='timelapse'>Timelapse</a></li>";
	site += "      <li><a href='settings'>Settings</a></li>";
	site += "    </ul>";
	site += "";
	site += "    ";
	site += "<div id=\"slider-info\">";
	site += "  <p id=\"info\">&#128677; Current State</p>";
	site += "  <h1 class=\"insertSTATE\">" + getSliderStateString() + "</h1>";
	site += "  <p class=\"insertSTATEDETAIL\">" + getSliderSubStateString() + "</p>";
	site += "  <button class=\"block\" onclick='makeRequest(\"timelapse_stop&slide_stop&pan_stop\");'>Stop</button>";
	site += "</div>";
	site += "<script> startStreamListener(); </script>";
	site += "";
	site += "";
	site += "    <br>";
	site += "";
	site += "    <div class='section'>";
	site += "      <h2>&#128212; Slider Inforamtion</h2>";
	site += "      <br>";
	site += "      <p>Name: <i>" + String(SLIDEANDPAN_NAME) + "</i></p>";
	site += "      <p>Version: <i>" + String(SLIDEANDPAN_VERSION) + "</i></p>";
	site += "      <p>Copyright: <i>" + String(SLIDEANDPAN_COPYRIGHT) + "</i></p>";
	site += "      <p>ID: <i>" + String(SLIDEANDPAN_ID) + "</i></p>";
	site += "      <br>";
	site += "      <p>Note: <i>" + String(SLIDEANDPAN_ID_INFO) + "</i></p>";
	site += "      <p>Ver.-Info: <i>" + String(SLIDEANDPAN_VERSION_INFO) + "</i></p>";
	site += "      <br>";
	site += "    </div>";
	site += "";
	site += "    <br><br>";
	site += "";
	site += "    <div class='section'>";
	site += "      <h2>&#8596; Hardware - Slide</h2>";
	site += "      <br>";
	site += "      <p>Direction Pin: <i>" + String(SLIDE_STEPPER_PIN_DIRECTION) + "</i></p>";
	site += "      <p>Step Pin <i>" + String(SLIDE_STEPPER_PIN_STEP) + "</i></p>";
	site += "      <p>Sleep Pin <i>" + String(SLIDE_STEPPER_PIN_SLEEP) + "</i></p>";
	site += "      <p>Steps / Turn: <i>" + String(STEPPER_STEPS_PER_TURN) + "</i></p>";
	site += "      <p>Can change res.: <i>" + String(getSlideStepper()->hasChangeResolutionMethod() ? "Yes" : "No") + "</i></p>";
	site += "      <br>";
	site += "      <p>Driver M1 Pin <i>" + String(SLIDE_STEPPER_DRIVER_M1) + "</i></p>";
	site += "      <p>Driver M2 Pin <i>" + String(SLIDE_STEPPER_DRIVER_M2) + "</i></p>";
	site += "      <p>Driver M3 Pin <i>" + String(SLIDE_STEPPER_DRIVER_M3) + "</i></p>";
	site += "      <br>";
	site += "    </div>";
	site += "";
	site += "    <br><br>";
	site += "";
	site += "    <div class='section'>";
	site += "      <h2>&#8618; Hardware - Pan</h2>";
	site += "      <br>";
	site += "      <p>Direction Pin: <i>" + String(PAN_STEPPER_PIN_DIRECTION) + "</i></p>";
	site += "      <p>Step Pin <i>" + String(PAN_STEPPER_PIN_STEP) + "</i></p>";
	site += "      <p>Sleep Pin <i>" + String(PAN_STEPPER_PIN_SLEEP) + "</i></p>";
	site += "      <p>Steps / Turn: <i>" + String(STEPPER_STEPS_PER_TURN) + "</i></p>";
	site += "      <p>Can change res.: <i>" + String(getPanStepper()->hasChangeResolutionMethod() ? "Yes" : "No") + "</i></p>";
	site += "      <br>";
	site += "      <p>Driver M1 Pin <i>" + String(PAN_STEPPER_DRIVER_M1) + "</i></p>";
	site += "      <p>Driver M2 Pin <i>" + String(PAN_STEPPER_DRIVER_M2) + "</i></p>";
	site += "      <p>Driver M3 Pin <i>" + String(PAN_STEPPER_DRIVER_M3) + "</i></p>";
	site += "      <br>";
	site += "    </div>";
	site += "";
	site += "    <br><br>";
	site += "";
	site += "    <div class='section'>";
	site += "      <h2>&#128678; IO Board</h2>";
	site += "      <br>";
	site += "      <p>Latch Pin: <i>" + String(PIN_LATCH) + "</i></p>";
	site += "      <p>Clock Pin: <i>" + String(PIN_CLOCK) + "</i></p>";
	site += "      <p>DataOut Pin: <i>" + String(PIN_DATAOUT) + "</i></p>";
	site += "      <p>DataIn Pin: <i>" + String(PIN_DATAIN) + "</i></p>";
	site += "      <p>LatchIn Pin: <i>" + String(PIN_LATCHIN) + "</i></p>";
	site += "      <br>";
	site += "      <p>Enc. CLK Pin: <i>" + String(ENCODER_PIN_CLK) + "</i></p>";
	site += "      <p>Enc. DIR Pin: <i>" + String(ENCODER_PIN_DIRECTION) + "</i></p>";
	site += "      <p>Enc. Switch Pin: <i>" + String(ENCODER_PIN_SWITCH) + "</i></p>";
	site += "      <br>";
	site += "      <p>Battery AI Pin: <i>" + String(PIN_BATTERY) + "</i></p>";
	site += "      <br>";
	site += "    </div>";
	site += "";
	site += "    <br><br>";
	site += "";
	site += "    <div class='section'>";
	site += "      <h2>&#128209; Constants</h2>";
	site += "      <br>";
	site += "      <p>Gear diameter: <i>" + String(SLIDE_GEAR_DIAMETER) + "</i></p>";
	site += "      <p>Gear cog number: <i>" + String(PAN_GEAR_SMALL_COG_NUMBER) + "</i></p>";
	site += "      <p>Big gear cog number: <i>" + String(PAN_GEAR_LARGE_COG_NUMBER) + "</i></p>";
	site += "      <p>Earth rotation: <i>" + secondsToString(EARTH_SECONDS_PER_DAY) + "</i></p>";
	site += "      <p>Moon rotation: <i>" + secondsToString(MOON_SECONDS_PER_TURN) + "</i></p>";
	site += "      ";
	site += "      <br>";
	site += "    </div>";
	site += "";
	site += "    <br><br>";
	site += "";
	site += "    <div class='section'>";
	site += "      <h2>&#128198; Time</h2>";
	site += "      <br>";
	site += "      <p>Slider Time: <i>" + secondsToTimeString(getTime()) + "</i></p>";
	site += "      <br>";
	site += "      <button class='block' onclick='makeRequest(\"\");'>Set time</button>";
	site += "      <br>";
	site += "    </div>";
	site += "  </div>";
	site += "";
	site += "";
	site += "  <br><br><br><br>";
	site += "  <br><br><br><br>";
	site += "";
	site += "  ";
	site += "</body>";
	site += "</html>";

	return site;
}

String getMaincssPage() {
	String site = "* {";
	site += "  font-family:courier,arial,helvetica;";
	site += "}";
	site += "";
	site += "body {";
	site += "  background-color: rgb(180, 180, 180);";
	site += "}";
	site += "";
	site += "li {";
	site += "  display:inline-block;";
	site += "  margin: 5px;";
	site += "}";
	site += "";
	site += "ul {";
	site += "  margin: 0 auto;";
	site += "  display: inherit;";
	site += "}";
	site += "";
	site += "h1, h2, h3 {";
	site += "  text-align: center;";
	site += "}";
	site += "";
	site += "#container {";
	site += "  width: 100%;";
	site += "  max-width: 960px;";
	site += "  margin: 0 auto;";
	site += "}";
	site += "";
	site += ".section {";
	site += "";
	site += "  background: whitesmoke;";
	site += "  border-radius: 20px;";
	site += "";
	site += "  padding: 20px;";
	site += "}";
	site += "";
	site += "input {";
	site += "  width: 50px;";
	site += "}";
	site += "";
	site += ".set_button {";
	site += "  width: 200px;";
	site += "}";
	site += "";
	site += ".block {";
	site += "  display: block;";
	site += "  width: 100%;";
	site += "  height: 50px;;";
	site += "}";
	site += "";
	site += "#slider-info {";
	site += "  position: fixed;";
	site += "  bottom: 0;";
	site += "  left: 0;";
	site += "  right: 0;";
	site += "  width: 100%;";
	site += "  height: 60px;";
	site += "";
	site += "  text-align: left;";
	site += "";
	site += "  background-color: rgb(180, 180, 180);";
	site += "";
	site += "  box-shadow: 1px -3px 57px -4px rgba(0,0,0,0.81);";
	site += "  -webkit-box-shadow: 1px -3px 57px -4px rgba(0,0,0,0.81);";
	site += "  -moz-box-shadow: 1px -3px 57px -4px rgba(0,0,0,0.81);";
	site += "";
	site += "  border-top: solid black 1px;";
	site += "";
	site += "  transition: all ease .3s;";
	site += "}";
	site += "";
	site += "#slider-info:active, #slider-info:hover {";
	site += "  height: 100px;";
	site += "}";
	site += "";
	site += "#slider-info #info {";
	site += "  font-size: .8em;";
	site += "  margin: 5px;";
	site += "}";
	site += "";
	site += "#slider-info h1, p {";
	site += "  text-align: left;";
	site += "  margin: 5px 20px;";
	site += "}";
	site += "";
	site += "#slider-info button {";
	site += "  position: absolute;";
	site += "  right: 10px;";
	site += "  top: 10px;";
	site += "  height: 40px;";
	site += "  width: 20%;";
	site += "}";

	return site;
}

String getMainjsPage() {
	String site = "function makeRequest(command) {";
	site += "  var url = \"/device/command/?\" + command;";
	site += "  ";
	site += "  var request = new XMLHttpRequest();";
	site += "";
	site += "  request.onreadystatechange = function() {";
	site += "    if (this.readyState == 4 && this.status == 200) {";
	site += "      location.reload();";
	site += "    }";
	site += "  };";
	site += "";
	site += "  request.open(\"GET\",url);";
	site += "  request.send();";
	site += "}";
	site += "";
	site += "function getDaytimeInSeconds() {";
	site += "  let now = new Date();";
	site += "  return now.getSeconds() + 60 * now.getMinutes() + 60*60* now.getHours(); ";
	site += "}";
	site += "";
	site += "var updateTimeRequest = new XMLHttpRequest();";
	site += "updateTimeRequest.open(\"GET\", \"/device/command/?set_time=\" + getDaytimeInSeconds());";
	site += "updateTimeRequest.send();";
	site += "";
	site += "";
	site += "";
	site += "var streamData = null;";
	site += "function startStreamListener() {";
	site += "  var $event_source_name = new EventSource(\"./device/stream/\");";
	site += "";
	site += "  $event_source_name.addEventListener(\"event\", function(e) { ";
	site += "    var result = JSON.parse( e.data );";
	site += "    ";
	site += "    if(e.lastEventId == \"CLOSE\") { console.log('Closed stream'); }";
	site += "    else { ";
	site += "      streamData = result;";
	site += "      updateGUIFromStramData();";
	site += "    }";
	site += "";
	site += "  });";
	site += "";
	site += "  $event_source_name.addEventListener(\"error\", function(e) { $event_source_name.close(); });";
	site += "}";
	site += "";
	site += "classPathMap = {";
	site += "  'insertSTATE': (data) => data['state']['state'],";
	site += "  'insertSTATEDETAIL': (data) => data['state']['detail'],";
	site += "  'insertSLIDEPOS': (data) => data['slide']['Position'],";
	site += "  'insertSLIDEDIR': (data) => data['slide']['Direction'],";
	site += "  'insertSLIDESLEEP': (data) => data['slide']['Sleeping'],";
	site += "  'insertPANPOS': (data) => data['pan']['Position'],";
	site += "  'insertPANDIR': (data) => data['pan']['Direction'],";
	site += "  'insertPANSLEEP': (data) => data['pan']['Sleeping'],";
	site += "};";
	site += "";
	site += "function updateGUIFromStramData() {";
	site += "  if(!streamData) return;";
	site += "";
	site += "  for (var classOI in classPathMap) {";
	site += "    if (classPathMap.hasOwnProperty(classOI)) {      ";
	site += "      var elements = document.getElementsByClassName(classOI);";
	site += "";
	site += "      for (var index = 0; index < elements.length; index++) {";
	site += "        try {";
	site += "          elements[index].innerHTML = classPathMap[classOI](streamData);";
	site += "        } catch (error) {";
	site += "          ";
	site += "        }";
	site += "        ";
	site += "      }";
	site += "    }";
	site += "  }";
	site += "}";
	site += "";

	return site;
}

#endif