
#ifndef HTML_APPFILES_H
#define HTML_APPFILES_H

#include "common.h"
#include "io.h"
#include "stepper.h"
#include "debug.h"
    

void MainjsAppPageHandler(ESP8266WebServer& server) {
	server.sendContent("optionPageMap = {");
	server.sendContent("  1: './control.html',");
	server.sendContent("  2: './timelapse.html',");
	server.sendContent("  3: './milkyway.html',");
	server.sendContent("  4: './tracker.html',");
	server.sendContent("  5: './plan.html',");
	server.sendContent("  6: './info.html'");
	server.sendContent("};");
	server.sendContent("\n");
	server.sendContent("function select(optionNr) {");
	server.sendContent("\n");
	server.sendContent("  iframe = document.getElementById(\"iframe\");");
	server.sendContent("  iframe.src = optionPageMap[optionNr];");
	server.sendContent("\n");
	server.sendContent("  wheel = document.getElementById(\"select\");");
	server.sendContent("\n");
	server.sendContent("  [1, 2, 3, 4, 5, 6, 7, 8].forEach(element => {");
	server.sendContent("    wheel.classList.remove('option' + element);");
	server.sendContent("  });");
	server.sendContent("\n");
	server.sendContent("  wheel.classList.add('option' + optionNr);");
	server.sendContent("};");
	server.sendContent("\n");
	server.sendContent("function changeSpeed(sender) {");
	server.sendContent("  requestStrings = [");
	server.sendContent("    \"\",");
	server.sendContent("    \"slide_speed=0.05&pan_speed=0.05\",");
	server.sendContent("    \"slide_speed=0.25&pan_speed=0.5\",");
	server.sendContent("    \"slide_speed=0.5&pan_speed=1\",");
	server.sendContent("    \"slide_speed=1&pan_speed=2\"\n");
	server.sendContent("  ];");
	server.sendContent("\n");
	server.sendContent("  makeRequest(requestStrings[sender.value], false);");
	server.sendContent("  document.getElementById(\"speed-selection\").innerHTML = ([\"Zero\", \"Extremely Slow\", \"Slow\", \"Middle\", \"Fast\"])[sender.value];");
	server.sendContent("};");
	server.sendContent("\n");
	server.sendContent("function makeRequest(command, reload = false) {");
	server.sendContent("  var url = \"/device/command/?\" + command;");
	server.sendContent("  ");
	server.sendContent("  var request = new XMLHttpRequest();");
	server.sendContent("\n");
	server.sendContent("  request.onreadystatechange = function() {");
	server.sendContent("    if (this.readyState == 4 && this.status == 200) {");
	server.sendContent("      if(reload) location.reload();");
	server.sendContent("    }");
	server.sendContent("  };");
	server.sendContent("\n");
	server.sendContent("  request.open(\"GET\",url);");
	server.sendContent("  request.send();");
	server.sendContent("};");
	server.sendContent("\n");
	server.sendContent("function getDaytimeInSeconds() {");
	server.sendContent("  let now = new Date();");
	server.sendContent("  return now.getSeconds() + 60 * now.getMinutes() + 60*60* now.getHours(); ");
	server.sendContent("};");
	server.sendContent("\n");
	server.sendContent("var streamData = null;");
	server.sendContent("function startStreamListener() {");
	server.sendContent("  var $event_source_name = new EventSource('../device/stream/');");
	server.sendContent("\n");
	server.sendContent("  $event_source_name.addEventListener('event', function(e) { ");
	server.sendContent("  var result = JSON.parse( e.data );");
	server.sendContent("  ");
	server.sendContent("  if(e.lastEventId == 'CLOSE') { console.log(\"Closed stream\"); }");
	server.sendContent("  else { ");
	server.sendContent("    streamData = result;");
	server.sendContent("    updateGUIFromStramData();");
	server.sendContent("  }");
	server.sendContent("\n");
	server.sendContent("  });");
	server.sendContent("\n");
	server.sendContent("  $event_source_name.addEventListener('error', function(e) { $event_source_name.close(); });");
	server.sendContent("}");
	server.sendContent("\n");
	server.sendContent("classPathMap = {");
	server.sendContent("  \"insertSTATE\": (data) => data[\"state\"][\"state\"],");
	server.sendContent("  \"insertSTATEDETAIL\": (data) => data[\"state\"][\"detail\"],");
	server.sendContent("  \"insertSLIDEPOS\": (data) => data[\"slide\"][\"Position\"],");
	server.sendContent("  \"insertSLIDEDIR\": (data) => data[\"slide\"][\"Direction\"],");
	server.sendContent("  \"insertSLIDESLEEP\": (data) => data[\"slide\"][\"Sleeping\"],");
	server.sendContent("  \"insertPANPOS\": (data) => data[\"pan\"][\"Position\"],");
	server.sendContent("  \"insertPANDIR\": (data) => data[\"pan\"][\"Direction\"],");
	server.sendContent("  \"insertPANSLEEP\": (data) => data[\"pan\"][\"Sleeping\"],");
	server.sendContent("};");
	server.sendContent("\n");
	server.sendContent("function updateGUIFromStramData() {");
	server.sendContent("  if(!streamData) return;");
	server.sendContent("\n");
	server.sendContent("  heartBeat();");
	server.sendContent("  updateBattery(streamData['battery']);");
	server.sendContent("\n");
	server.sendContent("  for (var classOI in classPathMap) {");
	server.sendContent("    if (classPathMap.hasOwnProperty(classOI)) {   ");
	server.sendContent("      updateGUIValue(classOI, classPathMap[classOI](streamData));");
	server.sendContent("    }");
	server.sendContent("  }");
	server.sendContent("}");
	server.sendContent("\n");
	server.sendContent("function updateGUIValue(classOI, value) {");
	server.sendContent("\n");
	server.sendContent("  var elements = document.getElementsByClassName(classOI);");
	server.sendContent("\n");
	server.sendContent("  ifr = document.getElementById(\"iframe\");");
	server.sendContent("  var iFrameElements = ifr ");
	server.sendContent("    ? document.getElementById(\"iframe\").contentWindow.document.getElementsByClassName(classOI)");
	server.sendContent("    : [];");
	server.sendContent("\n");
	server.sendContent("  [elements, iFrameElements].forEach(list => {");
	server.sendContent("\n");
	server.sendContent("    for (var index = 0; index < list.length; index++) {");
	server.sendContent("      try {");
	server.sendContent("        list[index].innerHTML = value;");
	server.sendContent("      } catch (error) {");
	server.sendContent("        ");
	server.sendContent("      }");
	server.sendContent("    }");
	server.sendContent("  });");
	server.sendContent("}");
	server.sendContent("  ");
	server.sendContent("function updateBattery(batteryData) {");
	server.sendContent("  let batEl = document.querySelector('#battery-fill');");
	server.sendContent("\n");
	server.sendContent("  try {");
	server.sendContent("    let level = batteryData['level'];");
	server.sendContent("    let full = batteryData['full'];");
	server.sendContent("    let middle = batteryData['middle'];");
	server.sendContent("    let empty = batteryData['empty'];");
	server.sendContent("    let critical = batteryData['critical'];");
	server.sendContent("\n");
	server.sendContent("    batEl.style.width = Math.max(10, Math.min(100, (level-critical)/(full-critical)*100)) + '%';");
	server.sendContent("  ");
	server.sendContent("    batEl.style.backgroundColor = 'forestgreen';");
	server.sendContent("    if(level <= middle) batEl.style.backgroundColor = '#F4AF00';");
	server.sendContent("    if(level <= empty) batEl.style.backgroundColor = '#cc0000';");
	server.sendContent("    if(level <= critical) batEl.style.backgroundColor = 'red';");
	server.sendContent("\n");
	server.sendContent("  } catch (error) {");
	server.sendContent("    batEl.style.width = '50%';");
	server.sendContent("    batEl.style.backgroundColor = 'blue';");
	server.sendContent("  }");
	server.sendContent("}");
	server.sendContent("\n");
	server.sendContent("var heartBeatCount = 0;");
	server.sendContent("function heartBeat() {");
	server.sendContent("  heartBeatCount = 6;");
	server.sendContent("  setConnection(true);");
	server.sendContent("  setInnerConnection(true);");
	server.sendContent("}");
	server.sendContent("\n");
	server.sendContent("function setConnection(visible) {");
	server.sendContent("  try {");
	server.sendContent("    document.querySelector('#connection').style.display = visible ? \"unset\" : \"none\";");
	server.sendContent("  } catch (error) { }");
	server.sendContent("}");
	server.sendContent("\n");
	server.sendContent("function setInnerConnection(antenne) {");
	server.sendContent("  try {");
	server.sendContent("    document.querySelector('#connection').innerHTML = antenne ? \"&#128225;\" : \"&#10060;\";");
	server.sendContent("  } catch (error) { }");
	server.sendContent("}");
	server.sendContent("\n");
	server.sendContent("setInterval(function() {");
	server.sendContent("  heartBeatCount--;");
	server.sendContent("  if(heartBeatCount<=0) {");
	server.sendContent("    streamData = null;");
	server.sendContent("\n");
	server.sendContent("    if(heartBeatCount >= -10) {");
	server.sendContent("      setConnection(heartBeatCount % 2);");
	server.sendContent("    ");
	server.sendContent("      dotString = '...'.substr(0, Math.abs(heartBeatCount % 4));");
	server.sendContent("      updateGUIValue('insertSTATE', 'Wait for Slider' + dotString);");
	server.sendContent("      updateGUIValue('insertSTATEDETAIL', 'Maybe we lost the connection :0');");
	server.sendContent("    }");
	server.sendContent("    else {");
	server.sendContent("      setInnerConnection(false);");
	server.sendContent("      setConnection(true);");
	server.sendContent("      updateGUIValue('insertSTATE', 'No Connection!');");
	server.sendContent("      updateGUIValue('insertSTATEDETAIL', 'Please try to reconnect.');");
	server.sendContent("    }");
	server.sendContent("  }");
	server.sendContent("}, 500);");
	server.sendContent("\n");
	server.sendContent("\n");
	server.sendContent("var updateTimeRequest = new XMLHttpRequest();");
	server.sendContent("updateTimeRequest.open(\"GET\", \"../device/command/?set_time=\" + getDaytimeInSeconds());");
	server.sendContent("updateTimeRequest.send();");
}

void MilkywayAppPageHandler(ESP8266WebServer& server) {
	server.sendContent("<!DOCTYPE html>");
	server.sendContent("<html lang='en'>");
	server.sendContent("<head>");
	server.sendContent("  <meta charset='UTF-8'>");
	server.sendContent("  <meta name='viewport' content='width=device-width, initial-scale=1.0'>");
	server.sendContent("  <title>Milkyway</title>");
	server.sendContent("\n");
	server.sendContent("  <link rel='stylesheet' href='definesCss.css'>");
	server.sendContent("  <link rel='stylesheet' href='mainCss.css'>");
	server.sendContent("  <link rel='stylesheet' href='mainCss2.css'>");
	server.sendContent("\n");
	server.sendContent("  <script src='mainJs.js'></script>");
	server.sendContent("</head>");
	server.sendContent("<body>");
	server.sendContent("  <div class='content'>");
	server.sendContent("    <div class='vspace'></div>");
	server.sendContent("    <h1>&#127775; Milkyway</h1>");
	server.sendContent("    <div class='option-container'>");
	server.sendContent("      ");
	server.sendContent("      <p>Photos:</p>");
	server.sendContent("      <input>");
	server.sendContent("      <p class='small'>#</p>");
	server.sendContent("\n");
	server.sendContent("      <p>Slide:</p>");
	server.sendContent("      <input>");
	server.sendContent("      <p class='small'>mm / Step</p>");
	server.sendContent("\n");
	server.sendContent("      <p>Photo interval:</p>");
	server.sendContent("      <input>");
	server.sendContent("      <p class='small'>s / Photo</p>");
	server.sendContent("\n");
	server.sendContent("      <p>Step time:</p>");
	server.sendContent("      <input>");
	server.sendContent("      <p class='small'>s / Step</p>");
	server.sendContent("    </div>");
	server.sendContent("\n");
	server.sendContent("    <div class='side-container'>");
	server.sendContent("      <div class='button main'>&#128640; Shoot Milkyway</div>");
	server.sendContent("      <div class='button main'>&#10060;</div>");
	server.sendContent("    </div>");
	server.sendContent("\n");
	server.sendContent("    <br><br>");
	server.sendContent("    <h1>&#127916; Info</h1>");
	server.sendContent("\n");
	server.sendContent("    <div class='option-container'>");
	server.sendContent("      ");
	server.sendContent("      <p>Total time:</p>");
	server.sendContent("      <p>213413241234 1234 1234 1234 2</p>");
	server.sendContent("      <p class='small'></p>");
	server.sendContent("\n");
	server.sendContent("      <p>End time:</p>");
	server.sendContent("      <p></p>");
	server.sendContent("      <p class='small'></p>");
	server.sendContent("\n");
	server.sendContent("      <p></p><p></p><p></p>");
	server.sendContent("\n");
	server.sendContent("      <p>Total Slide:</p>");
	server.sendContent("      <p></p>");
	server.sendContent("      <p class='small'></p>");
	server.sendContent("\n");
	server.sendContent("      <p>Total Pan:</p>");
	server.sendContent("      <p></p>");
	server.sendContent("      <p class='small'></p>      ");
	server.sendContent("      ");
	server.sendContent("      <p></p><p></p><p></p>");
	server.sendContent("\n");
	server.sendContent("      <p>Video (24fps):</p>");
	server.sendContent("      <p></p>");
	server.sendContent("      <p class='small'></p>");
	server.sendContent("      <p>Video (25fps):</p>");
	server.sendContent("      <p></p>");
	server.sendContent("      <p class='small'></p>");
	server.sendContent("      <p>Video (30fps):</p>");
	server.sendContent("      <p></p>");
	server.sendContent("      <p class='small'></p>");
	server.sendContent("      <p>Video (60fps):</p>");
	server.sendContent("      <p></p>");
	server.sendContent("      <p class='small'></p>");
	server.sendContent("    </div>");
	server.sendContent("\n");
	server.sendContent("    <div class='closer'></div>");
	server.sendContent("  </div>");
	server.sendContent("</body>");
	server.sendContent("</html>");
}

void IndexAppPageHandler(ESP8266WebServer& server) {
	server.sendContent("<!DOCTYPE html>");
	server.sendContent("<html lang='en'>");
	server.sendContent("<head style='overflow: hidden;'>");
	server.sendContent("  <meta charset='UTF-8'>");
	server.sendContent("  <meta name='viewport' content='width=device-width, initial-scale=1.0'>");
	server.sendContent("  <title>Slide and Pan</title>");
	server.sendContent("\n");
	server.sendContent("  <link rel='stylesheet' href='definesCss.css'>");
	server.sendContent("  <link rel='stylesheet' href='mainCss.css'>");
	server.sendContent("  <link rel='stylesheet' href='mainCss2.css'>");
	server.sendContent("\n");
	server.sendContent("  <script src='mainJs.js'></script>");
	server.sendContent("</head>");
	server.sendContent("<body style='overflow: hidden;'>");
	server.sendContent("  <div id='status-bar'>");
	server.sendContent("    <div id='battery'>");
	server.sendContent("      <div id='battery-plus-pole'></div>");
	server.sendContent("      <div id='battery-fill'></div>");
	server.sendContent("      <div id='battery-glas'></div>");
	server.sendContent("    </div>");
	server.sendContent("\n");
	server.sendContent("    <div class='status left'>");
	server.sendContent("      &#128678; <span class='insertSTATE' id='status' onclick='document.getElementById(\"status-bar-detail\").classList.toggle(\"open\");'></span>");
	server.sendContent("    </div>");
	server.sendContent("\n");
	server.sendContent("    <div id='e-stop' onclick='makeRequest(\"slide_stop&pan_stop\");'>");
	server.sendContent("      <p>E-STOP</p>");
	server.sendContent("    </div>");
	server.sendContent("\n");
	server.sendContent("    <div class='status right'>");
	server.sendContent("      <p><span id='connection'>&#128225;</span> &#128247; <span id='camera'>READY</span></p>");
	server.sendContent("    </div>");
	server.sendContent("  </div>");
	server.sendContent("\n");
	server.sendContent("  <div id='status-bar-detail'>");
	server.sendContent("    <h1 class='insertSTATE'></h1>");
	server.sendContent("    <p class='insertSTATEDETAIL'></p>");
	server.sendContent("    <br><br>");
	server.sendContent("    <hr>");
	server.sendContent("    <br>");
	server.sendContent("    <p style='text-align: center; font-size: 2em;'>");
	server.sendContent("      <span class='insertSLIDEPOS'>?</span>cm / ");
	server.sendContent("      <span class='insertPANPOS'>?</span>°");
	server.sendContent("    </p>");
	server.sendContent("    <br>");
	server.sendContent("    <div class='side-container'>");
	server.sendContent("      <div class='button main' onclick='makeRequest(\"slide_reset&pan_reset\");'>&#127919; Set as Home</div>");
	server.sendContent("      <div class='button main' onclick='makeRequest(\"pan_physical_value=0&slide_physical_value=0\");'>&#127969;</div>");
	server.sendContent("    </div>");
	server.sendContent("    <br><br>");
	server.sendContent("    <br><br>");
	server.sendContent("    <div class='section'>");
	server.sendContent("      <h3>Slide to:</h3>");
	server.sendContent("      <div class='side-container'>");
	server.sendContent("        <input type='number' value='" + (getSlideStepper()->getPhysicalValueInfo()) + "' step='0.001' min='-50000' max='50000' id='slide_pv'>");
	server.sendContent("        <div class='button main' onclick='makeRequest(\"slide_physical_value=\" + document.getElementById(\"slide_pv\").value);'>&#128681;</div>");
	server.sendContent("      </div>");
	server.sendContent("      <br>");
	server.sendContent("      <h3>Pan to:</h3>");
	server.sendContent("      <div class='side-container'>");
	server.sendContent("        <input type='number' value='" + (getPanStepper()->getPhysicalValueInfo()) + "' step='0.001' min='-50000' max='50000' id='pan_pv'>");
	server.sendContent("        <div class='button main' onclick='makeRequest(\"pan_physical_value=\" + document.getElementById(\"pan_pv\").value);'>&#128681;</div>");
	server.sendContent("      </div>");
	server.sendContent("    </div>");
	server.sendContent("\n");
	server.sendContent("    <div class='closer'></div>");
	server.sendContent("  </div>");
	server.sendContent("\n");
	server.sendContent("  <div id='select' class='select wheel'>");
	server.sendContent("    <div class='select option option1' onclick='select(1);'><p>&#127918;</p></div>");
	server.sendContent("    <div class='select option option2' onclick='select(2);'><p>&#9202;</p></div>");
	server.sendContent("    <div class='select option option3' onclick='select(3);'><p>&#127775;</p></div>");
	server.sendContent("    <div class='select option option4' onclick='select(4);'><p>&#128301;</p></div>");
	server.sendContent("    <div class='select option option5' onclick='select(5);'><p>&#128203;</p></div>");
	server.sendContent("    <div class='select option option6' onclick='select(6);'><p>&#128209;</p></div>");
	server.sendContent("  </div>");
	server.sendContent("\n");
	server.sendContent("\n");
	server.sendContent("  <iframe id='iframe' src='' frameBorder='0'></iframe>");
	server.sendContent("  <script>select(2); startStreamListener();</script>");
	server.sendContent("</body>");
	server.sendContent("</html>");
}

void TimelapseAppPageHandler(ESP8266WebServer& server) {
	server.sendContent("<!DOCTYPE html>");
	server.sendContent("<html lang='en'>");
	server.sendContent("<head>");
	server.sendContent("  <meta charset='UTF-8'>");
	server.sendContent("  <meta name='viewport' content='width=device-width, initial-scale=1.0'>");
	server.sendContent("  <title>Timelapse</title>");
	server.sendContent("\n");
	server.sendContent("  <link rel='stylesheet' href='definesCss.css'>");
	server.sendContent("  <link rel='stylesheet' href='mainCss.css'>");
	server.sendContent("  <link rel='stylesheet' href='mainCss2.css'>");
	server.sendContent("\n");
	server.sendContent("  <script src='mainJs.js'></script>");
	server.sendContent("</head>");
	server.sendContent("<body>");
	server.sendContent("  <div class='content'>");
	server.sendContent("    <div class='vspace'></div>");
	server.sendContent("    <h1>&#9202; Timelapse</h1>");
	server.sendContent("    <div class='option-container'>");
	server.sendContent("      ");
	server.sendContent("      <p>Photos:</p>");
	server.sendContent("      <input>");
	server.sendContent("      <p class='small'>#</p>");
	server.sendContent("\n");
	server.sendContent("      <p>Slide:</p>");
	server.sendContent("      <input>");
	server.sendContent("      <p class='small'>mm / Step</p>");
	server.sendContent("\n");
	server.sendContent("      <p>Pan:</p>");
	server.sendContent("      <input>");
	server.sendContent("      <p class='small'>° / Step</p>");
	server.sendContent("\n");
	server.sendContent("      <p>Photo interval:</p>");
	server.sendContent("      <input>");
	server.sendContent("      <p class='small'>s / Photo</p>");
	server.sendContent("\n");
	server.sendContent("      <p>Step time:</p>");
	server.sendContent("      <input>");
	server.sendContent("      <p class='small'>s / Step</p>");
	server.sendContent("    </div>");
	server.sendContent("\n");
	server.sendContent("    <div class='side-container'>");
	server.sendContent("      <div class='button main'>&#128640; Start Timelapse</div>");
	server.sendContent("      <div class='button main'>&#10060;</div>");
	server.sendContent("      <div class='button main'>&#129488; Preview</div>");
	server.sendContent("      <div class='button main'>&#10060;</div>");
	server.sendContent("    </div>");
	server.sendContent("\n");
	server.sendContent("    <br><br>");
	server.sendContent("    <h1>&#127916; Info</h1>");
	server.sendContent("\n");
	server.sendContent("    <div class='option-container'>");
	server.sendContent("      ");
	server.sendContent("      <p>Total time:</p>");
	server.sendContent("      <p>213413241234 1234 1234 1234 2</p>");
	server.sendContent("      <p class='small'></p>");
	server.sendContent("\n");
	server.sendContent("      <p>End time:</p>");
	server.sendContent("      <p></p>");
	server.sendContent("      <p class='small'></p>");
	server.sendContent("\n");
	server.sendContent("      <p></p><p></p><p></p>");
	server.sendContent("\n");
	server.sendContent("      <p>Total Slide:</p>");
	server.sendContent("      <p></p>");
	server.sendContent("      <p class='small'></p>");
	server.sendContent("\n");
	server.sendContent("      <p>Total Pan:</p>");
	server.sendContent("      <p></p>");
	server.sendContent("      <p class='small'></p>      ");
	server.sendContent("      ");
	server.sendContent("      <p></p><p></p><p></p>");
	server.sendContent("\n");
	server.sendContent("      <p>Video (24fps):</p>");
	server.sendContent("      <p></p>");
	server.sendContent("      <p class='small'></p>");
	server.sendContent("      <p>Video (25fps):</p>");
	server.sendContent("      <p></p>");
	server.sendContent("      <p class='small'></p>");
	server.sendContent("      <p>Video (30fps):</p>");
	server.sendContent("      <p></p>");
	server.sendContent("      <p class='small'></p>");
	server.sendContent("      <p>Video (60fps):</p>");
	server.sendContent("      <p></p>");
	server.sendContent("      <p class='small'></p>");
	server.sendContent("    </div>");
	server.sendContent("\n");
	server.sendContent("    <div class='closer'></div>");
	server.sendContent("  </div>");
	server.sendContent("</body>");
	server.sendContent("</html>");
}

void Maincss2AppPageHandler(ESP8266WebServer& server) {
	server.sendContent(".select.wheel.option1 {");
	server.sendContent("  transform: translate(-50%, var(--select-top-pos)) rotate(20deg);");
	server.sendContent("}");
	server.sendContent("\n");
	server.sendContent(".select.wheel.option2 {");
	server.sendContent("  transform: translate(-50%, var(--select-top-pos)) rotate(0deg);");
	server.sendContent("}");
	server.sendContent("\n");
	server.sendContent(".select.wheel.option3 {");
	server.sendContent("  transform: translate(-50%, var(--select-top-pos)) rotate(-20deg);");
	server.sendContent("}");
	server.sendContent("\n");
	server.sendContent(".select.wheel.option4 {");
	server.sendContent("  transform: translate(-50%, var(--select-top-pos)) rotate(-40deg);");
	server.sendContent("}");
	server.sendContent("\n");
	server.sendContent(".select.wheel.option5 {");
	server.sendContent("  transform: translate(-50%, var(--select-top-pos)) rotate(-60deg);");
	server.sendContent("}");
	server.sendContent("\n");
	server.sendContent("\n");
	server.sendContent(".select.wheel.option6 {");
	server.sendContent("  transform: translate(-50%, var(--select-top-pos)) rotate(-80deg);");
	server.sendContent("}");
	server.sendContent("\n");
	server.sendContent(".select.option {");
	server.sendContent("  width: 200vw;");
	server.sendContent("  height: 200vw;");
	server.sendContent("  min-width: 500px;");
	server.sendContent("  min-height: 500px;");
	server.sendContent("  max-width: 960px;");
	server.sendContent("  max-height: 960px;");
	server.sendContent("  ");
	server.sendContent("  color: var(--color-front1);");
	server.sendContent("  font-size: 2em;");
	server.sendContent("\n");
	server.sendContent("  background-color: transparent;");
	server.sendContent("  border: none;");
	server.sendContent("  position: fixed;");
	server.sendContent("\n");
	server.sendContent("  text-align: center;");
	server.sendContent("  padding-top: 10px;");
	server.sendContent("\n");
	server.sendContent("  pointer-events: none;");
	server.sendContent("}");
	server.sendContent("\n");
	server.sendContent(".select.option p {");
	server.sendContent("  pointer-events: all;");
	server.sendContent("  cursor: pointer;");
	server.sendContent("  display: inline-block;");
	server.sendContent("  padding: 5px;");
	server.sendContent("}");
	server.sendContent("\n");
	server.sendContent(".select.option p:hover {");
	server.sendContent("  color: var(--color-front2);");
	server.sendContent("}");
	server.sendContent("\n");
	server.sendContent(".select.option.option1 {");
	server.sendContent("  transform: rotate(-20deg);");
	server.sendContent("  z-index: 20;");
	server.sendContent("}");
	server.sendContent("\n");
	server.sendContent(".select.option.option2 {");
	server.sendContent("  transform: rotate(0deg);");
	server.sendContent("  z-index: 21;");
	server.sendContent("}");
	server.sendContent("\n");
	server.sendContent(".select.option.option3 {");
	server.sendContent("  transform: rotate(20deg);");
	server.sendContent("  z-index: 22;");
	server.sendContent("}");
	server.sendContent("\n");
	server.sendContent(".select.option.option4 {");
	server.sendContent("  transform: rotate(40deg);");
	server.sendContent("  z-index: 22;");
	server.sendContent("}");
	server.sendContent("\n");
	server.sendContent(".select.option.option5 {");
	server.sendContent("  transform: rotate(60deg);");
	server.sendContent("  z-index: 22;");
	server.sendContent("}");
	server.sendContent("\n");
	server.sendContent(".select.option.option6 {");
	server.sendContent("  transform: rotate(80deg);");
	server.sendContent("  z-index: 22;");
	server.sendContent("}");
	server.sendContent("\n");
	server.sendContent("iframe {");
	server.sendContent("  position: absolute;");
	server.sendContent("  top: 0;");
	server.sendContent("  left: 0;");
	server.sendContent("  width: 100%;");
	server.sendContent("  height: 100%;");
	server.sendContent("  z-index: 1;");
	server.sendContent("  margin-top: 30px;");
	server.sendContent("}");
	server.sendContent("\n");
	server.sendContent(".control-container {");
	server.sendContent("  display: grid;");
	server.sendContent("  grid-template-columns: 1fr 1fr 1fr;");
	server.sendContent("  grid-template-rows: 1fr 1fr 1fr;");
	server.sendContent("  gap: 10px 10px;");
	server.sendContent("\n");
	server.sendContent("  width: 80%;");
	server.sendContent("  margin: 50px auto;");
	server.sendContent("}");
	server.sendContent("\n");
	server.sendContent(".option-container {");
	server.sendContent("  display: grid;");
	server.sendContent("  grid-template-columns: 2fr 1fr 1fr;");
	server.sendContent("  gap: 5px 10px;");
	server.sendContent("\n");
	server.sendContent("  width: 80%;");
	server.sendContent("  margin: 50px auto;");
	server.sendContent("}");
	server.sendContent("\n");
	server.sendContent(".button {");
	server.sendContent("  display: inline-block;");
	server.sendContent("  text-align: center;");
	server.sendContent("  vertical-align: middle;");
	server.sendContent("  width: 100%;");
	server.sendContent("  height: 100%;");
	server.sendContent("  font-size: 3em;");
	server.sendContent("\n");
	server.sendContent("  cursor: pointer;");
	server.sendContent("\n");
	server.sendContent("  border-radius: 10px;");
	server.sendContent("  border: solid var(--color-background1) 2px;");
	server.sendContent("\n");
	server.sendContent("  transition: all .3s ease;");
	server.sendContent("}");
	server.sendContent("\n");
	server.sendContent(".button:hover, .button:active {");
	server.sendContent("  border: solid var(--color-front2) 2px;");
	server.sendContent("  background-color: var(--color-background3);");
	server.sendContent("  color: var(--color-front2);");
	server.sendContent("}");
	server.sendContent("\n");
	server.sendContent(".button.stop {");
	server.sendContent("  font-size: 1em;");
	server.sendContent("}");
	server.sendContent("\n");
	server.sendContent(".button p {");
	server.sendContent("  position: relative;");
	server.sendContent("  top: 70%;");
	server.sendContent("}");
	server.sendContent("\n");
	server.sendContent(".button.main {");
	server.sendContent("  width: 80%;");
	server.sendContent("  margin: 20px auto;");
	server.sendContent("  display: block;");
	server.sendContent("  font-size: 1.2em;");
	server.sendContent("  padding: 5px 0;");
	server.sendContent("}");
	server.sendContent("\n");
	server.sendContent("input {");
	server.sendContent("  display: inline-block;");
	server.sendContent("  text-align: center;");
	server.sendContent("  margin: auto;");
	server.sendContent("  width: 100%;");
	server.sendContent("  color: red;");
	server.sendContent("}");
	server.sendContent("\n");
	server.sendContent(".main-container {");
	server.sendContent("  width: 80%;");
	server.sendContent("  margin: 50px auto;");
	server.sendContent("}");
	server.sendContent("\n");
	server.sendContent(".main-container h2 {");
	server.sendContent("  text-align: center;");
	server.sendContent("  margin-bottom: 10px;");
	server.sendContent("}");
	server.sendContent("\n");
	server.sendContent(".side-container {");
	server.sendContent("  display: grid;");
	server.sendContent("  grid-template-columns: 4fr 1fr;");
	server.sendContent("  gap: 20px 10px;");
	server.sendContent("  width: 80%;");
	server.sendContent("  height: auto;");
	server.sendContent("  margin: auto;");
	server.sendContent("}");
	server.sendContent("\n");
	server.sendContent(".side-container .button {");
	server.sendContent("  margin: 0;");
	server.sendContent("  width: 100%;");
	server.sendContent("  display: inline-table");
	server.sendContent("}");
	server.sendContent("\n");
	server.sendContent(".small {");
	server.sendContent("  font-size: .75em;");
	server.sendContent("}");
	server.sendContent("\n");
	server.sendContent(".closer {");
	server.sendContent("  height: 200px;");
	server.sendContent("}");
	server.sendContent("\n");
	server.sendContent(".section {");
	server.sendContent("  text-align: text;");
	server.sendContent("  width: 80%;");
	server.sendContent("  margin: auto;");
	server.sendContent("}");
	server.sendContent("\n");
	server.sendContent(".section h1, h2, h3 {");
	server.sendContent("  text-align: center;");
	server.sendContent("}");
	server.sendContent("\n");
	server.sendContent("input {");
	server.sendContent("  text-align: left;");
	server.sendContent("  color: var(--color-background1);");
	server.sendContent("  background-color: var(--color-front1);");
	server.sendContent("  padding: 5px 10px;");
	server.sendContent("  ");
	server.sendContent("  border-radius: 10px;");
	server.sendContent("  border: solid var(--color-background1) 2px;");
	server.sendContent("  min-height: 25px;");
	server.sendContent("  width: 80%;");
	server.sendContent("}");
}

void InfoAppPageHandler(ESP8266WebServer& server) {
	server.sendContent("<!DOCTYPE html>");
	server.sendContent("<html lang='en'>");
	server.sendContent("<head>");
	server.sendContent("  <meta charset='UTF-8'>");
	server.sendContent("  <meta name='viewport' content='width=device-width, initial-scale=1.0'>");
	server.sendContent("  <title>Plan</title>");
	server.sendContent("\n");
	server.sendContent("  <link rel='stylesheet' href='definesCss.css'>");
	server.sendContent("  <link rel='stylesheet' href='mainCss.css'>");
	server.sendContent("  <link rel='stylesheet' href='mainCss2.css'>");
	server.sendContent("\n");
	server.sendContent("  <script src='mainJs.js'></script>");
	server.sendContent("</head>");
	server.sendContent("<body>");
	server.sendContent("  <div class='content'>");
	server.sendContent("    <div class='vspace'></div>");
	server.sendContent("    <h1>&#128209; Info</h1>");
	server.sendContent("    ");
	server.sendContent("    <br><br>");
	server.sendContent("\n");
	server.sendContent("    <div class='main-container'>");
	server.sendContent("       ");
	server.sendContent("      <h2>&#128640; Slider</h2>");
	server.sendContent("      <p>");
	server.sendContent("        TODO");
	server.sendContent("      </p>");
	server.sendContent("\n");
	server.sendContent("      <br><br>");
	server.sendContent("\n");
	server.sendContent("      <h2>&#128199; Author</h2>");
	server.sendContent("      <p>");
	server.sendContent("        TODO");
	server.sendContent("      </p>");
	server.sendContent("\n");
	server.sendContent("      <br><br>");
	server.sendContent("\n");
	server.sendContent("      ");
	server.sendContent("      <h2>&#127759; More</h2>");
	server.sendContent("      <p>");
	server.sendContent("        TODO");
	server.sendContent("      </p>");
	server.sendContent("\n");
	server.sendContent("      <br><br>");
	server.sendContent("\n");
	server.sendContent("      <h2>&#9874; Hardware</h2>");
	server.sendContent("      <p>");
	server.sendContent("        TODO");
	server.sendContent("      </p>");
	server.sendContent("\n");
	server.sendContent("      <br><br>");
	server.sendContent(" ");
	server.sendContent("      <h2>&#128655; Constants</h2>");
	server.sendContent("      <p>");
	server.sendContent("        TODO");
	server.sendContent("      </p>");
	server.sendContent("\n");
	server.sendContent("      <h2>&#128213; Logs</h2>");
	server.sendContent("      <div style='overflow-x: scroll; padding-bottom: 10px;'>");
	server.sendContent("        <p style='display: inline; white-space: nowrap; overflow-x: scroll;'>");
	server.sendContent("          " + getRingBufferForWeb() + "\n");
	server.sendContent("        </p>");
	server.sendContent("      </div>");
	server.sendContent("    </div>");
	server.sendContent("    ");
	server.sendContent("    <div class='closer'></div>");
	server.sendContent("  </div>");
	server.sendContent("</body>");
	server.sendContent("</html>");
}

void DefinescssAppPageHandler(ESP8266WebServer& server) {
	server.sendContent(":root {");
	server.sendContent("  --color-red: #cc0000;");
	server.sendContent("  --color-red2: #7a0000;");
	server.sendContent("  --color-yellow: #F4AF00;");
	server.sendContent("  --color-green: forestgreen;");
	server.sendContent("  ");
	server.sendContent("  --color-light-gray: #C7C7C7;");
	server.sendContent("  --color-gray: #7E7E7E;");
	server.sendContent("  --color-dark-gray: #4A4A4A;");
	server.sendContent("  ");
	server.sendContent("  --color-light-white: #F9F9F9;");
	server.sendContent("  --color-white: #FAF9F6;");
	server.sendContent("  --color-dark-white: #F2F2F2; ");
	server.sendContent("  ");
	server.sendContent("  --color-first: #0B0C10;");
	server.sendContent("  --color-second: #1F2833;");
	server.sendContent("  --color-third: #C5C6C7;");
	server.sendContent("  --color-fourth: #66FCF1;");
	server.sendContent("  --color-fifth: #286090;");
	server.sendContent("\n");
	server.sendContent("  --color-background1: #111111;");
	server.sendContent("  --color-background2: #353535;");
	server.sendContent("  --color-background3: #505050;");
	server.sendContent("  --color-front1: #F2F2F2;");
	server.sendContent("  --color-front2: tomato;");
	server.sendContent("  ");
	server.sendContent("  --web-std-width: 960px;");
	server.sendContent("  --select-top-pos: 75vh;");
	server.sendContent("}");
}

void ControlAppPageHandler(ESP8266WebServer& server) {
	server.sendContent("<!DOCTYPE html>");
	server.sendContent("<html lang='en'>");
	server.sendContent("<head>");
	server.sendContent("  <meta charset='UTF-8'>");
	server.sendContent("  <meta name='viewport' content='width=device-width, initial-scale=1.0'>");
	server.sendContent("  <title>Control</title>");
	server.sendContent("\n");
	server.sendContent("  <link rel='stylesheet' href='definesCss.css'>");
	server.sendContent("  <link rel='stylesheet' href='mainCss.css'>");
	server.sendContent("  <link rel='stylesheet' href='mainCss2.css'>");
	server.sendContent("\n");
	server.sendContent("  <script src='mainJs.js'></script>");
	server.sendContent("</head>");
	server.sendContent("<body>");
	server.sendContent("  <div class='content'>");
	server.sendContent("    <div class='vspace'></div>");
	server.sendContent("    <h1>&#127918; Control</h1>");
	server.sendContent("    <p style='text-align: center; font-size: .7em;'>");
	server.sendContent("      <span class='insertSLIDEPOS'>?</span>cm / ");
	server.sendContent("      <span class='insertPANPOS'>?</span>°</p>");
	server.sendContent("    <div class='control-container'>");
	server.sendContent("      <div></div>");
	server.sendContent("      <div><div class='button' onclick='makeRequest(\"slide_to=1000000\");'>&#11014;</div></div>");
	server.sendContent("      <div></div>");
	server.sendContent("\n");
	server.sendContent("      <div><div class='button' onclick='makeRequest(\"pan_to=1000000\");'>&#8618;</div></div>");
	server.sendContent("      <div><div class='button stop' onclick='makeRequest(\"slide_stop&pan_stop\");'><p>STOP</p></div></div>");
	server.sendContent("      <div><div class='button' onclick='makeRequest(\"pan_to=-1000000\");'>&#8617;</div></div>");
	server.sendContent("\n");
	server.sendContent("      <div></div>");
	server.sendContent("      <div><div class='button' onclick='makeRequest(\"slide_to=-1000000\");'>&#11015;</div></div>");
	server.sendContent("      <div></div>");
	server.sendContent("    </div>");
	server.sendContent("\n");
	server.sendContent("    <div class='main-container'>");
	server.sendContent("      <h3>&#128640; Speed</h3>");
	server.sendContent("      <p style='text-align: center;' id='speed-selection'>Fast</p>");
	server.sendContent("      <input type='range' min='1' max='4' value='2' class='slider' id='myRange' ");
	server.sendContent("          onchange='changeSpeed(this);'>");
	server.sendContent("\n");
	server.sendContent("      <br><br>");
	server.sendContent("      <br><br>");
	server.sendContent("      <h3>&#128268; Stepper Power</h3>");
	server.sendContent("      <br><br>");
	server.sendContent("      <div class='side-container'>");
	server.sendContent("        <div class='button main' onclick='makeRequest(\"slide_sleep=0&pan_sleep=0\");'>&#9889; Power On</div>");
	server.sendContent("        <div class='button main' onclick='makeRequest(\"slide_sleep=0&pan_sleep=0\");'>OFF</div>");
	server.sendContent("      </div>");
	server.sendContent("    </div>");
	server.sendContent("\n");
	server.sendContent("  ");
	server.sendContent("    ");
	server.sendContent("  </div>");
	server.sendContent("  ");
	server.sendContent("  <div class='closer'></div>");
	server.sendContent("</body>");
	server.sendContent("</html>");
}

void PlanAppPageHandler(ESP8266WebServer& server) {
	server.sendContent("<!DOCTYPE html>");
	server.sendContent("<html lang='en'>");
	server.sendContent("<head>");
	server.sendContent("  <meta charset='UTF-8'>");
	server.sendContent("  <meta name='viewport' content='width=device-width, initial-scale=1.0'>");
	server.sendContent("  <title>Plan</title>");
	server.sendContent("\n");
	server.sendContent("  <link rel='stylesheet' href='definesCss.css'>");
	server.sendContent("  <link rel='stylesheet' href='mainCss.css'>");
	server.sendContent("  <link rel='stylesheet' href='mainCss2.css'>");
	server.sendContent("\n");
	server.sendContent("  <script src='mainJs.js'></script>");
	server.sendContent("</head>");
	server.sendContent("<body>");
	server.sendContent("  <div class='content'>");
	server.sendContent("    <div class='vspace'></div>");
	server.sendContent("    <h1>&#128203; Plan</h1>");
	server.sendContent("    ");
	server.sendContent("    <p>");
	server.sendContent("      TODO");
	server.sendContent("    </p>");
	server.sendContent("\n");
	server.sendContent("    <br><br>");
	server.sendContent("\n");
	server.sendContent("  </div>");
	server.sendContent("</body>");
	server.sendContent("</html>");
}

void TrackerAppPageHandler(ESP8266WebServer& server) {
	server.sendContent("<!DOCTYPE html>");
	server.sendContent("<html lang='en'>");
	server.sendContent("<head>");
	server.sendContent("  <meta charset='UTF-8'>");
	server.sendContent("  <meta name='viewport' content='width=device-width, initial-scale=1.0'>");
	server.sendContent("  <title>Tracker</title>");
	server.sendContent("\n");
	server.sendContent("  <link rel='stylesheet' href='definesCss.css'>");
	server.sendContent("  <link rel='stylesheet' href='mainCss.css'>");
	server.sendContent("  <link rel='stylesheet' href='mainCss2.css'>");
	server.sendContent("\n");
	server.sendContent("  <script src='mainJs.js'></script>");
	server.sendContent("</head>");
	server.sendContent("<body>");
	server.sendContent("  <div class='content'>");
	server.sendContent("    <div class='vspace'></div>");
	server.sendContent("    <h1>&#128301; Star Tracker</h1>");
	server.sendContent("    ");
	server.sendContent("    <p>");
	server.sendContent("\n");
	server.sendContent("    </p>");
	server.sendContent("\n");
	server.sendContent("    <br><br>");
	server.sendContent("    <div class='side-container'>");
	server.sendContent("      <div class='button main'>&#128640; Track Stars</div>");
	server.sendContent("      <div class='button main'>&#10060;</div>");
	server.sendContent("    </div>");
	server.sendContent("\n");
	server.sendContent("  </div>");
	server.sendContent("</body>");
	server.sendContent("</html>");
}

void MaincssAppPageHandler(ESP8266WebServer& server) {
	server.sendContent("\n");
	server.sendContent("* {");
	server.sendContent("  margin: 0;");
	server.sendContent("  padding: 0;");
	server.sendContent("  font-family: sans-serif;");
	server.sendContent("}");
	server.sendContent("\n");
	server.sendContent("html, body {");
	server.sendContent("  width: 100%;");
	server.sendContent("  height: 100%;");
	server.sendContent("}");
	server.sendContent("\n");
	server.sendContent("h1 { ");
	server.sendContent("  text-align: center;");
	server.sendContent("}");
	server.sendContent("\n");
	server.sendContent(".vspace {");
	server.sendContent("  height: 40px;");
	server.sendContent("}");
	server.sendContent("\n");
	server.sendContent(".content {");
	server.sendContent("  max-width: 600px !important;");
	server.sendContent("  margin: auto;");
	server.sendContent("}");
	server.sendContent("\n");
	server.sendContent("#status-bar {");
	server.sendContent("  position: fixed;");
	server.sendContent("  top: 0;");
	server.sendContent("\n");
	server.sendContent("  width: 100%;");
	server.sendContent("  height: 30px;");
	server.sendContent("\n");
	server.sendContent("  background-color: var(--color-background1);");
	server.sendContent("  z-index: 20;");
	server.sendContent("}");
	server.sendContent("\n");
	server.sendContent("#status-bar #battery {");
	server.sendContent("  z-index: 21;");
	server.sendContent("\n");
	server.sendContent("  position: relative;");
	server.sendContent("  top: 25%;");
	server.sendContent("  left: 10px;");
	server.sendContent("  height: 33%;");
	server.sendContent("  width: 20px;");
	server.sendContent("\n");
	server.sendContent("  border: solid var(--color-front1) 2px;");
	server.sendContent("  border-radius: 8%;");
	server.sendContent("}");
	server.sendContent("\n");
	server.sendContent("#status-bar #battery #battery-plus-pole {");
	server.sendContent("  position: absolute;");
	server.sendContent("  top: 27%;");
	server.sendContent("  left: 20px;");
	server.sendContent("  height: 20%;");
	server.sendContent("  width: 0px;");
	server.sendContent("\n");
	server.sendContent("  background-color: var(--color-front1);");
	server.sendContent("  border: solid var(--color-front1) 2px;");
	server.sendContent("  border-radius: 20%;");
	server.sendContent("}");
	server.sendContent("\n");
	server.sendContent("#status-bar #battery #battery-fill {");
	server.sendContent("  position: absolute;");
	server.sendContent("  top: 0;");
	server.sendContent("  left: 0;");
	server.sendContent("  height: 100%;");
	server.sendContent("  width: 80%;");
	server.sendContent("\n");
	server.sendContent("  background-color: var(--color-green);");
	server.sendContent("}");
	server.sendContent("\n");
	server.sendContent("#status-bar #battery #battery-glas {");
	server.sendContent("  z-index: 22;");
	server.sendContent("\n");
	server.sendContent("  position: absolute;");
	server.sendContent("  top: 0;");
	server.sendContent("  left: 0;");
	server.sendContent("  height: 100%;");
	server.sendContent("  width: 100%;");
	server.sendContent("\n");
	server.sendContent("  background: rgb(255,255,255);");
	server.sendContent("  background: -moz-linear-gradient(180deg, rgba(255,255,255,0) 0%, rgba(249,249,249,0.25) 50%, rgba(249,249,249,.5) 100%);");
	server.sendContent("  background: -webkit-linear-gradient(180deg, rgba(255,255,255,0) 0%, rgba(249,249,249,0.25) 50%, rgba(249,249,249,.5) 100%);");
	server.sendContent("  background: linear-gradient(180deg, rgba(255,255,255,0) 0%, rgba(249,249,249,0.25) 50%, rgba(249,249,249,.5) 100%);");
	server.sendContent("  filter: progid:DXImageTransform.Microsoft.gradient(startColorstr='#ffffff',endColorstr='#f9f9f9',GradientType=1);");
	server.sendContent("\n");
	server.sendContent("  display: none;");
	server.sendContent("}");
	server.sendContent("\n");
	server.sendContent("#status-bar #e-stop {");
	server.sendContent("  border: solid var(--color-front2) 1px;");
	server.sendContent("  border-radius: 5px;");
	server.sendContent("  padding: 5px 20px;");
	server.sendContent("\n");
	server.sendContent("  cursor: pointer;");
	server.sendContent("  text-align: center;");
	server.sendContent("\n");
	server.sendContent("  position: relative;");
	server.sendContent("  top: 0;");
	server.sendContent("  left: 50%;");
	server.sendContent("  width: 50px;");
	server.sendContent("\n");
	server.sendContent("  transform: translate(-50%, -50%);");
	server.sendContent("}");
	server.sendContent("\n");
	server.sendContent("#status-bar #e-stop:hover {");
	server.sendContent("  background-color: var(--color-front2);");
	server.sendContent("}");
	server.sendContent("\n");
	server.sendContent("#status-bar #e-stop p {");
	server.sendContent("  color: var(--color-front1);");
	server.sendContent("  font-size: .5em;");
	server.sendContent("}");
	server.sendContent("\n");
	server.sendContent("#status-bar .status {");
	server.sendContent("  position: absolute;");
	server.sendContent("  top: 8px;");
	server.sendContent("  color: var(--color-front1);");
	server.sendContent("  font-size: .7em;");
	server.sendContent("}");
	server.sendContent("\n");
	server.sendContent("#status-bar .status.left {");
	server.sendContent("  left: 50px;");
	server.sendContent("  cursor: pointer;");
	server.sendContent("}");
	server.sendContent("\n");
	server.sendContent("#status-bar-detail {");
	server.sendContent("  background-color: var(--color-background2);");
	server.sendContent("  position: absolute;");
	server.sendContent("  top: 30px;");
	server.sendContent("  left: 0;");
	server.sendContent("  width: 100%;");
	server.sendContent("  height: 0;");
	server.sendContent("  z-index: 20;");
	server.sendContent("\n");
	server.sendContent("  transition: ease .3s all;");
	server.sendContent("  overflow: hidden;");
	server.sendContent("\n");
	server.sendContent("  color: var(--color-front1);");
	server.sendContent("}");
	server.sendContent("\n");
	server.sendContent("#status-bar-detail h1 {");
	server.sendContent("  margin-top: 10px;");
	server.sendContent("  margin-left: 20px;");
	server.sendContent("}");
	server.sendContent("\n");
	server.sendContent("#status-bar-detail p {");
	server.sendContent("  margin-top: 5px;");
	server.sendContent("  margin-left: 30px;");
	server.sendContent("}");
	server.sendContent("\n");
	server.sendContent("#status-bar-detail.open {");
	server.sendContent("  height: 100%;");
	server.sendContent("  overflow-y: auto;");
	server.sendContent("}");
	server.sendContent("\n");
	server.sendContent("#status-bar .status.right {");
	server.sendContent("  right: 10px;");
	server.sendContent("}");
	server.sendContent("\n");
	server.sendContent("#status-bar #connection {");
	server.sendContent("  margin-right: 10px;");
	server.sendContent("}");
	server.sendContent("\n");
	server.sendContent(".select {");
	server.sendContent("  position: fixed;");
	server.sendContent("  width: 200vw;");
	server.sendContent("  height: 200vw;");
	server.sendContent("  min-width: 500px;");
	server.sendContent("  min-height: 500px;");
	server.sendContent("  max-width: 960px;");
	server.sendContent("  max-height: 960px;");
	server.sendContent("\n");
	server.sendContent("  border-radius: 50%;");
	server.sendContent("  margin: auto;");
	server.sendContent("\n");
	server.sendContent("  background-color: var(--color-background1);");
	server.sendContent("}");
	server.sendContent("\n");
	server.sendContent(".select.wheel {");
	server.sendContent("  position: fixed;");
	server.sendContent("  left: 50%;");
	server.sendContent("  top: 0;");
	server.sendContent("  transform: translate(-50%, var(--select-top-pos));");
	server.sendContent("\n");
	server.sendContent("  transition: all .3s ease;");
	server.sendContent("\n");
	server.sendContent("  box-shadow: 1px -1px 33px 6px rgba(0,0,0,0.75);");
	server.sendContent("  -webkit-box-shadow: 1px -1px 33px 6px rgba(0,0,0,0.75);");
	server.sendContent("  -moz-box-shadow: 1px -1px 33px 6px rgba(0,0,0,0.75);");
	server.sendContent("\n");
	server.sendContent("  z-index: 20;");
	server.sendContent("}");
}

#endif